/*
 Highmaps JS v6.1.0-modified (2018-06-15)

 (c) 2011-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(T,I){"object"===typeof module&&module.exports?module.exports=T.document?I(T):I:T.Highcharts=I(T)})("undefined"!==typeof window?window:this,function(T){var I=function(){var a="undefined"===typeof T?window:T,y=a.document,z=a.navigator&&a.navigator.userAgent||"",B=y&&y.createElementNS&&!!y.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,l=/(edge|msie|trident)/i.test(z)&&!a.opera,f=-1!==z.indexOf("Firefox"),g=-1!==z.indexOf("Chrome"),r=f&&4>parseInt(z.split("Firefox/")[1],
10);return a.Highcharts?a.Highcharts.error(16,!0):{product:"Highmaps",version:"6.1.0-modified",deg2rad:2*Math.PI/360,doc:y,hasBidiBug:r,hasTouch:y&&void 0!==y.documentElement.ontouchstart,isMS:l,isWebKit:-1!==z.indexOf("AppleWebKit"),isFirefox:f,isChrome:g,isSafari:!g&&-1!==z.indexOf("Safari"),isTouchDevice:/(Mobile|Android|Windows Phone)/.test(z),SVG_NS:"http://www.w3.org/2000/svg",chartCount:0,seriesTypes:{},symbolSizes:{},svg:B,win:a,marginNames:["plotTop","marginRight","marginBottom","plotLeft"],
noop:function(){},charts:[]}}();(function(a){a.timers=[];var y=a.charts,z=a.doc,B=a.win;a.error=function(l,f){l=a.isNumber(l)?"Highcharts error #"+l+": www.highcharts.com/errors/"+l:l;if(f)throw Error(l);B.console&&console.log(l)};a.Fx=function(a,f,g){this.options=f;this.elem=a;this.prop=g};a.Fx.prototype={dSetter:function(){var a=this.paths[0],f=this.paths[1],g=[],r=this.now,w=a.length,p;if(1===r)g=this.toD;else if(w===f.length&&1>r)for(;w--;)p=parseFloat(a[w]),g[w]=isNaN(p)?f[w]:r*parseFloat(f[w]-
p)+p;else g=f;this.elem.attr("d",g,null,!0)},update:function(){var a=this.elem,f=this.prop,g=this.now,r=this.options.step;if(this[f+"Setter"])this[f+"Setter"]();else a.attr?a.element&&a.attr(f,g,null,!0):a.style[f]=g+this.unit;r&&r.call(a,g,this)},run:function(l,f,g){var r=this,w=r.options,p=function(a){return p.stopped?!1:r.step(a)},e=B.requestAnimationFrame||function(a){setTimeout(a,13)},d=function(){for(var k=0;k<a.timers.length;k++)a.timers[k]()||a.timers.splice(k--,1);a.timers.length&&e(d)};
l!==f||this.elem["forceAnimate:"+this.prop]?(this.startTime=+new Date,this.start=l,this.end=f,this.unit=g,this.now=this.start,this.pos=0,p.elem=this.elem,p.prop=this.prop,p()&&1===a.timers.push(p)&&e(d)):(delete w.curAnim[this.prop],w.complete&&0===a.keys(w.curAnim).length&&w.complete.call(this.elem))},step:function(l){var f=+new Date,g,r=this.options,w=this.elem,p=r.complete,e=r.duration,d=r.curAnim;w.attr&&!w.element?l=!1:l||f>=e+this.startTime?(this.now=this.end,this.pos=1,this.update(),g=d[this.prop]=
!0,a.objectEach(d,function(a){!0!==a&&(g=!1)}),g&&p&&p.call(w),l=!1):(this.pos=r.easing((f-this.startTime)/e),this.now=this.start+(this.end-this.start)*this.pos,this.update(),l=!0);return l},initPath:function(l,f,g){function r(a){var b,c;for(h=a.length;h--;)b="M"===a[h]||"L"===a[h],c=/[a-zA-Z]/.test(a[h+3]),b&&c&&a.splice(h+1,0,a[h+1],a[h+2],a[h+1],a[h+2])}function w(a,b){for(;a.length<c;){a[0]=b[c-a.length];var d=a.slice(0,q);[].splice.apply(a,[0,0].concat(d));n&&(d=a.slice(a.length-q),[].splice.apply(a,
[a.length,0].concat(d)),h--)}a[0]="M"}function p(a,h){for(var d=(c-a.length)/q;0<d&&d--;)b=a.slice().splice(a.length/J-q,q*J),b[0]=h[c-q-d*q],t&&(b[q-6]=b[q-2],b[q-5]=b[q-1]),[].splice.apply(a,[a.length/J,0].concat(b)),n&&d--}f=f||"";var e,d=l.startX,k=l.endX,t=-1<f.indexOf("C"),q=t?7:3,c,b,h;f=f.split(" ");g=g.slice();var n=l.isArea,J=n?2:1,H;t&&(r(f),r(g));if(d&&k){for(h=0;h<d.length;h++)if(d[h]===k[0]){e=h;break}else if(d[0]===k[k.length-d.length+h]){e=h;H=!0;break}void 0===e&&(f=[])}f.length&&
a.isNumber(e)&&(c=g.length+e*J*q,H?(w(f,g),p(g,f)):(w(g,f),p(f,g)));return[f,g]}};a.Fx.prototype.fillSetter=a.Fx.prototype.strokeSetter=function(){this.elem.attr(this.prop,a.color(this.start).tweenTo(a.color(this.end),this.pos),null,!0)};a.merge=function(){var l,f=arguments,g,r={},w=function(g,e){"object"!==typeof g&&(g={});a.objectEach(e,function(d,k){!a.isObject(d,!0)||a.isClass(d)||a.isDOMElement(d)?g[k]=e[k]:g[k]=w(g[k]||{},d)});return g};!0===f[0]&&(r=f[1],f=Array.prototype.slice.call(f,2));
g=f.length;for(l=0;l<g;l++)r=w(r,f[l]);return r};a.pInt=function(a,f){return parseInt(a,f||10)};a.isString=function(a){return"string"===typeof a};a.isArray=function(a){a=Object.prototype.toString.call(a);return"[object Array]"===a||"[object Array Iterator]"===a};a.isObject=function(l,f){return!!l&&"object"===typeof l&&(!f||!a.isArray(l))};a.isDOMElement=function(l){return a.isObject(l)&&"number"===typeof l.nodeType};a.isClass=function(l){var f=l&&l.constructor;return!(!a.isObject(l,!0)||a.isDOMElement(l)||
!f||!f.name||"Object"===f.name)};a.isNumber=function(a){return"number"===typeof a&&!isNaN(a)&&Infinity>a&&-Infinity<a};a.erase=function(a,f){for(var g=a.length;g--;)if(a[g]===f){a.splice(g,1);break}};a.defined=function(a){return void 0!==a&&null!==a};a.attr=function(l,f,g){var r;a.isString(f)?a.defined(g)?l.setAttribute(f,g):l&&l.getAttribute&&((r=l.getAttribute(f))||"class"!==f||(r=l.getAttribute(f+"Name"))):a.defined(f)&&a.isObject(f)&&a.objectEach(f,function(a,g){l.setAttribute(g,a)});return r};
a.splat=function(l){return a.isArray(l)?l:[l]};a.syncTimeout=function(a,f,g){if(f)return setTimeout(a,f,g);a.call(0,g)};a.clearTimeout=function(l){a.defined(l)&&clearTimeout(l)};a.extend=function(a,f){var g;a||(a={});for(g in f)a[g]=f[g];return a};a.pick=function(){var a=arguments,f,g,r=a.length;for(f=0;f<r;f++)if(g=a[f],void 0!==g&&null!==g)return g};a.css=function(l,f){a.isMS&&!a.svg&&f&&void 0!==f.opacity&&(f.filter="alpha(opacity\x3d"+100*f.opacity+")");a.extend(l.style,f)};a.createElement=function(l,
f,g,r,w){l=z.createElement(l);var p=a.css;f&&a.extend(l,f);w&&p(l,{padding:0,border:"none",margin:0});g&&p(l,g);r&&r.appendChild(l);return l};a.extendClass=function(l,f){var g=function(){};g.prototype=new l;a.extend(g.prototype,f);return g};a.pad=function(a,f,g){return Array((f||2)+1-String(a).replace("-","").length).join(g||0)+a};a.relativeLength=function(a,f,g){return/%$/.test(a)?f*parseFloat(a)/100+(g||0):parseFloat(a)};a.wrap=function(a,f,g){var l=a[f];a[f]=function(){var a=Array.prototype.slice.call(arguments),
f=arguments,e=this;e.proceed=function(){l.apply(e,arguments.length?arguments:f)};a.unshift(l);a=g.apply(this,a);e.proceed=null;return a}};a.formatSingle=function(l,f,g){var r=/\.([0-9])/,w=a.defaultOptions.lang;/f$/.test(l)?(g=(g=l.match(r))?g[1]:-1,null!==f&&(f=a.numberFormat(f,g,w.decimalPoint,-1<l.indexOf(",")?w.thousandsSep:""))):f=(g||a.time).dateFormat(l,f);return f};a.format=function(l,f,g){for(var r="{",w=!1,p,e,d,k,t=[],q;l;){r=l.indexOf(r);if(-1===r)break;p=l.slice(0,r);if(w){p=p.split(":");
e=p.shift().split(".");k=e.length;q=f;for(d=0;d<k;d++)q&&(q=q[e[d]]);p.length&&(q=a.formatSingle(p.join(":"),q,g));t.push(q)}else t.push(p);l=l.slice(r+1);r=(w=!w)?"}":"{"}t.push(l);return t.join("")};a.getMagnitude=function(a){return Math.pow(10,Math.floor(Math.log(a)/Math.LN10))};a.normalizeTickInterval=function(l,f,g,r,w){var p,e=l;g=a.pick(g,1);p=l/g;f||(f=w?[1,1.2,1.5,2,2.5,3,4,5,6,8,10]:[1,2,2.5,5,10],!1===r&&(1===g?f=a.grep(f,function(a){return 0===a%1}):.1>=g&&(f=[1/g])));for(r=0;r<f.length&&
!(e=f[r],w&&e*g>=l||!w&&p<=(f[r]+(f[r+1]||f[r]))/2);r++);return e=a.correctFloat(e*g,-Math.round(Math.log(.001)/Math.LN10))};a.stableSort=function(a,f){var g=a.length,l,w;for(w=0;w<g;w++)a[w].safeI=w;a.sort(function(a,e){l=f(a,e);return 0===l?a.safeI-e.safeI:l});for(w=0;w<g;w++)delete a[w].safeI};a.arrayMin=function(a){for(var f=a.length,g=a[0];f--;)a[f]<g&&(g=a[f]);return g};a.arrayMax=function(a){for(var f=a.length,g=a[0];f--;)a[f]>g&&(g=a[f]);return g};a.destroyObjectProperties=function(l,f){a.objectEach(l,
function(a,r){a&&a!==f&&a.destroy&&a.destroy();delete l[r]})};a.discardElement=function(l){var f=a.garbageBin;f||(f=a.createElement("div"));l&&f.appendChild(l);f.innerHTML=""};a.correctFloat=function(a,f){return parseFloat(a.toPrecision(f||14))};a.setAnimation=function(l,f){f.renderer.globalAnimation=a.pick(l,f.options.chart.animation,!0)};a.animObject=function(l){return a.isObject(l)?a.merge(l):{duration:l?500:0}};a.timeUnits={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5,month:24192E5,
year:314496E5};a.numberFormat=function(l,f,g,r){l=+l||0;f=+f;var w=a.defaultOptions.lang,p=(l.toString().split(".")[1]||"").split("e")[0].length,e,d,k=l.toString().split("e");-1===f?f=Math.min(p,20):a.isNumber(f)?f&&k[1]&&0>k[1]&&(e=f+ +k[1],0<=e?(k[0]=(+k[0]).toExponential(e).split("e")[0],f=e):(k[0]=k[0].split(".")[0]||0,l=20>f?(k[0]*Math.pow(10,k[1])).toFixed(f):0,k[1]=0)):f=2;d=(Math.abs(k[1]?k[0]:l)+Math.pow(10,-Math.max(f,p)-1)).toFixed(f);p=String(a.pInt(d));e=3<p.length?p.length%3:0;g=a.pick(g,
w.decimalPoint);r=a.pick(r,w.thousandsSep);l=(0>l?"-":"")+(e?p.substr(0,e)+r:"");l+=p.substr(e).replace(/(\d{3})(?=\d)/g,"$1"+r);f&&(l+=g+d.slice(-f));k[1]&&0!==+l&&(l+="e"+k[1]);return l};Math.easeInOutSine=function(a){return-.5*(Math.cos(Math.PI*a)-1)};a.getStyle=function(l,f,g){if("width"===f)return Math.max(0,Math.min(l.offsetWidth,l.scrollWidth)-a.getStyle(l,"padding-left")-a.getStyle(l,"padding-right"));if("height"===f)return Math.max(0,Math.min(l.offsetHeight,l.scrollHeight)-a.getStyle(l,"padding-top")-
a.getStyle(l,"padding-bottom"));B.getComputedStyle||a.error(27,!0);if(l=B.getComputedStyle(l,void 0))l=l.getPropertyValue(f),a.pick(g,"opacity"!==f)&&(l=a.pInt(l));return l};a.inArray=function(l,f,g){return(a.indexOfPolyfill||Array.prototype.indexOf).call(f,l,g)};a.grep=function(l,f){return(a.filterPolyfill||Array.prototype.filter).call(l,f)};a.find=Array.prototype.find?function(a,f){return a.find(f)}:function(a,f){var g,l=a.length;for(g=0;g<l;g++)if(f(a[g],g))return a[g]};a.some=function(l,f,g){return(a.somePolyfill||
Array.prototype.some).call(l,f,g)};a.map=function(a,f){for(var g=[],l=0,w=a.length;l<w;l++)g[l]=f.call(a[l],a[l],l,a);return g};a.keys=function(l){return(a.keysPolyfill||Object.keys).call(void 0,l)};a.reduce=function(l,f,g){return(a.reducePolyfill||Array.prototype.reduce).call(l,f,g)};a.offset=function(a){var f=z.documentElement;a=a.parentElement||a.parentNode?a.getBoundingClientRect():{top:0,left:0};return{top:a.top+(B.pageYOffset||f.scrollTop)-(f.clientTop||0),left:a.left+(B.pageXOffset||f.scrollLeft)-
(f.clientLeft||0)}};a.stop=function(l,f){for(var g=a.timers.length;g--;)a.timers[g].elem!==l||f&&f!==a.timers[g].prop||(a.timers[g].stopped=!0)};a.each=function(l,f,g){return(a.forEachPolyfill||Array.prototype.forEach).call(l,f,g)};a.objectEach=function(a,f,g){for(var l in a)a.hasOwnProperty(l)&&f.call(g||a[l],a[l],l,a)};a.addEvent=function(l,f,g,r){var w,p=l.addEventListener||a.addEventListenerPolyfill;w="function"===typeof l&&l.prototype?l.prototype.protoEvents=l.prototype.protoEvents||{}:l.hcEvents=
l.hcEvents||{};a.Point&&l instanceof a.Point&&l.series&&l.series.chart&&(l.series.chart.runTrackerClick=!0);p&&p.call(l,f,g,!1);w[f]||(w[f]=[]);w[f].push(g);r&&a.isNumber(r.order)&&(g.order=r.order,w[f].sort(function(a,d){return a.order-d.order}));return function(){a.removeEvent(l,f,g)}};a.removeEvent=function(l,f,g){function r(d,e){var k=l.removeEventListener||a.removeEventListenerPolyfill;k&&k.call(l,d,e,!1)}function w(d){var e,g;l.nodeName&&(f?(e={},e[f]=!0):e=d,a.objectEach(e,function(a,c){if(d[c])for(g=
d[c].length;g--;)r(c,d[c][g])}))}var p,e;a.each(["protoEvents","hcEvents"],function(d){var k=l[d];k&&(f?(p=k[f]||[],g?(e=a.inArray(g,p),-1<e&&(p.splice(e,1),k[f]=p),r(f,g)):(w(k),k[f]=[])):(w(k),l[d]={}))})};a.fireEvent=function(l,f,g,r){var w,p,e,d,k;g=g||{};z.createEvent&&(l.dispatchEvent||l.fireEvent)?(w=z.createEvent("Events"),w.initEvent(f,!0,!0),a.extend(w,g),l.dispatchEvent?l.dispatchEvent(w):l.fireEvent(f,w)):a.each(["protoEvents","hcEvents"],function(t){if(l[t])for(p=l[t][f]||[],e=p.length,
g.target||a.extend(g,{preventDefault:function(){g.defaultPrevented=!0},target:l,type:f}),d=0;d<e;d++)(k=p[d])&&!1===k.call(l,g)&&g.preventDefault()});r&&!g.defaultPrevented&&r.call(l,g)};a.animate=function(l,f,g){var r,w="",p,e,d;a.isObject(g)||(d=arguments,g={duration:d[2],easing:d[3],complete:d[4]});a.isNumber(g.duration)||(g.duration=400);g.easing="function"===typeof g.easing?g.easing:Math[g.easing]||Math.easeInOutSine;g.curAnim=a.merge(f);a.objectEach(f,function(d,t){a.stop(l,t);e=new a.Fx(l,
g,t);p=null;"d"===t?(e.paths=e.initPath(l,l.d,f.d),e.toD=f.d,r=0,p=1):l.attr?r=l.attr(t):(r=parseFloat(a.getStyle(l,t))||0,"opacity"!==t&&(w="px"));p||(p=d);p&&p.match&&p.match("px")&&(p=p.replace(/px/g,""));e.run(r,p,w)})};a.seriesType=function(l,f,g,r,w){var p=a.getOptions(),e=a.seriesTypes;p.plotOptions[l]=a.merge(p.plotOptions[f],g);e[l]=a.extendClass(e[f]||function(){},r);e[l].prototype.type=l;w&&(e[l].prototype.pointClass=a.extendClass(a.Point,w));return e[l]};a.uniqueKey=function(){var a=Math.random().toString(36).substring(2,
9),f=0;return function(){return"highcharts-"+a+"-"+f++}}();B.jQuery&&(B.jQuery.fn.highcharts=function(){var l=[].slice.call(arguments);if(this[0])return l[0]?(new (a[a.isString(l[0])?l.shift():"Chart"])(this[0],l[0],l[1]),this):y[a.attr(this[0],"data-highcharts-chart")]})})(I);(function(a){var y=a.each,z=a.isNumber,B=a.map,l=a.merge,f=a.pInt;a.Color=function(g){if(!(this instanceof a.Color))return new a.Color(g);this.init(g)};a.Color.prototype={parsers:[{regex:/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,
parse:function(a){return[f(a[1]),f(a[2]),f(a[3]),parseFloat(a[4],10)]}},{regex:/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,parse:function(a){return[f(a[1]),f(a[2]),f(a[3]),1]}}],names:{none:"rgba(255,255,255,0)",white:"#ffffff",black:"#000000"},init:function(g){var f,w,p,e;if((this.input=g=this.names[g&&g.toLowerCase?g.toLowerCase():""]||g)&&g.stops)this.stops=B(g.stops,function(d){return new a.Color(d[1])});else if(g&&g.charAt&&"#"===g.charAt()&&(f=g.length,g=parseInt(g.substr(1),
16),7===f?w=[(g&16711680)>>16,(g&65280)>>8,g&255,1]:4===f&&(w=[(g&3840)>>4|(g&3840)>>8,(g&240)>>4|g&240,(g&15)<<4|g&15,1])),!w)for(p=this.parsers.length;p--&&!w;)e=this.parsers[p],(f=e.regex.exec(g))&&(w=e.parse(f));this.rgba=w||[]},get:function(a){var g=this.input,f=this.rgba,p;this.stops?(p=l(g),p.stops=[].concat(p.stops),y(this.stops,function(e,d){p.stops[d]=[p.stops[d][0],e.get(a)]})):p=f&&z(f[0])?"rgb"===a||!a&&1===f[3]?"rgb("+f[0]+","+f[1]+","+f[2]+")":"a"===a?f[3]:"rgba("+f.join(",")+")":g;
return p},brighten:function(a){var g,l=this.rgba;if(this.stops)y(this.stops,function(g){g.brighten(a)});else if(z(a)&&0!==a)for(g=0;3>g;g++)l[g]+=f(255*a),0>l[g]&&(l[g]=0),255<l[g]&&(l[g]=255);return this},setOpacity:function(a){this.rgba[3]=a;return this},tweenTo:function(a,f){var g=this.rgba,p=a.rgba;p.length&&g&&g.length?(a=1!==p[3]||1!==g[3],f=(a?"rgba(":"rgb(")+Math.round(p[0]+(g[0]-p[0])*(1-f))+","+Math.round(p[1]+(g[1]-p[1])*(1-f))+","+Math.round(p[2]+(g[2]-p[2])*(1-f))+(a?","+(p[3]+(g[3]-
p[3])*(1-f)):"")+")"):f=a.input||"none";return f}};a.color=function(g){return new a.Color(g)}})(I);(function(a){var y=a.defined,z=a.each,B=a.extend,l=a.merge,f=a.pick,g=a.timeUnits,r=a.win;a.Time=function(a){this.update(a,!1)};a.Time.prototype={defaultOptions:{},update:function(g){var p=f(g&&g.useUTC,!0),e=this;this.options=g=l(!0,this.options||{},g);this.Date=g.Date||r.Date;this.timezoneOffset=(this.useUTC=p)&&g.timezoneOffset;this.getTimezoneOffset=this.timezoneOffsetFunction();(this.variableTimezone=
!(p&&!g.getTimezoneOffset&&!g.timezone))||this.timezoneOffset?(this.get=function(a,k){var d=k.getTime(),g=d-e.getTimezoneOffset(k);k.setTime(g);a=k["getUTC"+a]();k.setTime(d);return a},this.set=function(d,k,g){var q;if(-1!==a.inArray(d,["Milliseconds","Seconds","Minutes"]))k["set"+d](g);else q=e.getTimezoneOffset(k),q=k.getTime()-q,k.setTime(q),k["setUTC"+d](g),d=e.getTimezoneOffset(k),q=k.getTime()+d,k.setTime(q)}):p?(this.get=function(a,e){return e["getUTC"+a]()},this.set=function(a,e,g){return e["setUTC"+
a](g)}):(this.get=function(a,e){return e["get"+a]()},this.set=function(a,e,g){return e["set"+a](g)})},makeTime:function(g,p,e,d,k,t){var q,c,b;this.useUTC?(q=this.Date.UTC.apply(0,arguments),c=this.getTimezoneOffset(q),q+=c,b=this.getTimezoneOffset(q),c!==b?q+=b-c:c-36E5!==this.getTimezoneOffset(q-36E5)||a.isSafari||(q-=36E5)):q=(new this.Date(g,p,f(e,1),f(d,0),f(k,0),f(t,0))).getTime();return q},timezoneOffsetFunction:function(){var g=this,f=this.options,e=r.moment;if(!this.useUTC)return function(a){return 6E4*
(new Date(a)).getTimezoneOffset()};if(f.timezone){if(e)return function(a){return 6E4*-e.tz(a,f.timezone).utcOffset()};a.error(25)}return this.useUTC&&f.getTimezoneOffset?function(a){return 6E4*f.getTimezoneOffset(a)}:function(){return 6E4*(g.timezoneOffset||0)}},dateFormat:function(g,f,e){if(!a.defined(f)||isNaN(f))return a.defaultOptions.lang.invalidDate||"";g=a.pick(g,"%Y-%m-%d %H:%M:%S");var d=this,k=new this.Date(f),t=this.get("Hours",k),q=this.get("Day",k),c=this.get("Date",k),b=this.get("Month",
k),h=this.get("FullYear",k),n=a.defaultOptions.lang,p=n.weekdays,l=n.shortWeekdays,A=a.pad,k=a.extend({a:l?l[q]:p[q].substr(0,3),A:p[q],d:A(c),e:A(c,2," "),w:q,b:n.shortMonths[b],B:n.months[b],m:A(b+1),o:b+1,y:h.toString().substr(2,2),Y:h,H:A(t),k:t,I:A(t%12||12),l:t%12||12,M:A(d.get("Minutes",k)),p:12>t?"AM":"PM",P:12>t?"am":"pm",S:A(k.getSeconds()),L:A(Math.round(f%1E3),3)},a.dateFormats);a.objectEach(k,function(a,b){for(;-1!==g.indexOf("%"+b);)g=g.replace("%"+b,"function"===typeof a?a.call(d,f):
a)});return e?g.substr(0,1).toUpperCase()+g.substr(1):g},getTimeTicks:function(a,p,e,d){var k=this,t=[],q={},c,b=new k.Date(p),h=a.unitRange,n=a.count||1,l;if(y(p)){k.set("Milliseconds",b,h>=g.second?0:n*Math.floor(k.get("Milliseconds",b)/n));h>=g.second&&k.set("Seconds",b,h>=g.minute?0:n*Math.floor(k.get("Seconds",b)/n));h>=g.minute&&k.set("Minutes",b,h>=g.hour?0:n*Math.floor(k.get("Minutes",b)/n));h>=g.hour&&k.set("Hours",b,h>=g.day?0:n*Math.floor(k.get("Hours",b)/n));h>=g.day&&k.set("Date",b,h>=
g.month?1:n*Math.floor(k.get("Date",b)/n));h>=g.month&&(k.set("Month",b,h>=g.year?0:n*Math.floor(k.get("Month",b)/n)),c=k.get("FullYear",b));h>=g.year&&k.set("FullYear",b,c-c%n);h===g.week&&k.set("Date",b,k.get("Date",b)-k.get("Day",b)+f(d,1));c=k.get("FullYear",b);d=k.get("Month",b);var H=k.get("Date",b),A=k.get("Hours",b);p=b.getTime();k.variableTimezone&&(l=e-p>4*g.month||k.getTimezoneOffset(p)!==k.getTimezoneOffset(e));b=b.getTime();for(p=1;b<e;)t.push(b),b=h===g.year?k.makeTime(c+p*n,0):h===
g.month?k.makeTime(c,d+p*n):!l||h!==g.day&&h!==g.week?l&&h===g.hour&&1<n?k.makeTime(c,d,H,A+p*n):b+h*n:k.makeTime(c,d,H+p*n*(h===g.day?1:7)),p++;t.push(b);h<=g.hour&&1E4>t.length&&z(t,function(a){0===a%18E5&&"000000000"===k.dateFormat("%H%M%S%L",a)&&(q[a]="day")})}t.info=B(a,{higherRanks:q,totalRange:h*n});return t}}})(I);(function(a){var y=a.merge;a.defaultOptions={symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),
shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:" "},global:{},time:a.Time.prototype.defaultOptions,chart:{borderRadius:0,colorCount:10,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],resetZoomButton:{theme:{zIndex:6},position:{align:"right",x:-10,y:10}},
width:null,height:null},title:{text:"Chart title",align:"center",margin:15,widthAdjust:-44},subtitle:{text:"",align:"center",widthAdjust:-44},plotOptions:{},labels:{style:{position:"absolute",color:"#333333"}},legend:{enabled:!0,align:"center",alignColumns:!0,layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#999999",borderRadius:0,navigation:{},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},squareSymbol:!0,symbolPadding:5,verticalAlign:"bottom",x:0,
y:0,title:{}},loading:{},tooltip:{enabled:!0,animation:a.svg,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},footerFormat:"",padding:8,snap:a.isTouchDevice?25:10,headerFormat:'\x3cspan class\x3d"highcharts-header"\x3e{point.key}\x3c/span\x3e\x3cbr/\x3e',pointFormat:'\x3cspan class\x3d"highcharts-color-{point.colorIndex}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cspan class\x3d"highcharts-strong"\x3e{point.y}\x3c/span\x3e\x3cbr/\x3e'},
credits:{enabled:!0,href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},text:"Highcharts.com"}};a.setOptions=function(z){a.defaultOptions=y(!0,a.defaultOptions,z);a.time.update(y(a.defaultOptions.global,a.defaultOptions.time),!1);return a.defaultOptions};a.getOptions=function(){return a.defaultOptions};a.defaultPlotOptions=a.defaultOptions.plotOptions;a.time=new a.Time(y(a.defaultOptions.global,a.defaultOptions.time));a.dateFormat=function(z,y,l){return a.time.dateFormat(z,
y,l)}})(I);(function(a){var y,z,B=a.addEvent,l=a.animate,f=a.attr,g=a.charts,r=a.color,w=a.css,p=a.createElement,e=a.defined,d=a.deg2rad,k=a.destroyObjectProperties,t=a.doc,q=a.each,c=a.extend,b=a.erase,h=a.grep,n=a.hasTouch,J=a.inArray,H=a.isArray,A=a.isFirefox,G=a.isMS,v=a.isObject,x=a.isString,C=a.isWebKit,E=a.merge,M=a.noop,K=a.objectEach,m=a.pick,D=a.pInt,N=a.removeEvent,u=a.splat,F=a.stop,S=a.svg,Q=a.SVG_NS,O=a.symbolSizes,P=a.win;y=a.SVGElement=function(){return this};c(y.prototype,{opacity:1,
SVG_NS:Q,textProps:"direction fontSize fontWeight fontFamily fontStyle color lineHeight width textAlign textDecoration textOverflow textOutline".split(" "),init:function(a,b){this.element="span"===b?p(b):t.createElementNS(this.SVG_NS,b);this.renderer=a},animate:function(b,c,u){c=a.animObject(m(c,this.renderer.globalAnimation,!0));0!==c.duration?(u&&(c.complete=u),l(this,b,c)):(this.attr(b,null,u),c.step&&c.step.call(this));return this},complexColor:function(b,m,c){var u=this.renderer,h,D,L,d,n,k,
x,g,f,F,C,N=[],v;a.fireEvent(this.renderer,"complexColor",{args:arguments},function(){b.radialGradient?D="radialGradient":b.linearGradient&&(D="linearGradient");D&&(L=b[D],n=u.gradients,x=b.stops,F=c.radialReference,H(L)&&(b[D]=L={x1:L[0],y1:L[1],x2:L[2],y2:L[3],gradientUnits:"userSpaceOnUse"}),"radialGradient"===D&&F&&!e(L.gradientUnits)&&(d=L,L=E(L,u.getRadialAttr(F,d),{gradientUnits:"userSpaceOnUse"})),K(L,function(a,b){"id"!==b&&N.push(b,a)}),K(x,function(a){N.push(a)}),N=N.join(","),n[N]?C=n[N].attr("id"):
(L.id=C=a.uniqueKey(),n[N]=k=u.createElement(D).attr(L).add(u.defs),k.radAttr=d,k.stops=[],q(x,function(b){0===b[1].indexOf("rgba")?(h=a.color(b[1]),g=h.get("rgb"),f=h.get("a")):(g=b[1],f=1);b=u.createElement("stop").attr({offset:b[0],"stop-color":g,"stop-opacity":f}).add(k);k.stops.push(b)})),v="url("+u.url+"#"+C+")",c.setAttribute(m,v),c.gradient=N,b.toString=function(){return v})})},applyTextOutline:function(m){var c=this.element,u,h,D,L,e;-1!==m.indexOf("contrast")&&(m=m.replace(/contrast/g,this.renderer.getContrast(c.style.fill)));
m=m.split(" ");h=m[m.length-1];if((D=m[0])&&"none"!==D&&a.svg){this.fakeTS=!0;m=[].slice.call(c.getElementsByTagName("tspan"));this.ySetter=this.xSetter;D=D.replace(/(^[\d\.]+)(.*?)$/g,function(a,b,m){return 2*b+m});for(e=m.length;e--;)u=m[e],"highcharts-text-outline"===u.getAttribute("class")&&b(m,c.removeChild(u));L=c.firstChild;q(m,function(a,b){0===b&&(a.setAttribute("x",c.getAttribute("x")),b=c.getAttribute("y"),a.setAttribute("y",b||0),null===b&&c.setAttribute("y",0));a=a.cloneNode(1);f(a,{"class":"highcharts-text-outline",
fill:h,stroke:h,"stroke-width":D,"stroke-linejoin":"round"});c.insertBefore(a,L)})}},attr:function(a,b,m,c){var u,h=this.element,D,e=this,d,L;"string"===typeof a&&void 0!==b&&(u=a,a={},a[u]=b);"string"===typeof a?e=(this[a+"Getter"]||this._defaultGetter).call(this,a,h):(K(a,function(b,m){d=!1;c||F(this,m);this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)$/.test(m)&&(D||(this.symbolAttr(a),D=!0),d=!0);!this.rotation||"x"!==m&&"y"!==m||(this.doTransform=!0);d||(L=this[m+"Setter"]||
this._defaultSetter,L.call(this,b,m,h))},this),this.afterSetters());m&&m.call(this);return e},afterSetters:function(){this.doTransform&&(this.updateTransform(),this.doTransform=!1)},addClass:function(a,b){var m=this.attr("class")||"";-1===m.indexOf(a)&&(b||(a=(m+(m?" ":"")+a).replace("  "," ")),this.attr("class",a));return this},hasClass:function(a){return-1!==J(a,(this.attr("class")||"").split(" "))},removeClass:function(a){return this.attr("class",(this.attr("class")||"").replace(a,""))},symbolAttr:function(a){var b=
this;q("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=m(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a,b){var m;b=b||a.strokeWidth||0;m=Math.round(b)%2/2;a.x=Math.floor(a.x||this.x||0)+m;a.y=Math.floor(a.y||this.y||0)+m;a.width=Math.floor((a.width||this.width||0)-2*m);a.height=Math.floor((a.height||this.height||0)-
2*m);e(a.strokeWidth)&&(a.strokeWidth=b);return a},css:function(a){var b=this.styles,m={},u=this.element,h,e="",d,n=!b,L=["textOutline","textOverflow","width"];a&&a.color&&(a.fill=a.color);b&&K(a,function(a,c){a!==b[c]&&(m[c]=a,n=!0)});n&&(b&&(a=c(b,m)),a&&(null===a.width||"auto"===a.width?delete this.textWidth:"text"===u.nodeName.toLowerCase()&&a.width&&(h=this.textWidth=D(a.width))),this.styles=a,h&&!S&&this.renderer.forExport&&delete a.width,u.namespaceURI===this.SVG_NS?(d=function(a,b){return"-"+
b.toLowerCase()},K(a,function(a,b){-1===J(b,L)&&(e+=b.replace(/([A-Z])/g,d)+":"+a+";")}),e&&f(u,"style",e)):w(u,a),this.added&&("text"===this.element.nodeName&&this.renderer.buildText(this),a&&a.textOutline&&this.applyTextOutline(a.textOutline)));return this},getStyle:function(a){return P.getComputedStyle(this.element||this,"").getPropertyValue(a)},strokeWidth:function(){var a=this.getStyle("stroke-width"),b;a.indexOf("px")===a.length-2?a=D(a):(b=t.createElementNS(Q,"rect"),f(b,{width:a,"stroke-width":0}),
this.element.parentNode.appendChild(b),a=b.getBBox().width,b.parentNode.removeChild(b));return a},on:function(a,b){var m=this,c=m.element;n&&"click"===a?(c.ontouchstart=function(a){m.touchEventFired=Date.now();a.preventDefault();b.call(c,a)},c.onclick=function(a){(-1===P.navigator.userAgent.indexOf("Android")||1100<Date.now()-(m.touchEventFired||0))&&b.call(c,a)}):c["on"+a]=b;return this},setRadialReference:function(a){var b=this.renderer.gradients[this.element.gradient];this.element.radialReference=
a;b&&b.radAttr&&b.animate(this.renderer.getRadialAttr(a,b.radAttr));return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(a){this.inverted=a;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,u=this.scaleY,h=this.inverted,D=this.rotation,d=this.matrix,n=this.element;h&&(a+=this.width,b+=this.height);a=["translate("+a+","+b+")"];e(d)&&a.push("matrix("+d.join(",")+")");h?a.push("rotate(90) scale(-1,1)"):
D&&a.push("rotate("+D+" "+m(this.rotationOriginX,n.getAttribute("x"),0)+" "+m(this.rotationOriginY,n.getAttribute("y")||0)+")");(e(c)||e(u))&&a.push("scale("+m(c,1)+" "+m(u,1)+")");a.length&&n.setAttribute("transform",a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,c,u){var h,D,e,d,n={};D=this.renderer;e=D.alignedObjects;var k,L;if(a){if(this.alignOptions=a,this.alignByTranslate=c,!u||x(u))this.alignTo=h=u||"renderer",b(e,this),e.push(this),
u=null}else a=this.alignOptions,c=this.alignByTranslate,h=this.alignTo;u=m(u,D[h],D);h=a.align;D=a.verticalAlign;e=(u.x||0)+(a.x||0);d=(u.y||0)+(a.y||0);"right"===h?k=1:"center"===h&&(k=2);k&&(e+=(u.width-(a.width||0))/k);n[c?"translateX":"x"]=Math.round(e);"bottom"===D?L=1:"middle"===D&&(L=2);L&&(d+=(u.height-(a.height||0))/L);n[c?"translateY":"y"]=Math.round(d);this[this.placed?"animate":"attr"](n);this.placed=!0;this.alignAttr=n;return this},getBBox:function(a,b){var u,h=this.renderer,D,n=this.element,
k=this.styles,x,L=this.textStr,g,E=h.cache,f=h.cacheKeys,F;b=m(b,this.rotation);D=b*d;x=n&&y.prototype.getStyle.call(n,"font-size");e(L)&&(F=L.toString(),-1===F.indexOf("\x3c")&&(F=F.replace(/[0-9]/g,"0")),F+=["",b||0,x,this.textWidth,k&&k.textOverflow].join());F&&!a&&(u=E[F]);if(!u){if(n.namespaceURI===this.SVG_NS||h.forExport){try{(g=this.fakeTS&&function(a){q(n.querySelectorAll(".highcharts-text-outline"),function(b){b.style.display=a})})&&g("none"),u=n.getBBox?c({},n.getBBox()):{width:n.offsetWidth,
height:n.offsetHeight},g&&g("")}catch(X){}if(!u||0>u.width)u={width:0,height:0}}else u=this.htmlGetBBox();h.isSVG&&(a=u.width,h=u.height,k&&"11px"===k.fontSize&&17===Math.round(h)&&(u.height=h=14),b&&(u.width=Math.abs(h*Math.sin(D))+Math.abs(a*Math.cos(D)),u.height=Math.abs(h*Math.cos(D))+Math.abs(a*Math.sin(D))));if(F&&0<u.height){for(;250<f.length;)delete E[f.shift()];E[F]||f.push(F);E[F]=u}}return u},show:function(a){return this.attr({visibility:a?"inherit":"visible"})},hide:function(){return this.attr({visibility:"hidden"})},
fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.attr({y:-9999})}})},add:function(a){var b=this.renderer,m=this.element,c;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);this.added=!0;if(!a||a.handleZ||this.zIndex)c=this.zIndexSetter();c||(a?a.element:b.box).appendChild(m);if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=
this,m=a.element||{},c=a.renderer.isSVG&&"SPAN"===m.nodeName&&a.parentGroup,u=m.ownerSVGElement,h=a.clipPath;m.onclick=m.onmouseout=m.onmouseover=m.onmousemove=m.point=null;F(a);h&&u&&(q(u.querySelectorAll("[clip-path],[CLIP-PATH]"),function(a){var b=a.getAttribute("clip-path"),m=h.element.id;(-1<b.indexOf("(#"+m+")")||-1<b.indexOf('("#'+m+'")'))&&a.removeAttribute("clip-path")}),a.clipPath=h.destroy());if(a.stops){for(u=0;u<a.stops.length;u++)a.stops[u]=a.stops[u].destroy();a.stops=null}for(a.safeRemoveChild(m);c&&
c.div&&0===c.div.childNodes.length;)m=c.parentGroup,a.safeRemoveChild(c.div),delete c.div,c=m;a.alignTo&&b(a.renderer.alignedObjects,a);K(a,function(b,m){delete a[m]});return null},xGetter:function(a){"circle"===this.element.nodeName&&("x"===a?a="cx":"y"===a&&(a="cy"));return this._defaultGetter(a)},_defaultGetter:function(a){a=m(this[a+"Value"],this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,b,m){a&&a.join&&(a=a.join(" "));
/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");this[b]!==a&&(m.setAttribute(b,a),this[b]=a)},alignSetter:function(a){this.alignValue=a;this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,m){this[b]=a;m.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=t.createElementNS(this.SVG_NS,"title"),this.element.appendChild(b));b.firstChild&&b.removeChild(b.firstChild);b.appendChild(t.createTextNode(String(m(a),
"").replace(/<[^>]*>/g,"").replace(/&lt;/g,"\x3c").replace(/&gt;/g,"\x3e")))},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,m){"string"===typeof a?m.setAttribute(b,a):a&&this.complexColor(a,b,m)},visibilitySetter:function(a,b,m){"inherit"===a?m.removeAttribute(b):this[b]!==a&&m.setAttribute(b,a);this[b]=a},zIndexSetter:function(a,b){var m=this.renderer,c=this.parentGroup,u=(c||m).element||m.box,h,d=this.element,
n,k,m=u===m.box;h=this.added;var x;e(a)?(d.setAttribute("data-z-index",a),a=+a,this[b]===a&&(h=!1)):e(this[b])&&d.removeAttribute("data-z-index");this[b]=a;if(h){(a=this.zIndex)&&c&&(c.handleZ=!0);b=u.childNodes;for(x=b.length-1;0<=x&&!n;x--)if(c=b[x],h=c.getAttribute("data-z-index"),k=!e(h),c!==d)if(0>a&&k&&!m&&!x)u.insertBefore(d,b[x]),n=!0;else if(D(h)<=a||k&&(!e(a)||0<=a))u.insertBefore(d,b[x+1]||null),n=!0;n||(u.insertBefore(d,b[m?3:0]||null),n=!0)}return n},_defaultSetter:function(a,b,m){m.setAttribute(b,
a)}});y.prototype.yGetter=y.prototype.xGetter;y.prototype.translateXSetter=y.prototype.translateYSetter=y.prototype.rotationSetter=y.prototype.verticalAlignSetter=y.prototype.rotationOriginXSetter=y.prototype.rotationOriginYSetter=y.prototype.scaleXSetter=y.prototype.scaleYSetter=y.prototype.matrixSetter=function(a,b){this[b]=a;this.doTransform=!0};z=a.SVGRenderer=function(){this.init.apply(this,arguments)};c(z.prototype,{Element:y,SVG_NS:Q,init:function(a,b,m,c,u,h){var D;c=this.createElement("svg").attr({version:"1.1",
"class":"highcharts-root"});D=c.element;a.appendChild(D);f(a,"dir","ltr");-1===a.innerHTML.indexOf("xmlns")&&f(D,"xmlns",this.SVG_NS);this.isSVG=!0;this.box=D;this.boxWrapper=c;this.alignedObjects=[];this.url=(A||C)&&t.getElementsByTagName("base").length?P.location.href.replace(/#.*?$/,"").replace(/<[^>]*>/g,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(t.createTextNode("Created with Highmaps 6.1.0-modified"));this.defs=this.createElement("defs").add();
this.allowHTML=h;this.forExport=u;this.gradients={};this.cache={};this.cacheKeys=[];this.imgCount=0;this.setSize(b,m,!1);var e;A&&a.getBoundingClientRect&&(b=function(){w(a,{left:0,top:0});e=a.getBoundingClientRect();w(a,{left:Math.ceil(e.left)-e.left+"px",top:Math.ceil(e.top)-e.top+"px"})},b(),this.unSubPixelFix=B(P,"resize",b))},definition:function(a){function b(a,c){var h;q(u(a),function(a){var u=m.createElement(a.tagName),D={};K(a,function(a,b){"tagName"!==b&&"children"!==b&&"textContent"!==b&&
(D[b]=a)});u.attr(D);u.add(c||m.defs);a.textContent&&u.element.appendChild(t.createTextNode(a.textContent));b(a.children||[],u);h=u});return h}var m=this;return b(a)},isHidden:function(){return!this.boxWrapper.getBBox().width},destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();k(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.unSubPixelFix&&this.unSubPixelFix();return this.alignedObjects=null},createElement:function(a){var b=new this.Element;
b.init(this,a);return b},draw:M,getRadialAttr:function(a,b){return{cx:a[0]-a[2]/2+b.cx*a[2],cy:a[1]-a[2]/2+b.cy*a[2],r:b.r*a[2]}},getSpanWidth:function(a){return a.getBBox(!0).width},applyEllipsis:function(a,b,m,c){var u=a.rotation,h=m,D,e=0,d=m.length,n=function(a){b.removeChild(b.firstChild);a&&b.appendChild(t.createTextNode(a))},k;a.rotation=0;h=this.getSpanWidth(a,b);if(k=h>c){for(;e<=d;)D=Math.ceil((e+d)/2),h=m.substring(0,D)+"\u2026",n(h),h=this.getSpanWidth(a,b),e===d?e=d+1:h>c?d=D-1:e=D;0===
d&&n("")}a.rotation=u;return k},escapes:{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;","'":"\x26#39;",'"':"\x26quot;"},buildText:function(a){var b=a.element,c=this,u=c.forExport,e=m(a.textStr,"").toString(),d=-1!==e.indexOf("\x3c"),n=b.childNodes,k,x=f(b,"x"),g=a.styles,E=a.textWidth,F=g&&g.lineHeight,C=g&&g.textOutline,N=g&&"ellipsis"===g.textOverflow,v=g&&"nowrap"===g.whiteSpace,A,p=n.length,G=E&&!a.added&&this.box,l=function(a){return F?D(F):c.fontMetrics(void 0,a.getAttribute("style")?a:
b).h},M=function(a,b){K(c.escapes,function(m,c){b&&-1!==J(m,b)||(a=a.toString().replace(new RegExp(m,"g"),c))});return a},L=function(a,b){var m;m=a.indexOf("\x3c");a=a.substring(m,a.indexOf("\x3e")-m);m=a.indexOf(b+"\x3d");if(-1!==m&&(m=m+b.length+1,b=a.charAt(m),'"'===b||"'"===b))return a=a.substring(m+1),a.substring(0,a.indexOf(b))},g=[e,N,v,F,C,g&&g.fontSize,E].join();if(g!==a.textCache){for(a.textCache=g;p--;)b.removeChild(n[p]);d||C||N||E||-1!==e.indexOf(" ")?(G&&G.appendChild(b),e=d?e.replace(/<(b|strong)>/g,
'\x3cspan class\x3d"highcharts-strong"\x3e').replace(/<(i|em)>/g,'\x3cspan class\x3d"highcharts-emphasized"\x3e').replace(/<a/g,"\x3cspan").replace(/<\/(b|strong|i|em|a)>/g,"\x3c/span\x3e").split(/<br.*?>/g):[e],e=h(e,function(a){return""!==a}),q(e,function(m,h){var D,e=0;m=m.replace(/^\s+|\s+$/g,"").replace(/<span/g,"|||\x3cspan").replace(/<\/span>/g,"\x3c/span\x3e|||");D=m.split("|||");q(D,function(m){if(""!==m||1===D.length){var d={},n=t.createElementNS(c.SVG_NS,"tspan"),g,F;(g=L(m,"class"))&&
f(n,"class",g);if(g=L(m,"style"))g=g.replace(/(;| |^)color([ :])/,"$1fill$2"),f(n,"style",g);(F=L(m,"href"))&&!u&&(f(n,"onclick",'location.href\x3d"'+F+'"'),f(n,"class","highcharts-anchor"));m=M(m.replace(/<[a-zA-Z\/](.|\n)*?>/g,"")||" ");if(" "!==m){n.appendChild(t.createTextNode(m));e?d.dx=0:h&&null!==x&&(d.x=x);f(n,d);b.appendChild(n);!e&&A&&(!S&&u&&w(n,{display:"block"}),f(n,"dy",l(n)));if(E){d=m.replace(/([^\^])-/g,"$1- ").split(" ");F=1<D.length||h||1<d.length&&!v;var C=[],q,p=l(n),G=a.rotation;
for(N&&(k=c.applyEllipsis(a,n,m,E));!N&&F&&(d.length||C.length);)a.rotation=0,q=c.getSpanWidth(a,n),m=q>E,void 0===k&&(k=m),m&&1!==d.length?(n.removeChild(n.firstChild),C.unshift(d.pop())):(d=C,C=[],d.length&&!v&&(n=t.createElementNS(Q,"tspan"),f(n,{dy:p,x:x}),g&&f(n,"style",g),b.appendChild(n)),q>E&&(E=q+1)),d.length&&n.appendChild(t.createTextNode(d.join(" ").replace(/- /g,"-")));a.rotation=G}e++}}});A=A||b.childNodes.length}),N&&k&&a.attr("title",M(a.textStr,["\x26lt;","\x26gt;"])),G&&G.removeChild(b),
C&&a.applyTextOutline&&a.applyTextOutline(C)):b.appendChild(t.createTextNode(M(e)))}},getContrast:function(a){a=r(a).rgba;return 510<a[0]+a[1]+a[2]?"#000000":"#FFFFFF"},button:function(a,b,m,c,u,h,D,e,d){var n=this.label(a,b,m,d,null,null,null,null,"button"),k=0;n.attr(E({padding:8,r:2},u));B(n.element,G?"mouseover":"mouseenter",function(){3!==k&&n.setState(1)});B(n.element,G?"mouseout":"mouseleave",function(){3!==k&&n.setState(k)});n.setState=function(a){1!==a&&(n.state=k=a);n.removeClass(/highcharts-button-(normal|hover|pressed|disabled)/).addClass("highcharts-button-"+
["normal","hover","pressed","disabled"][a||0])};return n.on("click",function(a){3!==k&&c.call(n,a)})},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=Math.round(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=Math.round(a[2])+b%2/2);return a},path:function(a){var b={};H(a)?b.d=a:v(a)&&c(b,a);return this.createElement("path").attr(b)},circle:function(a,b,m){a=v(a)?a:{x:a,y:b,r:m};b=this.createElement("circle");b.xSetter=b.ySetter=function(a,b,m){m.setAttribute("c"+b,a)};return b.attr(a)},arc:function(a,b,m,c,
u,h){v(a)?(c=a,b=c.y,m=c.r,a=c.x):c={innerR:c,start:u,end:h};a=this.symbol("arc",a,b,m,m,c);a.r=m;return a},rect:function(a,b,m,c,u,h){u=v(a)?a.r:u;h=this.createElement("rect");a=v(a)?a:void 0===a?{}:{x:a,y:b,width:Math.max(m,0),height:Math.max(c,0)};u&&(a.r=u);h.rSetter=function(a,b,m){f(m,{rx:a,ry:a})};return h.attr(a)},setSize:function(a,b,c){var u=this.alignedObjects,h=u.length;this.width=a;this.height=b;for(this.boxWrapper.animate({width:a,height:b},{step:function(){this.attr({viewBox:"0 0 "+
this.attr("width")+" "+this.attr("height")})},duration:m(c,!0)?void 0:0});h--;)u[h].align()},g:function(a){var b=this.createElement("g");return a?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,m,u,h,D){var e={preserveAspectRatio:"none"},d,n=function(a,b){a.setAttributeNS?a.setAttributeNS("http://www.w3.org/1999/xlink","href",b):a.setAttribute("hc-svg-href",b)},k=function(b){n(d.element,a);D.call(d,b)};1<arguments.length&&c(e,{x:b,y:m,width:u,height:h});d=this.createElement("image").attr(e);
D?(n(d.element,"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d"),e=new P.Image,B(e,"load",k),e.src=a,e.complete&&k({})):n(d.element,a);return d},symbol:function(a,b,u,h,D,d){var n=this,k,x=/^url\((.*?)\)$/,E=x.test(a),F=!E&&(this.symbols[a]?a:"circle"),f=F&&this.symbols[F],C=e(b)&&f&&f.call(this.symbols,Math.round(b),Math.round(u),h,D,d),N,v;f?(k=this.path(C),c(k,{symbolName:F,x:b,y:u,width:h,height:D}),d&&c(k,d)):E&&(N=a.match(x)[1],k=this.image(N),k.imgwidth=m(O[N]&&
O[N].width,d&&d.width),k.imgheight=m(O[N]&&O[N].height,d&&d.height),v=function(){k.attr({width:k.width,height:k.height})},q(["width","height"],function(a){k[a+"Setter"]=function(a,b){var m={},c=this["img"+b],u="width"===b?"translateX":"translateY";this[b]=a;e(c)&&(this.element&&this.element.setAttribute(b,c),this.alignByTranslate||(m[u]=((this[b]||0)-c)/2,this.attr(m)))}}),e(b)&&k.attr({x:b,y:u}),k.isImg=!0,e(k.imgwidth)&&e(k.imgheight)?v():(k.attr({width:0,height:0}),p("img",{onload:function(){var a=
g[n.chartIndex];0===this.width&&(w(this,{position:"absolute",top:"-999em"}),t.body.appendChild(this));O[N]={width:this.width,height:this.height};k.imgwidth=this.width;k.imgheight=this.height;k.element&&v();this.parentNode&&this.parentNode.removeChild(this);n.imgCount--;if(!n.imgCount&&a&&a.onload)a.onload()},src:N}),this.imgCount++));return k},symbols:{circle:function(a,b,m,c){return this.arc(a+m/2,b+c/2,m/2,c/2,{start:0,end:2*Math.PI,open:!1})},square:function(a,b,m,c){return["M",a,b,"L",a+m,b,a+
m,b+c,a,b+c,"Z"]},triangle:function(a,b,m,c){return["M",a+m/2,b,"L",a+m,b+c,a,b+c,"Z"]},"triangle-down":function(a,b,m,c){return["M",a,b,"L",a+m,b,a+m/2,b+c,"Z"]},diamond:function(a,b,m,c){return["M",a+m/2,b,"L",a+m,b+c/2,a+m/2,b+c,a,b+c/2,"Z"]},arc:function(a,b,c,u,h){var D=h.start,d=h.r||c,n=h.r||u||c,k=h.end-.001;c=h.innerR;u=m(h.open,.001>Math.abs(h.end-h.start-2*Math.PI));var x=Math.cos(D),g=Math.sin(D),E=Math.cos(k),k=Math.sin(k);h=.001>h.end-D-Math.PI?0:1;d=["M",a+d*x,b+n*g,"A",d,n,0,h,1,a+
d*E,b+n*k];e(c)&&d.push(u?"M":"L",a+c*E,b+c*k,"A",c,c,0,h,0,a+c*x,b+c*g);d.push(u?"":"Z");return d},callout:function(a,b,m,c,u){var h=Math.min(u&&u.r||0,m,c),D=h+6,d=u&&u.anchorX;u=u&&u.anchorY;var e;e=["M",a+h,b,"L",a+m-h,b,"C",a+m,b,a+m,b,a+m,b+h,"L",a+m,b+c-h,"C",a+m,b+c,a+m,b+c,a+m-h,b+c,"L",a+h,b+c,"C",a,b+c,a,b+c,a,b+c-h,"L",a,b+h,"C",a,b,a,b,a+h,b];d&&d>m?u>b+D&&u<b+c-D?e.splice(13,3,"L",a+m,u-6,a+m+6,u,a+m,u+6,a+m,b+c-h):e.splice(13,3,"L",a+m,c/2,d,u,a+m,c/2,a+m,b+c-h):d&&0>d?u>b+D&&u<b+c-
D?e.splice(33,3,"L",a,u+6,a-6,u,a,u-6,a,b+h):e.splice(33,3,"L",a,c/2,d,u,a,c/2,a,b+h):u&&u>c&&d>a+D&&d<a+m-D?e.splice(23,3,"L",d+6,b+c,d,b+c+6,d-6,b+c,a+h,b+c):u&&0>u&&d>a+D&&d<a+m-D&&e.splice(3,3,"L",d-6,b,d,b-6,d+6,b,m-h,b);return e}},clipRect:function(b,m,c,u){var h=a.uniqueKey(),d=this.createElement("clipPath").attr({id:h}).add(this.defs);b=this.rect(b,m,c,u,0).add(d);b.id=h;b.clipPath=d;b.count=0;return b},text:function(a,b,m,c){var u={};if(c&&(this.allowHTML||!this.forExport))return this.html(a,
b,m);u.x=Math.round(b||0);m&&(u.y=Math.round(m));if(a||0===a)u.text=a;a=this.createElement("text").attr(u);c||(a.xSetter=function(a,b,m){var c=m.getElementsByTagName("tspan"),u,h=m.getAttribute(b),d;for(d=0;d<c.length;d++)u=c[d],u.getAttribute(b)===h&&u.setAttribute(b,a);m.setAttribute(b,a)});return a},fontMetrics:function(a,b){a=b&&y.prototype.getStyle.call(b,"font-size");a=/px/.test(a)?D(a):/em/.test(a)?parseFloat(a)*(b?this.fontMetrics(null,b.parentNode).f:16):12;b=24>a?a+3:Math.round(1.2*a);return{h:b,
b:Math.round(.8*b),f:a}},rotCorr:function(a,b,m){var c=a;b&&m&&(c=Math.max(c*Math.cos(b*d),4));return{x:-a/3*Math.sin(b*d),y:c}},label:function(b,m,u,h,d,D,n,k,x){var g=this,F=g.g("button"!==x&&"label"),f=F.text=g.text("",0,0,n).attr({zIndex:1}),C,v,A=0,t=3,p=0,G,l,M,J,S,Q={},K,H=/^url\((.*?)\)$/.test(h),w=H,r,O,P,L;x&&F.addClass("highcharts-"+x);w=!0;r=function(){return C.strokeWidth()%2/2};O=function(){var a=f.element.style,b={};v=(void 0===G||void 0===l||S)&&e(f.textStr)&&f.getBBox();F.width=(G||
v.width||0)+2*t+p;F.height=(l||v.height||0)+2*t;K=t+g.fontMetrics(a&&a.fontSize,f).b;w&&(C||(F.box=C=g.symbols[h]||H?g.symbol(h):g.rect(),C.addClass(("button"===x?"":"highcharts-label-box")+(x?" highcharts-"+x+"-box":"")),C.add(F),a=r(),b.x=a,b.y=(k?-K:0)+a),b.width=Math.round(F.width),b.height=Math.round(F.height),C.attr(c(b,Q)),Q={})};P=function(){var a=p+t,b;b=k?0:K;e(G)&&v&&("center"===S||"right"===S)&&(a+={center:.5,right:1}[S]*(G-v.width));if(a!==f.x||b!==f.y)f.attr("x",a),f.hasBoxWidthChanged&&
(v=f.getBBox(!0),O()),void 0!==b&&f.attr("y",b);f.x=a;f.y=b};L=function(a,b){C?C.attr(a,b):Q[a]=b};F.onAdd=function(){f.add(F);F.attr({text:b||0===b?b:"",x:m,y:u});C&&e(d)&&F.attr({anchorX:d,anchorY:D})};F.widthSetter=function(b){G=a.isNumber(b)?b:null};F.heightSetter=function(a){l=a};F["text-alignSetter"]=function(a){S=a};F.paddingSetter=function(a){e(a)&&a!==t&&(t=F.padding=a,P())};F.paddingLeftSetter=function(a){e(a)&&a!==p&&(p=a,P())};F.alignSetter=function(a){a={left:0,center:.5,right:1}[a];
a!==A&&(A=a,v&&F.attr({x:M}))};F.textSetter=function(a){void 0!==a&&f.textSetter(a);O();P()};F["stroke-widthSetter"]=function(a,b){a&&(w=!0);this["stroke-width"]=a;L(b,a)};F.rSetter=function(a,b){L(b,a)};F.anchorXSetter=function(a,b){d=F.anchorX=a;L(b,Math.round(a)-r()-M)};F.anchorYSetter=function(a,b){D=F.anchorY=a;L(b,a-J)};F.xSetter=function(a){F.x=a;A&&(a-=A*((G||v.width)+2*t),F["forceAnimate:x"]=!0);M=Math.round(a);F.attr("translateX",M)};F.ySetter=function(a){J=F.y=Math.round(a);F.attr("translateY",
J)};var z=F.css;return c(F,{css:function(a){if(a){var b={};a=E(a);q(F.textProps,function(m){void 0!==a[m]&&(b[m]=a[m],delete a[m])});f.css(b);"width"in b&&O()}return z.call(F,a)},getBBox:function(){return{width:v.width+2*t,height:v.height+2*t,x:v.x-t,y:v.y-t}},destroy:function(){N(F.element,"mouseenter");N(F.element,"mouseleave");f&&(f=f.destroy());C&&(C=C.destroy());y.prototype.destroy.call(F);F=g=O=P=L=null}})}});a.Renderer=z})(I);(function(a){var y=a.attr,z=a.createElement,B=a.css,l=a.defined,
f=a.each,g=a.extend,r=a.isFirefox,w=a.isMS,p=a.isWebKit,e=a.pick,d=a.pInt,k=a.SVGRenderer,t=a.win,q=a.wrap;g(a.SVGElement.prototype,{htmlCss:function(a){var b=this.element;if(b=a&&"SPAN"===b.tagName&&a.width)delete a.width,this.textWidth=b,this.htmlUpdateTransform();a&&"ellipsis"===a.textOverflow&&(a.whiteSpace="nowrap",a.overflow="hidden");this.styles=g(this.styles,a);B(this.element,a);return this},htmlGetBBox:function(){var a=this.element;return{x:a.offsetLeft,y:a.offsetTop,width:a.offsetWidth,
height:a.offsetHeight}},htmlUpdateTransform:function(){if(this.added){var a=this.renderer,b=this.element,h=this.x||0,e=this.y||0,k=this.textAlign||"left",g={left:0,center:.5,right:1}[k],q=this.styles,t=q&&q.whiteSpace;B(b,{marginLeft:this.translateX||0,marginTop:this.translateY||0});this.inverted&&f(b.childNodes,function(c){a.invertChild(c,b)});if("SPAN"===b.tagName){var q=this.rotation,v=this.textWidth&&d(this.textWidth),x=[q,k,b.innerHTML,this.textWidth,this.textAlign].join(),C;(C=v!==this.oldTextWidth)&&
!(C=v>this.oldTextWidth)&&((C=this.textPxLength)||(B(b,{width:"",whiteSpace:t||"nowrap"}),C=b.offsetWidth),C=C>v);C&&/[ \-]/.test(b.textContent||b.innerText)?(B(b,{width:v+"px",display:"block",whiteSpace:t||"normal"}),this.oldTextWidth=v,this.hasBoxWidthChanged=!0):this.hasBoxWidthChanged=!1;x!==this.cTT&&(t=a.fontMetrics(b.style.fontSize).b,l(q)&&q!==(this.oldRotation||0)&&this.setSpanRotation(q,g,t),this.getSpanCorrection(!l(q)&&this.textPxLength||b.offsetWidth,t,g,q,k));B(b,{left:h+(this.xCorr||
0)+"px",top:e+(this.yCorr||0)+"px"});this.cTT=x;this.oldRotation=q}}else this.alignOnAdd=!0},setSpanRotation:function(a,b,h){var c={},d=this.renderer.getTransformKey();c[d]=c.transform="rotate("+a+"deg)";c[d+(r?"Origin":"-origin")]=c.transformOrigin=100*b+"% "+h+"px";B(this.element,c)},getSpanCorrection:function(a,b,h){this.xCorr=-a*h;this.yCorr=-b}});g(k.prototype,{getTransformKey:function(){return w&&!/Edge/.test(t.navigator.userAgent)?"-ms-transform":p?"-webkit-transform":r?"MozTransform":t.opera?
"-o-transform":""},html:function(a,b,h){var c=this.createElement("span"),d=c.element,k=c.renderer,A=k.isSVG,t=function(a,b){f(["opacity","visibility"],function(c){q(a,c+"Setter",function(a,c,h,m){a.call(this,c,h,m);b[h]=c})});a.addedSetters=!0};c.textSetter=function(a){a!==d.innerHTML&&delete this.bBox;this.textStr=a;d.innerHTML=e(a,"");c.doTransform=!0};A&&t(c,c.element.style);c.xSetter=c.ySetter=c.alignSetter=c.rotationSetter=function(a,b){"align"===b&&(b="textAlign");c[b]=a;c.doTransform=!0};c.afterSetters=
function(){this.doTransform&&(this.htmlUpdateTransform(),this.doTransform=!1)};c.attr({text:a,x:Math.round(b),y:Math.round(h)}).css({position:"absolute"});d.style.whiteSpace="nowrap";c.css=c.htmlCss;A&&(c.add=function(a){var b,h=k.box.parentNode,e=[];if(this.parentGroup=a){if(b=a.div,!b){for(;a;)e.push(a),a=a.parentGroup;f(e.reverse(),function(a){function d(b,c){a[c]=b;"translateX"===c?m.left=b+"px":m.top=b+"px";a.doTransform=!0}var m,D=y(a.element,"class");D&&(D={className:D});b=a.div=a.div||z("div",
D,{position:"absolute",left:(a.translateX||0)+"px",top:(a.translateY||0)+"px",display:a.display,opacity:a.opacity,pointerEvents:a.styles&&a.styles.pointerEvents},b||h);m=b.style;g(a,{classSetter:function(a){return function(b){this.element.setAttribute("class",b);a.className=b}}(b),on:function(){e[0].div&&c.on.apply({element:e[0].div},arguments);return a},translateXSetter:d,translateYSetter:d});a.addedSetters||t(a,m)})}}else b=h;b.appendChild(d);c.added=!0;c.alignOnAdd&&c.htmlUpdateTransform();return c});
return c}})})(I);(function(a){var y=a.correctFloat,z=a.defined,B=a.destroyObjectProperties,l=a.fireEvent,f=a.isNumber,g=a.pick,r=a.deg2rad;a.Tick=function(a,g,e,d){this.axis=a;this.pos=g;this.type=e||"";this.isNewLabel=this.isNew=!0;e||d||this.addLabel()};a.Tick.prototype={addLabel:function(){var a=this.axis,f=a.options,e=a.chart,d=a.categories,k=a.names,t=this.pos,q=f.labels,c=a.tickPositions,b=t===c[0],h=t===c[c.length-1],k=d?g(d[t],k[t],t):t,d=this.label,c=c.info,n;a.isDatetimeAxis&&c&&(n=f.dateTimeLabelFormats[c.higherRanks[t]||
c.unitName]);this.isFirst=b;this.isLast=h;f=a.labelFormatter.call({axis:a,chart:e,isFirst:b,isLast:h,dateTimeLabelFormat:n,value:a.isLog?y(a.lin2log(k)):k,pos:t});if(z(d))d&&d.attr({text:f});else{if(this.label=d=z(f)&&q.enabled?e.renderer.text(f,0,0,q.useHTML).add(a.labelGroup):null)d.textPxLength=d.getBBox().width;this.rotation=0}},getLabelSize:function(){return this.label?this.label.getBBox()[this.axis.horiz?"height":"width"]:0},handleOverflow:function(a){var f=this.axis,e=f.options.labels,d=a.x,
k=f.chart.chartWidth,t=f.chart.spacing,q=g(f.labelLeft,Math.min(f.pos,t[3])),t=g(f.labelRight,Math.max(f.isRadial?0:f.pos+f.len,k-t[1])),c=this.label,b=this.rotation,h={left:0,center:.5,right:1}[f.labelAlign||c.attr("align")],n=c.getBBox().width,l=f.getSlotWidth(this),H=l,A=1,G,v={};if(b||!1===e.overflow)0>b&&d-h*n<q?G=Math.round(d/Math.cos(b*r)-q):0<b&&d+h*n>t&&(G=Math.round((k-d)/Math.cos(b*r)));else if(k=d+(1-h)*n,d-h*n<q?H=a.x+H*(1-h)-q:k>t&&(H=t-a.x+H*h,A=-1),H=Math.min(l,H),H<l&&"center"===
f.labelAlign&&(a.x+=A*(l-H-h*(l-Math.min(n,H)))),n>H||f.autoRotation&&(c.styles||{}).width)G=H;G&&(v.width=G,(e.style||{}).textOverflow||(v.textOverflow="ellipsis"),c.css(v))},getPosition:function(g,f,e,d){var k=this.axis,t=k.chart,q=d&&t.oldChartHeight||t.chartHeight;g={x:g?a.correctFloat(k.translate(f+e,null,null,d)+k.transB):k.left+k.offset+(k.opposite?(d&&t.oldChartWidth||t.chartWidth)-k.right-k.left:0),y:g?q-k.bottom+k.offset-(k.opposite?k.height:0):a.correctFloat(q-k.translate(f+e,null,null,
d)-k.transB)};l(this,"afterGetPosition",{pos:g});return g},getLabelPosition:function(a,g,e,d,k,f,q,c){var b=this.axis,h=b.transA,n=b.reversed,t=b.staggerLines,p=b.tickRotCorr||{x:0,y:0},A=k.y,G=d||b.reserveSpaceDefault?0:-b.labelOffset*("center"===b.labelAlign?.5:1),v={};z(A)||(A=0===b.side?e.rotation?-8:-e.getBBox().height:2===b.side?p.y+8:Math.cos(e.rotation*r)*(p.y-e.getBBox(!1,0).height/2));a=a+k.x+G+p.x-(f&&d?f*h*(n?-1:1):0);g=g+A-(f&&!d?f*h*(n?1:-1):0);t&&(e=q/(c||1)%t,b.opposite&&(e=t-e-1),
g+=b.labelOffset/t*e);v.x=a;v.y=Math.round(g);l(this,"afterGetLabelPosition",{pos:v});return v},getMarkPath:function(a,g,e,d,k,f){return f.crispLine(["M",a,g,"L",a+(k?0:-e),g+(k?e:0)],d)},renderGridLine:function(a,g,e){var d=this.axis,k=this.gridLine,f={},q=this.pos,c=this.type,b=d.tickmarkOffset,h=d.chart.renderer;k||(c||(f.zIndex=1),a&&(f.opacity=0),this.gridLine=k=h.path().attr(f).addClass("highcharts-"+(c?c+"-":"")+"grid-line").add(d.gridGroup));if(!a&&k&&(a=d.getPlotLinePath(q+b,k.strokeWidth()*
e,a,!0)))k[this.isNew?"attr":"animate"]({d:a,opacity:g})},renderMark:function(a,g,e){var d=this.axis,k=d.chart.renderer,f=this.type,q=d.tickSize(f?f+"Tick":"tick"),c=this.mark,b=!c,h=a.x;a=a.y;q&&(d.opposite&&(q[0]=-q[0]),b&&(this.mark=c=k.path().addClass("highcharts-"+(f?f+"-":"")+"tick").add(d.axisGroup)),c[b?"attr":"animate"]({d:this.getMarkPath(h,a,q[0],c.strokeWidth()*e,d.horiz,k),opacity:g}))},renderLabel:function(a,l,e,d){var k=this.axis,t=k.horiz,q=k.options,c=this.label,b=q.labels,h=b.step,
k=k.tickmarkOffset,n=!0,p=a.x;a=a.y;c&&f(p)&&(c.xy=a=this.getLabelPosition(p,a,c,t,b,k,d,h),this.isFirst&&!this.isLast&&!g(q.showFirstLabel,1)||this.isLast&&!this.isFirst&&!g(q.showLastLabel,1)?n=!1:!t||b.step||b.rotation||l||0===e||this.handleOverflow(a),h&&d%h&&(n=!1),n&&f(a.y)?(a.opacity=e,c[this.isNewLabel?"attr":"animate"](a),this.isNewLabel=!1):(c.attr("y",-9999),this.isNewLabel=!0))},render:function(f,l,e){var d=this.axis,k=d.horiz,t=this.getPosition(k,this.pos,d.tickmarkOffset,l),q=t.x,c=
t.y,d=k&&q===d.pos+d.len||!k&&c===d.pos?-1:1;e=g(e,1);this.isActive=!0;this.renderGridLine(l,e,d);this.renderMark(t,e,d);this.renderLabel(t,l,e,f);this.isNew=!1;a.fireEvent(this,"afterRender")},destroy:function(){B(this,this.axis)}}})(I);var W=function(a){var y=a.addEvent,z=a.animObject,B=a.arrayMax,l=a.arrayMin,f=a.correctFloat,g=a.defaultOptions,r=a.defined,w=a.deg2rad,p=a.destroyObjectProperties,e=a.each,d=a.extend,k=a.fireEvent,t=a.format,q=a.getMagnitude,c=a.grep,b=a.inArray,h=a.isArray,n=a.isNumber,
J=a.isString,H=a.merge,A=a.normalizeTickInterval,G=a.objectEach,v=a.pick,x=a.removeEvent,C=a.splat,E=a.syncTimeout,M=a.Tick,K=function(){this.init.apply(this,arguments)};a.extend(K.prototype,{defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,labels:{enabled:!0,x:0},maxPadding:.01,minorTickLength:2,minorTickPosition:"outside",minPadding:.01,startOfWeek:1,startOnTick:!1,tickLength:10,
tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",title:{align:"middle"},type:"linear"},defaultYAxisOptions:{endOnTick:!0,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8},maxPadding:.05,minPadding:.05,startOnTick:!0,title:{rotation:270,text:"Values"},stackLabels:{allowOverlap:!1,enabled:!1,formatter:function(){return a.numberFormat(this.total,-1)}}},defaultLeftAxisOptions:{labels:{x:-15},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15},title:{rotation:90}},defaultBottomAxisOptions:{labels:{autoRotation:[-45],
x:0},title:{rotation:0}},defaultTopAxisOptions:{labels:{autoRotation:[-45],x:0},title:{rotation:0}},init:function(a,c){var m=c.isX,u=this;u.chart=a;u.horiz=a.inverted&&!u.isZAxis?!m:m;u.isXAxis=m;u.coll=u.coll||(m?"xAxis":"yAxis");k(this,"init",{userOptions:c});u.opposite=c.opposite;u.side=c.side||(u.horiz?u.opposite?0:2:u.opposite?1:3);u.setOptions(c);var h=this.options,d=h.type;u.labelFormatter=h.labels.formatter||u.defaultLabelFormatter;u.userOptions=c;u.minPixelPadding=0;u.reversed=h.reversed;
u.visible=!1!==h.visible;u.zoomEnabled=!1!==h.zoomEnabled;u.hasNames="category"===d||!0===h.categories;u.categories=h.categories||u.hasNames;u.names||(u.names=[],u.names.keys={});u.plotLinesAndBandsGroups={};u.isLog="logarithmic"===d;u.isDatetimeAxis="datetime"===d;u.positiveValuesOnly=u.isLog&&!u.allowNegativeLog;u.isLinked=r(h.linkedTo);u.ticks={};u.labelEdge=[];u.minorTicks={};u.plotLinesAndBands=[];u.alternateBands={};u.len=0;u.minRange=u.userMinRange=h.minRange||h.maxZoom;u.range=h.range;u.offset=
h.offset||0;u.stacks={};u.oldStacks={};u.stacksTouched=0;u.max=null;u.min=null;u.crosshair=v(h.crosshair,C(a.options.tooltip.crosshairs)[m?0:1],!1);c=u.options.events;-1===b(u,a.axes)&&(m?a.axes.splice(a.xAxis.length,0,u):a.axes.push(u),a[u.coll].push(u));u.series=u.series||[];a.inverted&&!u.isZAxis&&m&&void 0===u.reversed&&(u.reversed=!0);G(c,function(a,b){y(u,b,a)});u.lin2log=h.linearToLogConverter||u.lin2log;u.isLog&&(u.val2lin=u.log2lin,u.lin2val=u.lin2log);k(this,"afterInit")},setOptions:function(a){this.options=
H(this.defaultOptions,"yAxis"===this.coll&&this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],H(g[this.coll],a));k(this,"afterSetOptions",{userOptions:a})},defaultLabelFormatter:function(){var b=this.axis,c=this.value,h=b.chart.time,u=b.categories,d=this.dateTimeLabelFormat,e=g.lang,k=e.numericSymbols,e=e.numericSymbolMagnitude||1E3,n=k&&k.length,x,f=b.options.labels.format,b=b.isLog?Math.abs(c):b.tickInterval;
if(f)x=t(f,this,h);else if(u)x=c;else if(d)x=h.dateFormat(d,c);else if(n&&1E3<=b)for(;n--&&void 0===x;)h=Math.pow(e,n+1),b>=h&&0===10*c%h&&null!==k[n]&&0!==c&&(x=a.numberFormat(c/h,-1)+k[n]);void 0===x&&(x=1E4<=Math.abs(c)?a.numberFormat(c,-1):a.numberFormat(c,-1,void 0,""));return x},getSeriesExtremes:function(){var a=this,b=a.chart;k(this,"getSeriesExtremes",null,function(){a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.threshold=null;a.softThreshold=!a.isXAxis;a.buildStacks&&a.buildStacks();e(a.series,
function(m){if(m.visible||!b.options.chart.ignoreHiddenSeries){var u=m.options,h=u.threshold,d;a.hasVisibleSeries=!0;a.positiveValuesOnly&&0>=h&&(h=null);if(a.isXAxis)u=m.xData,u.length&&(m=l(u),d=B(u),n(m)||m instanceof Date||(u=c(u,n),m=l(u),d=B(u)),u.length&&(a.dataMin=Math.min(v(a.dataMin,u[0],m),m),a.dataMax=Math.max(v(a.dataMax,u[0],d),d)));else if(m.getExtremes(),d=m.dataMax,m=m.dataMin,r(m)&&r(d)&&(a.dataMin=Math.min(v(a.dataMin,m),m),a.dataMax=Math.max(v(a.dataMax,d),d)),r(h)&&(a.threshold=
h),!u.softThreshold||a.positiveValuesOnly)a.softThreshold=!1}})});k(this,"afterGetSeriesExtremes")},translate:function(a,b,c,u,h,d){var m=this.linkedParent||this,e=1,D=0,k=u?m.oldTransA:m.transA;u=u?m.oldMin:m.min;var x=m.minPixelPadding;h=(m.isOrdinal||m.isBroken||m.isLog&&h)&&m.lin2val;k||(k=m.transA);c&&(e*=-1,D=m.len);m.reversed&&(e*=-1,D-=e*(m.sector||m.len));b?(a=(a*e+D-x)/k+u,h&&(a=m.lin2val(a))):(h&&(a=m.val2lin(a)),a=n(u)?e*(a-u)*k+D+e*x+(n(d)?k*d:0):void 0);return a},toPixels:function(a,
b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,u,h){var m=this.chart,d=this.left,e=this.top,D,k,x=c&&m.oldChartHeight||m.chartHeight,g=c&&m.oldChartWidth||m.chartWidth,f;D=this.transB;var E=function(a,b,m){if(a<b||a>m)u?a=Math.min(Math.max(b,a),m):f=!0;return a};h=v(h,this.translate(a,null,null,c));h=Math.min(Math.max(-1E5,h),1E5);a=c=Math.round(h+D);D=k=Math.round(x-
h-D);n(h)?this.horiz?(D=e,k=x-this.bottom,a=c=E(a,d,d+this.width)):(a=d,c=g-this.right,D=k=E(D,e,e+this.height)):(f=!0,u=!1);return f&&!u?null:m.renderer.crispLine(["M",a,D,"L",c,k],b||1)},getLinearTickPositions:function(a,b,c){var m,h=f(Math.floor(b/a)*a);c=f(Math.ceil(c/a)*a);var d=[],e;f(h+a)===h&&(e=20);if(this.single)return[b];for(b=h;b<=c;){d.push(b);b=f(b+a,e);if(b===m)break;m=b}return d},getMinorTickInterval:function(){var a=this.options;return!0===a.minorTicks?v(a.minorTickInterval,"auto"):
!1===a.minorTicks?null:a.minorTickInterval},getMinorTickPositions:function(){var a=this,b=a.options,c=a.tickPositions,u=a.minorTickInterval,h=[],d=a.pointRangePadding||0,k=a.min-d,d=a.max+d,n=d-k;if(n&&n/u<a.len/3)if(a.isLog)e(this.paddedTicks,function(b,c,m){c&&h.push.apply(h,a.getLogTickPositions(u,m[c-1],m[c],!0))});else if(a.isDatetimeAxis&&"auto"===this.getMinorTickInterval())h=h.concat(a.getTimeTicks(a.normalizeTimeTickInterval(u),k,d,b.startOfWeek));else for(b=k+(c[0]-k)%u;b<=d&&b!==h[0];b+=
u)h.push(b);0!==h.length&&a.trimTicks(h);return h},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,h,d,k,n,x,g,f,E;this.isXAxis&&void 0===this.minRange&&!this.isLog&&(r(a.min)||r(a.max)?this.minRange=null:(e(this.series,function(a){g=a.xData;for(n=f=a.xIncrement?1:g.length-1;0<n;n--)if(x=g[n]-g[n-1],void 0===k||x<k)k=x}),this.minRange=Math.min(5*k,this.dataMax-this.dataMin)));c-b<this.minRange&&(d=this.dataMax-this.dataMin>=this.minRange,E=this.minRange,h=(E-c+b)/2,h=[b-h,v(a.min,
b-h)],d&&(h[2]=this.isLog?this.log2lin(this.dataMin):this.dataMin),b=B(h),c=[b+E,v(a.max,b+E)],d&&(c[2]=this.isLog?this.log2lin(this.dataMax):this.dataMax),c=l(c),c-b<E&&(h[0]=c-E,h[1]=v(a.min,c-E),b=B(h)));this.min=b;this.max=c},getClosest:function(){var a;this.categories?a=1:e(this.series,function(b){var c=b.closestPointRange,m=b.visible||!b.chart.options.chart.ignoreHiddenSeries;!b.noSharedTooltip&&r(c)&&m&&(a=r(a)?Math.min(a,c):c)});return a},nameToX:function(a){var c=h(this.categories),m=c?this.categories:
this.names,u=a.options.x,d;a.series.requireSorting=!1;r(u)||(u=!1===this.options.uniqueNames?a.series.autoIncrement():c?b(a.name,m):v(m.keys[a.name],-1));-1===u?c||(d=m.length):d=u;void 0!==d&&(this.names[d]=a.name,this.names.keys[a.name]=d);return d},updateNames:function(){var b=this,c=this.names;0<c.length&&(e(a.keys(c.keys),function(a){delete c.keys[a]}),c.length=0,this.minRange=this.userMinRange,e(this.series||[],function(a){a.xIncrement=null;if(!a.points||a.isDirtyData)a.processData(),a.generatePoints();
e(a.points,function(c,m){var h;c.options&&(h=b.nameToX(c),void 0!==h&&h!==c.x&&(c.x=h,a.xData[m]=h))})}))},setAxisTranslation:function(a){var b=this,c=b.max-b.min,m=b.axisPointRange||0,h,d=0,n=0,x=b.linkedParent,g=!!b.categories,f=b.transA,E=b.isXAxis;if(E||g||m)h=b.getClosest(),x?(d=x.minPointOffset,n=x.pointRangePadding):e(b.series,function(a){var c=g?1:E?v(a.options.pointRange,h,0):b.axisPointRange||0;a=a.options.pointPlacement;m=Math.max(m,c);b.single||(d=Math.max(d,J(a)?0:c/2),n=Math.max(n,"on"===
a?0:c))}),x=b.ordinalSlope&&h?b.ordinalSlope/h:1,b.minPointOffset=d*=x,b.pointRangePadding=n*=x,b.pointRange=Math.min(m,c),E&&(b.closestPointRange=h);a&&(b.oldTransA=f);b.translationSlope=b.transA=f=b.options.staticScale||b.len/(c+n||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=f*d;k(this,"afterSetAxisTranslation")},minFromRange:function(){return this.max-this.range},setTickInterval:function(b){var c=this,m=c.chart,h=c.options,d=c.isLog,x=c.isDatetimeAxis,g=c.isXAxis,E=c.isLinked,C=h.maxPadding,
t=h.minPadding,l=h.tickInterval,G=h.tickPixelInterval,M=c.categories,p=n(c.threshold)?c.threshold:null,J=c.softThreshold,K,H,w,z;x||M||E||this.getTickAmount();w=v(c.userMin,h.min);z=v(c.userMax,h.max);E?(c.linkedParent=m[c.coll][h.linkedTo],m=c.linkedParent.getExtremes(),c.min=v(m.min,m.dataMin),c.max=v(m.max,m.dataMax),h.type!==c.linkedParent.options.type&&a.error(11,1)):(!J&&r(p)&&(c.dataMin>=p?(K=p,t=0):c.dataMax<=p&&(H=p,C=0)),c.min=v(w,K,c.dataMin),c.max=v(z,H,c.dataMax));d&&(c.positiveValuesOnly&&
!b&&0>=Math.min(c.min,v(c.dataMin,c.min))&&a.error(10,1),c.min=f(c.log2lin(c.min),15),c.max=f(c.log2lin(c.max),15));c.range&&r(c.max)&&(c.userMin=c.min=w=Math.max(c.dataMin,c.minFromRange()),c.userMax=z=c.max,c.range=null);k(c,"foundExtremes");c.beforePadding&&c.beforePadding();c.adjustForMinRange();!(M||c.axisPointRange||c.usePercentage||E)&&r(c.min)&&r(c.max)&&(m=c.max-c.min)&&(!r(w)&&t&&(c.min-=m*t),!r(z)&&C&&(c.max+=m*C));n(h.softMin)&&!n(c.userMin)&&(c.min=Math.min(c.min,h.softMin));n(h.softMax)&&
!n(c.userMax)&&(c.max=Math.max(c.max,h.softMax));n(h.floor)&&(c.min=Math.max(c.min,h.floor));n(h.ceiling)&&(c.max=Math.min(c.max,h.ceiling));J&&r(c.dataMin)&&(p=p||0,!r(w)&&c.min<p&&c.dataMin>=p?c.min=p:!r(z)&&c.max>p&&c.dataMax<=p&&(c.max=p));c.tickInterval=c.min===c.max||void 0===c.min||void 0===c.max?1:E&&!l&&G===c.linkedParent.options.tickPixelInterval?l=c.linkedParent.tickInterval:v(l,this.tickAmount?(c.max-c.min)/Math.max(this.tickAmount-1,1):void 0,M?1:(c.max-c.min)*G/Math.max(c.len,G));g&&
!b&&e(c.series,function(a){a.processData(c.min!==c.oldMin||c.max!==c.oldMax)});c.setAxisTranslation(!0);c.beforeSetTickPositions&&c.beforeSetTickPositions();c.postProcessTickInterval&&(c.tickInterval=c.postProcessTickInterval(c.tickInterval));c.pointRange&&!l&&(c.tickInterval=Math.max(c.pointRange,c.tickInterval));b=v(h.minTickInterval,c.isDatetimeAxis&&c.closestPointRange);!l&&c.tickInterval<b&&(c.tickInterval=b);x||d||l||(c.tickInterval=A(c.tickInterval,null,q(c.tickInterval),v(h.allowDecimals,
!(.5<c.tickInterval&&5>c.tickInterval&&1E3<c.max&&9999>c.max)),!!this.tickAmount));this.tickAmount||(c.tickInterval=c.unsquish());this.setTickPositions()},setTickPositions:function(){var a=this.options,b,c=a.tickPositions;b=this.getMinorTickInterval();var h=a.tickPositioner,d=a.startOnTick,e=a.endOnTick;this.tickmarkOffset=this.categories&&"between"===a.tickmarkPlacement&&1===this.tickInterval?.5:0;this.minorTickInterval="auto"===b&&this.tickInterval?this.tickInterval/5:b;this.single=this.min===this.max&&
r(this.min)&&!this.tickAmount&&(parseInt(this.min,10)===this.min||!1!==a.allowDecimals);this.tickPositions=b=c&&c.slice();!b&&(b=this.isDatetimeAxis?this.getTimeTicks(this.normalizeTimeTickInterval(this.tickInterval,a.units),this.min,this.max,a.startOfWeek,this.ordinalPositions,this.closestPointRange,!0):this.isLog?this.getLogTickPosit