/*
 Highstock JS v6.1.0-modified (2018-06-16)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(U,K){"object"===typeof module&&module.exports?module.exports=U.document?K(U):K:U.Highcharts=K(U)})("undefined"!==typeof window?window:this,function(U){var K=function(){var a="undefined"===typeof U?window:U,F=a.document,G=a.navigator&&a.navigator.userAgent||"",H=F&&F.createElementNS&&!!F.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,u=/(edge|msie|trident)/i.test(G)&&!a.opera,g=-1!==G.indexOf("Firefox"),e=-1!==G.indexOf("Chrome"),x=g&&4>parseInt(G.split("Firefox/")[1],
10),a=a.Highcharts?a.Highcharts.error(16,!0):{product:"Highstock",version:"6.1.0-modified",deg2rad:2*Math.PI/360,doc:F,hasBidiBug:x,hasTouch:F&&void 0!==F.documentElement.ontouchstart,isMS:u,isWebKit:-1!==G.indexOf("AppleWebKit"),isFirefox:g,isChrome:e,isSafari:!e&&-1!==G.indexOf("Safari"),isTouchDevice:/(Mobile|Android|Windows Phone)/.test(G),SVG_NS:"http://www.w3.org/2000/svg",chartCount:0,seriesTypes:{},symbolSizes:{},svg:H,win:a,marginNames:["plotTop","marginRight","marginBottom","plotLeft"],
noop:function(){},charts:[]};console.log(a);return a}();(function(a){a.timers=[];var F=a.charts,G=a.doc,H=a.win;a.error=function(u,g){u=a.isNumber(u)?"Highcharts error #"+u+": www.highcharts.com/errors/"+u:u;if(g)throw Error(u);H.console&&console.log(u)};a.Fx=function(a,g,e){this.options=g;this.elem=a;this.prop=e};a.Fx.prototype={dSetter:function(){var a=this.paths[0],g=this.paths[1],e=[],x=this.now,z=a.length,v;if(1===x)e=this.toD;else if(z===g.length&&1>x)for(;z--;)v=parseFloat(a[z]),e[z]=isNaN(v)?
g[z]:x*parseFloat(g[z]-v)+v;else e=g;this.elem.attr("d",e,null,!0)},update:function(){var a=this.elem,g=this.prop,e=this.now,x=this.options.step;if(this[g+"Setter"])this[g+"Setter"]();else a.attr?a.element&&a.attr(g,e,null,!0):a.style[g]=e+this.unit;x&&x.call(a,e,this)},run:function(u,g,e){var x=this,z=x.options,v=function(a){return v.stopped?!1:x.step(a)},t=H.requestAnimationFrame||function(a){setTimeout(a,13)},d=function(){for(var c=0;c<a.timers.length;c++)a.timers[c]()||a.timers.splice(c--,1);
a.timers.length&&t(d)};u!==g||this.elem["forceAnimate:"+this.prop]?(this.startTime=+new Date,this.start=u,this.end=g,this.unit=e,this.now=this.start,this.pos=0,v.elem=this.elem,v.prop=this.prop,v()&&1===a.timers.push(v)&&t(d)):(delete z.curAnim[this.prop],z.complete&&0===a.keys(z.curAnim).length&&z.complete.call(this.elem))},step:function(u){var g=+new Date,e,x=this.options,z=this.elem,v=x.complete,t=x.duration,d=x.curAnim;z.attr&&!z.element?u=!1:u||g>=t+this.startTime?(this.now=this.end,this.pos=
1,this.update(),e=d[this.prop]=!0,a.objectEach(d,function(a){!0!==a&&(e=!1)}),e&&v&&v.call(z),u=!1):(this.pos=x.easing((g-this.startTime)/t),this.now=this.start+(this.end-this.start)*this.pos,this.update(),u=!0);return u},initPath:function(u,g,e){function x(a){var b,c;for(l=a.length;l--;)b="M"===a[l]||"L"===a[l],c=/[a-zA-Z]/.test(a[l+3]),b&&c&&a.splice(l+1,0,a[l+1],a[l+2],a[l+1],a[l+2])}function z(a,b){for(;a.length<r;){a[0]=b[r-a.length];var c=a.slice(0,n);[].splice.apply(a,[0,0].concat(c));h&&(c=
a.slice(a.length-n),[].splice.apply(a,[a.length,0].concat(c)),l--)}a[0]="M"}function v(a,c){for(var d=(r-a.length)/n;0<d&&d--;)b=a.slice().splice(a.length/B-n,n*B),b[0]=c[r-n-d*n],A&&(b[n-6]=b[n-2],b[n-5]=b[n-1]),[].splice.apply(a,[a.length/B,0].concat(b)),h&&d--}g=g||"";var t,d=u.startX,c=u.endX,A=-1<g.indexOf("C"),n=A?7:3,r,b,l;g=g.split(" ");e=e.slice();var h=u.isArea,B=h?2:1,C;A&&(x(g),x(e));if(d&&c){for(l=0;l<d.length;l++)if(d[l]===c[0]){t=l;break}else if(d[0]===c[c.length-d.length+l]){t=l;C=
!0;break}void 0===t&&(g=[])}g.length&&a.isNumber(t)&&(r=e.length+t*B*n,C?(z(g,e),v(e,g)):(z(e,g),v(g,e)));return[g,e]}};a.Fx.prototype.fillSetter=a.Fx.prototype.strokeSetter=function(){this.elem.attr(this.prop,a.color(this.start).tweenTo(a.color(this.end),this.pos),null,!0)};a.merge=function(){var u,g=arguments,e,x={},z=function(e,t){"object"!==typeof e&&(e={});a.objectEach(t,function(d,c){!a.isObject(d,!0)||a.isClass(d)||a.isDOMElement(d)?e[c]=t[c]:e[c]=z(e[c]||{},d)});return e};!0===g[0]&&(x=g[1],
g=Array.prototype.slice.call(g,2));e=g.length;for(u=0;u<e;u++)x=z(x,g[u]);return x};a.pInt=function(a,g){return parseInt(a,g||10)};a.isString=function(a){return"string"===typeof a};a.isArray=function(a){a=Object.prototype.toString.call(a);return"[object Array]"===a||"[object Array Iterator]"===a};a.isObject=function(u,g){return!!u&&"object"===typeof u&&(!g||!a.isArray(u))};a.isDOMElement=function(u){return a.isObject(u)&&"number"===typeof u.nodeType};a.isClass=function(u){var g=u&&u.constructor;return!(!a.isObject(u,
!0)||a.isDOMElement(u)||!g||!g.name||"Object"===g.name)};a.isNumber=function(a){return"number"===typeof a&&!isNaN(a)&&Infinity>a&&-Infinity<a};a.erase=function(a,g){for(var e=a.length;e--;)if(a[e]===g){a.splice(e,1);break}};a.defined=function(a){return void 0!==a&&null!==a};a.attr=function(u,g,e){var x;a.isString(g)?a.defined(e)?u.setAttribute(g,e):u&&u.getAttribute&&((x=u.getAttribute(g))||"class"!==g||(x=u.getAttribute(g+"Name"))):a.defined(g)&&a.isObject(g)&&a.objectEach(g,function(a,e){u.setAttribute(e,
a)});return x};a.splat=function(u){return a.isArray(u)?u:[u]};a.syncTimeout=function(a,g,e){if(g)return setTimeout(a,g,e);a.call(0,e)};a.clearTimeout=function(u){a.defined(u)&&clearTimeout(u)};a.extend=function(a,g){var e;a||(a={});for(e in g)a[e]=g[e];return a};a.pick=function(){var a=arguments,g,e,x=a.length;for(g=0;g<x;g++)if(e=a[g],void 0!==e&&null!==e)return e};a.css=function(u,g){a.isMS&&!a.svg&&g&&void 0!==g.opacity&&(g.filter="alpha(opacity\x3d"+100*g.opacity+")");a.extend(u.style,g)};a.createElement=
function(u,g,e,x,z){u=G.createElement(u);var v=a.css;g&&a.extend(u,g);z&&v(u,{padding:0,border:"none",margin:0});e&&v(u,e);x&&x.appendChild(u);return u};a.extendClass=function(u,g){var e=function(){};e.prototype=new u;a.extend(e.prototype,g);return e};a.pad=function(a,g,e){return Array((g||2)+1-String(a).replace("-","").length).join(e||0)+a};a.relativeLength=function(a,g,e){return/%$/.test(a)?g*parseFloat(a)/100+(e||0):parseFloat(a)};a.wrap=function(a,g,e){var x=a[g];a[g]=function(){var a=Array.prototype.slice.call(arguments),
v=arguments,t=this;t.proceed=function(){x.apply(t,arguments.length?arguments:v)};a.unshift(x);a=e.apply(this,a);t.proceed=null;return a}};a.formatSingle=function(u,g,e){var x=/\.([0-9])/,z=a.defaultOptions.lang;/f$/.test(u)?(e=(e=u.match(x))?e[1]:-1,null!==g&&(g=a.numberFormat(g,e,z.decimalPoint,-1<u.indexOf(",")?z.thousandsSep:""))):g=(e||a.time).dateFormat(u,g);return g};a.format=function(u,g,e){for(var x="{",z=!1,v,t,d,c,A=[],n;u;){x=u.indexOf(x);if(-1===x)break;v=u.slice(0,x);if(z){v=v.split(":");
t=v.shift().split(".");c=t.length;n=g;for(d=0;d<c;d++)n&&(n=n[t[d]]);v.length&&(n=a.formatSingle(v.join(":"),n,e));A.push(n)}else A.push(v);u=u.slice(x+1);x=(z=!z)?"}":"{"}A.push(u);return A.join("")};a.getMagnitude=function(a){return Math.pow(10,Math.floor(Math.log(a)/Math.LN10))};a.normalizeTickInterval=function(u,g,e,x,z){var v,t=u;e=a.pick(e,1);v=u/e;g||(g=z?[1,1.2,1.5,2,2.5,3,4,5,6,8,10]:[1,2,2.5,5,10],!1===x&&(1===e?g=a.grep(g,function(a){return 0===a%1}):.1>=e&&(g=[1/e])));for(x=0;x<g.length&&
!(t=g[x],z&&t*e>=u||!z&&v<=(g[x]+(g[x+1]||g[x]))/2);x++);return t=a.correctFloat(t*e,-Math.round(Math.log(.001)/Math.LN10))};a.stableSort=function(a,g){var e=a.length,x,z;for(z=0;z<e;z++)a[z].safeI=z;a.sort(function(a,t){x=g(a,t);return 0===x?a.safeI-t.safeI:x});for(z=0;z<e;z++)delete a[z].safeI};a.arrayMin=function(a){for(var g=a.length,e=a[0];g--;)a[g]<e&&(e=a[g]);return e};a.arrayMax=function(a){for(var g=a.length,e=a[0];g--;)a[g]>e&&(e=a[g]);return e};a.destroyObjectProperties=function(u,g){a.objectEach(u,
function(a,x){a&&a!==g&&a.destroy&&a.destroy();delete u[x]})};a.discardElement=function(u){var g=a.garbageBin;g||(g=a.createElement("div"));u&&g.appendChild(u);g.innerHTML=""};a.correctFloat=function(a,g){return parseFloat(a.toPrecision(g||14))};a.setAnimation=function(u,g){g.renderer.globalAnimation=a.pick(u,g.options.chart.animation,!0)};a.animObject=function(u){return a.isObject(u)?a.merge(u):{duration:u?500:0}};a.timeUnits={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5,month:24192E5,
year:314496E5};a.numberFormat=function(u,g,e,x){u=+u||0;g=+g;var z=a.defaultOptions.lang,v=(u.toString().split(".")[1]||"").split("e")[0].length,t,d,c=u.toString().split("e");-1===g?g=Math.min(v,20):a.isNumber(g)?g&&c[1]&&0>c[1]&&(t=g+ +c[1],0<=t?(c[0]=(+c[0]).toExponential(t).split("e")[0],g=t):(c[0]=c[0].split(".")[0]||0,u=20>g?(c[0]*Math.pow(10,c[1])).toFixed(g):0,c[1]=0)):g=2;d=(Math.abs(c[1]?c[0]:u)+Math.pow(10,-Math.max(g,v)-1)).toFixed(g);v=String(a.pInt(d));t=3<v.length?v.length%3:0;e=a.pick(e,
z.decimalPoint);x=a.pick(x,z.thousandsSep);u=(0>u?"-":"")+(t?v.substr(0,t)+x:"");u+=v.substr(t).replace(/(\d{3})(?=\d)/g,"$1"+x);g&&(u+=e+d.slice(-g));c[1]&&0!==+u&&(u+="e"+c[1]);return u};Math.easeInOutSine=function(a){return-.5*(Math.cos(Math.PI*a)-1)};a.getStyle=function(u,g,e){if("width"===g)return Math.max(0,Math.min(u.offsetWidth,u.scrollWidth)-a.getStyle(u,"padding-left")-a.getStyle(u,"padding-right"));if("height"===g)return Math.max(0,Math.min(u.offsetHeight,u.scrollHeight)-a.getStyle(u,"padding-top")-
a.getStyle(u,"padding-bottom"));H.getComputedStyle||a.error(27,!0);if(u=H.getComputedStyle(u,void 0))u=u.getPropertyValue(g),a.pick(e,"opacity"!==g)&&(u=a.pInt(u));return u};a.inArray=function(u,g,e){return(a.indexOfPolyfill||Array.prototype.indexOf).call(g,u,e)};a.grep=function(u,g){return(a.filterPolyfill||Array.prototype.filter).call(u,g)};a.find=Array.prototype.find?function(a,g){return a.find(g)}:function(a,g){var e,x=a.length;for(e=0;e<x;e++)if(g(a[e],e))return a[e]};a.some=function(u,g,e){return(a.somePolyfill||
Array.prototype.some).call(u,g,e)};a.map=function(a,g){for(var e=[],x=0,z=a.length;x<z;x++)e[x]=g.call(a[x],a[x],x,a);return e};a.keys=function(u){return(a.keysPolyfill||Object.keys).call(void 0,u)};a.reduce=function(u,g,e){return(a.reducePolyfill||Array.prototype.reduce).call(u,g,e)};a.offset=function(a){var g=G.documentElement;a=a.parentElement||a.parentNode?a.getBoundingClientRect():{top:0,left:0};return{top:a.top+(H.pageYOffset||g.scrollTop)-(g.clientTop||0),left:a.left+(H.pageXOffset||g.scrollLeft)-
(g.clientLeft||0)}};a.stop=function(u,g){for(var e=a.timers.length;e--;)a.timers[e].elem!==u||g&&g!==a.timers[e].prop||(a.timers[e].stopped=!0)};a.each=function(u,g,e){return(a.forEachPolyfill||Array.prototype.forEach).call(u,g,e)};a.objectEach=function(a,g,e){for(var x in a)a.hasOwnProperty(x)&&g.call(e||a[x],a[x],x,a)};a.addEvent=function(u,g,e,x){var z,v=u.addEventListener||a.addEventListenerPolyfill;z="function"===typeof u&&u.prototype?u.prototype.protoEvents=u.prototype.protoEvents||{}:u.hcEvents=
u.hcEvents||{};a.Point&&u instanceof a.Point&&u.series&&u.series.chart&&(u.series.chart.runTrackerClick=!0);v&&v.call(u,g,e,!1);z[g]||(z[g]=[]);z[g].push(e);x&&a.isNumber(x.order)&&(e.order=x.order,z[g].sort(function(a,d){return a.order-d.order}));return function(){a.removeEvent(u,g,e)}};a.removeEvent=function(u,g,e){function x(d,c){var A=u.removeEventListener||a.removeEventListenerPolyfill;A&&A.call(u,d,c,!1)}function z(d){var c,A;u.nodeName&&(g?(c={},c[g]=!0):c=d,a.objectEach(c,function(a,c){if(d[c])for(A=
d[c].length;A--;)x(c,d[c][A])}))}var v,t;a.each(["protoEvents","hcEvents"],function(d){var c=u[d];c&&(g?(v=c[g]||[],e?(t=a.inArray(e,v),-1<t&&(v.splice(t,1),c[g]=v),x(g,e)):(z(c),c[g]=[])):(z(c),u[d]={}))})};a.fireEvent=function(u,g,e,x){var z,v,t,d,c;e=e||{};G.createEvent&&(u.dispatchEvent||u.fireEvent)?(z=G.createEvent("Events"),z.initEvent(g,!0,!0),a.extend(z,e),u.dispatchEvent?u.dispatchEvent(z):u.fireEvent(g,z)):a.each(["protoEvents","hcEvents"],function(A){if(u[A])for(v=u[A][g]||[],t=v.length,
e.target||a.extend(e,{preventDefault:function(){e.defaultPrevented=!0},target:u,type:g}),d=0;d<t;d++)(c=v[d])&&!1===c.call(u,e)&&e.preventDefault()});x&&!e.defaultPrevented&&x.call(u,e)};a.animate=function(u,g,e){var x,z="",v,t,d;a.isObject(e)||(d=arguments,e={duration:d[2],easing:d[3],complete:d[4]});a.isNumber(e.duration)||(e.duration=400);e.easing="function"===typeof e.easing?e.easing:Math[e.easing]||Math.easeInOutSine;e.curAnim=a.merge(g);a.objectEach(g,function(c,d){a.stop(u,d);t=new a.Fx(u,
e,d);v=null;"d"===d?(t.paths=t.initPath(u,u.d,g.d),t.toD=g.d,x=0,v=1):u.attr?x=u.attr(d):(x=parseFloat(a.getStyle(u,d))||0,"opacity"!==d&&(z="px"));v||(v=c);v&&v.match&&v.match("px")&&(v=v.replace(/px/g,""));t.run(x,v,z)})};a.seriesType=function(u,g,e,x,z){var v=a.getOptions(),t=a.seriesTypes;v.plotOptions[u]=a.merge(v.plotOptions[g],e);t[u]=a.extendClass(t[g]||function(){},x);t[u].prototype.type=u;z&&(t[u].prototype.pointClass=a.extendClass(a.Point,z));return t[u]};a.uniqueKey=function(){var a=Math.random().toString(36).substring(2,
9),g=0;return function(){return"highcharts-"+a+"-"+g++}}();H.jQuery&&(H.jQuery.fn.highcharts=function(){var u=[].slice.call(arguments);if(this[0])return u[0]?(new (a[a.isString(u[0])?u.shift():"Chart"])(this[0],u[0],u[1]),this):F[a.attr(this[0],"data-highcharts-chart")]})})(K);(function(a){var F=a.each,G=a.isNumber,H=a.map,u=a.merge,g=a.pInt;a.Color=function(e){if(!(this instanceof a.Color))return new a.Color(e);this.init(e)};a.Color.prototype={parsers:[{regex:/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,
parse:function(a){return[g(a[1]),g(a[2]),g(a[3]),parseFloat(a[4],10)]}},{regex:/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,parse:function(a){return[g(a[1]),g(a[2]),g(a[3]),1]}}],names:{none:"rgba(255,255,255,0)",white:"#ffffff",black:"#000000"},init:function(e){var g,z,v,t;if((this.input=e=this.names[e&&e.toLowerCase?e.toLowerCase():""]||e)&&e.stops)this.stops=H(e.stops,function(d){return new a.Color(d[1])});else if(e&&e.charAt&&"#"===e.charAt()&&(g=e.length,e=parseInt(e.substr(1),
16),7===g?z=[(e&16711680)>>16,(e&65280)>>8,e&255,1]:4===g&&(z=[(e&3840)>>4|(e&3840)>>8,(e&240)>>4|e&240,(e&15)<<4|e&15,1])),!z)for(v=this.parsers.length;v--&&!z;)t=this.parsers[v],(g=t.regex.exec(e))&&(z=t.parse(g));this.rgba=z||[]},get:function(a){var e=this.input,z=this.rgba,g;this.stops?(g=u(e),g.stops=[].concat(g.stops),F(this.stops,function(t,d){g.stops[d]=[g.stops[d][0],t.get(a)]})):g=z&&G(z[0])?"rgb"===a||!a&&1===z[3]?"rgb("+z[0]+","+z[1]+","+z[2]+")":"a"===a?z[3]:"rgba("+z.join(",")+")":e;
return g},brighten:function(a){var e,z=this.rgba;if(this.stops)F(this.stops,function(e){e.brighten(a)});else if(G(a)&&0!==a)for(e=0;3>e;e++)z[e]+=g(255*a),0>z[e]&&(z[e]=0),255<z[e]&&(z[e]=255);return this},setOpacity:function(a){this.rgba[3]=a;return this},tweenTo:function(a,g){var e=this.rgba,v=a.rgba;v.length&&e&&e.length?(a=1!==v[3]||1!==e[3],g=(a?"rgba(":"rgb(")+Math.round(v[0]+(e[0]-v[0])*(1-g))+","+Math.round(v[1]+(e[1]-v[1])*(1-g))+","+Math.round(v[2]+(e[2]-v[2])*(1-g))+(a?","+(v[3]+(e[3]-
v[3])*(1-g)):"")+")"):g=a.input||"none";return g}};a.color=function(e){return new a.Color(e)}})(K);(function(a){var F,G,H=a.addEvent,u=a.animate,g=a.attr,e=a.charts,x=a.color,z=a.css,v=a.createElement,t=a.defined,d=a.deg2rad,c=a.destroyObjectProperties,A=a.doc,n=a.each,r=a.extend,b=a.erase,l=a.grep,h=a.hasTouch,B=a.inArray,C=a.isArray,q=a.isFirefox,D=a.isMS,y=a.isObject,k=a.isString,w=a.isWebKit,I=a.merge,p=a.noop,J=a.objectEach,f=a.pick,E=a.pInt,L=a.removeEvent,m=a.splat,M=a.stop,W=a.svg,Q=a.SVG_NS,
N=a.symbolSizes,P=a.win;F=a.SVGElement=function(){return this};r(F.prototype,{opacity:1,SVG_NS:Q,textProps:"direction fontSize fontWeight fontFamily fontStyle color lineHeight width textAlign textDecoration textOverflow textOutline".split(" "),init:function(a,f){this.element="span"===f?v(f):A.createElementNS(this.SVG_NS,f);this.renderer=a},animate:function(b,m,E){m=a.animObject(f(m,this.renderer.globalAnimation,!0));0!==m.duration?(E&&(m.complete=E),u(this,b,m)):(this.attr(b,null,E),m.step&&m.step.call(this));
return this},complexColor:function(f,b,m){var E=this.renderer,k,c,p,h,O,d,w,l,r,q,L,B=[],M;a.fireEvent(this.renderer,"complexColor",{args:arguments},function(){f.radialGradient?c="radialGradient":f.linearGradient&&(c="linearGradient");c&&(p=f[c],O=E.gradients,w=f.stops,q=m.radialReference,C(p)&&(f[c]=p={x1:p[0],y1:p[1],x2:p[2],y2:p[3],gradientUnits:"userSpaceOnUse"}),"radialGradient"===c&&q&&!t(p.gradientUnits)&&(h=p,p=I(p,E.getRadialAttr(q,h),{gradientUnits:"userSpaceOnUse"})),J(p,function(a,f){"id"!==
f&&B.push(f,a)}),J(w,function(a){B.push(a)}),B=B.join(","),O[B]?L=O[B].attr("id"):(p.id=L=a.uniqueKey(),O[B]=d=E.createElement(c).attr(p).add(E.defs),d.radAttr=h,d.stops=[],n(w,function(f){0===f[1].indexOf("rgba")?(k=a.color(f[1]),l=k.get("rgb"),r=k.get("a")):(l=f[1],r=1);f=E.createElement("stop").attr({offset:f[0],"stop-color":l,"stop-opacity":r}).add(d);d.stops.push(f)})),M="url("+E.url+"#"+L+")",m.setAttribute(b,M),m.gradient=B,f.toString=function(){return M})})},applyTextOutline:function(f){var m=
this.element,E,p,k,c,h;-1!==f.indexOf("contrast")&&(f=f.replace(/contrast/g,this.renderer.getContrast(m.style.fill)));f=f.split(" ");p=f[f.length-1];if((k=f[0])&&"none"!==k&&a.svg){this.fakeTS=!0;f=[].slice.call(m.getElementsByTagName("tspan"));this.ySetter=this.xSetter;k=k.replace(/(^[\d\.]+)(.*?)$/g,function(a,f,b){return 2*f+b});for(h=f.length;h--;)E=f[h],"highcharts-text-outline"===E.getAttribute("class")&&b(f,m.removeChild(E));c=m.firstChild;n(f,function(a,f){0===f&&(a.setAttribute("x",m.getAttribute("x")),
f=m.getAttribute("y"),a.setAttribute("y",f||0),null===f&&m.setAttribute("y",0));a=a.cloneNode(1);g(a,{"class":"highcharts-text-outline",fill:p,stroke:p,"stroke-width":k,"stroke-linejoin":"round"});m.insertBefore(a,c)})}},attr:function(a,f,b,m){var E,k=this.element,p,c=this,h,d;"string"===typeof a&&void 0!==f&&(E=a,a={},a[E]=f);"string"===typeof a?c=(this[a+"Getter"]||this._defaultGetter).call(this,a,k):(J(a,function(f,b){h=!1;m||M(this,b);this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)$/.test(b)&&
(p||(this.symbolAttr(a),p=!0),h=!0);!this.rotation||"x"!==b&&"y"!==b||(this.doTransform=!0);h||(d=this[b+"Setter"]||this._defaultSetter,d.call(this,f,b,k))},this),this.afterSetters());b&&b.call(this);return c},afterSetters:function(){this.doTransform&&(this.updateTransform(),this.doTransform=!1)},addClass:function(a,f){var b=this.attr("class")||"";-1===b.indexOf(a)&&(f||(a=(b+(b?" ":"")+a).replace("  "," ")),this.attr("class",a));return this},hasClass:function(a){return-1!==B(a,(this.attr("class")||
"").split(" "))},removeClass:function(a){return this.attr("class",(this.attr("class")||"").replace(a,""))},symbolAttr:function(a){var b=this;n("x y r start end width height innerR anchorX anchorY".split(" "),function(m){b[m]=f(a[m],b[m])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a,f){var b;f=f||a.strokeWidth||0;b=Math.round(f)%2/2;a.x=Math.floor(a.x||this.x||
0)+b;a.y=Math.floor(a.y||this.y||0)+b;a.width=Math.floor((a.width||this.width||0)-2*b);a.height=Math.floor((a.height||this.height||0)-2*b);t(a.strokeWidth)&&(a.strokeWidth=f);return a},css:function(a){var f=this.styles,b={},m=this.element,k,p="",c,h=!f,d=["textOutline","textOverflow","width"];a&&a.color&&(a.fill=a.color);f&&J(a,function(a,m){a!==f[m]&&(b[m]=a,h=!0)});h&&(f&&(a=r(f,b)),a&&(null===a.width||"auto"===a.width?delete this.textWidth:"text"===m.nodeName.toLowerCase()&&a.width&&(k=this.textWidth=
E(a.width))),this.styles=a,k&&!W&&this.renderer.forExport&&delete a.width,m.namespaceURI===this.SVG_NS?(c=function(a,f){return"-"+f.toLowerCase()},J(a,function(a,f){-1===B(f,d)&&(p+=f.replace(/([A-Z])/g,c)+":"+a+";")}),p&&g(m,"style",p)):z(m,a),this.added&&("text"===this.element.nodeName&&this.renderer.buildText(this),a&&a.textOutline&&this.applyTextOutline(a.textOutline)));return this},getStyle:function(a){return P.getComputedStyle(this.element||this,"").getPropertyValue(a)},strokeWidth:function(){var a=
this.getStyle("stroke-width"),f;a.indexOf("px")===a.length-2?a=E(a):(f=A.createElementNS(Q,"rect"),g(f,{width:a,"stroke-width":0}),this.element.parentNode.appendChild(f),a=f.getBBox().width,f.parentNode.removeChild(f));return a},on:function(a,f){var b=this,m=b.element;h&&"click"===a?(m.ontouchstart=function(a){b.touchEventFired=Date.now();a.preventDefault();f.call(m,a)},m.onclick=function(a){(-1===P.navigator.userAgent.indexOf("Android")||1100<Date.now()-(b.touchEventFired||0))&&f.call(m,a)}):m["on"+
a]=f;return this},setRadialReference:function(a){var f=this.renderer.gradients[this.element.gradient];this.element.radialReference=a;f&&f.radAttr&&f.animate(this.renderer.getRadialAttr(a,f.radAttr));return this},translate:function(a,f){return this.attr({translateX:a,translateY:f})},invert:function(a){this.inverted=a;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,m=this.scaleX,E=this.scaleY,p=this.inverted,k=this.rotation,c=this.matrix,
h=this.element;p&&(a+=this.width,b+=this.height);a=["translate("+a+","+b+")"];t(c)&&a.push("matrix("+c.join(",")+")");p?a.push("rotate(90) scale(-1,1)"):k&&a.push("rotate("+k+" "+f(this.rotationOriginX,h.getAttribute("x"),0)+" "+f(this.rotationOriginY,h.getAttribute("y")||0)+")");(t(m)||t(E))&&a.push("scale("+f(m,1)+" "+f(E,1)+")");a.length&&h.setAttribute("transform",a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,m,E){var p,c,h,d,w={};
c=this.renderer;h=c.alignedObjects;var I,l;if(a){if(this.alignOptions=a,this.alignByTranslate=m,!E||k(E))this.alignTo=p=E||"renderer",b(h,this),h.push(this),E=null}else a=this.alignOptions,m=this.alignByTranslate,p=this.alignTo;E=f(E,c[p],c);p=a.align;c=a.verticalAlign;h=(E.x||0)+(a.x||0);d=(E.y||0)+(a.y||0);"right"===p?I=1:"center"===p&&(I=2);I&&(h+=(E.width-(a.width||0))/I);w[m?"translateX":"x"]=Math.round(h);"bottom"===c?l=1:"middle"===c&&(l=2);l&&(d+=(E.height-(a.height||0))/l);w[m?"translateY":
"y"]=Math.round(d);this[this.placed?"animate":"attr"](w);this.placed=!0;this.alignAttr=w;return this},getBBox:function(a,b){var m,E=this.renderer,p,c=this.element,k=this.styles,h,w=this.textStr,I,l=E.cache,q=E.cacheKeys,L;b=f(b,this.rotation);p=b*d;h=c&&F.prototype.getStyle.call(c,"font-size");t(w)&&(L=w.toString(),-1===L.indexOf("\x3c")&&(L=L.replace(/[0-9]/g,"0")),L+=["",b||0,h,this.textWidth,k&&k.textOverflow].join());L&&!a&&(m=l[L]);if(!m){if(c.namespaceURI===this.SVG_NS||E.forExport){try{(I=
this.fakeTS&&function(a){n(c.querySelectorAll(".highcharts-text-outline"),function(f){f.style.display=a})})&&I("none"),m=c.getBBox?r({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight},I&&I("")}catch(ca){}if(!m||0>m.width)m={width:0,height:0}}else m=this.htmlGetBBox();E.isSVG&&(a=m.width,E=m.height,k&&"11px"===k.fontSize&&17===Math.round(E)&&(m.height=E=14),b&&(m.width=Math.abs(E*Math.sin(p))+Math.abs(a*Math.cos(p)),m.height=Math.abs(E*Math.cos(p))+Math.abs(a*Math.sin(p))));if(L&&0<m.height){for(;250<
q.length;)delete l[q.shift()];l[L]||q.push(L);l[L]=m}}return m},show:function(a){return this.attr({visibility:a?"inherit":"visible"})},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var f=this;f.animate({opacity:0},{duration:a||150,complete:function(){f.attr({y:-9999})}})},add:function(a){var f=this.renderer,b=this.element,m;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&f.buildText(this);this.added=!0;if(!a||a.handleZ||this.zIndex)m=
this.zIndexSetter();m||(a?a.element:f.box).appendChild(b);if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var f=a.parentNode;f&&f.removeChild(a)},destroy:function(){var a=this,f=a.element||{},m=a.renderer.isSVG&&"SPAN"===f.nodeName&&a.parentGroup,E=f.ownerSVGElement,p=a.clipPath;f.onclick=f.onmouseout=f.onmouseover=f.onmousemove=f.point=null;M(a);p&&E&&(n(E.querySelectorAll("[clip-path],[CLIP-PATH]"),function(a){var f=a.getAttribute("clip-path"),m=p.element.id;(-1<f.indexOf("(#"+
m+")")||-1<f.indexOf('("#'+m+'")'))&&a.removeAttribute("clip-path")}),a.clipPath=p.destroy());if(a.stops){for(E=0;E<a.stops.length;E++)a.stops[E]=a.stops[E].destroy();a.stops=null}for(a.safeRemoveChild(f);m&&m.div&&0===m.div.childNodes.length;)f=m.parentGroup,a.safeRemoveChild(m.div),delete m.div,m=f;a.alignTo&&b(a.renderer.alignedObjects,a);J(a,function(f,m){delete a[m]});return null},xGetter:function(a){"circle"===this.element.nodeName&&("x"===a?a="cx":"y"===a&&(a="cy"));return this._defaultGetter(a)},
_defaultGetter:function(a){a=f(this[a+"Value"],this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,f,m){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");this[f]!==a&&(m.setAttribute(f,a),this[f]=a)},alignSetter:function(a){this.alignValue=a;this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,f,m){this[f]=a;m.setAttribute(f,a)},titleSetter:function(a){var m=
this.element.getElementsByTagName("title")[0];m||(m=A.createElementNS(this.SVG_NS,"title"),this.element.appendChild(m));m.firstChild&&m.removeChild(m.firstChild);m.appendChild(A.createTextNode(String(f(a),"").replace(/<[^>]*>/g,"").replace(/&lt;/g,"\x3c").replace(/&gt;/g,"\x3e")))},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,f,m){"string"===typeof a?m.setAttribute(f,a):a&&this.complexColor(a,f,m)},visibilitySetter:function(a,
f,m){"inherit"===a?m.removeAttribute(f):this[f]!==a&&m.setAttribute(f,a);this[f]=a},zIndexSetter:function(a,f){var m=this.renderer,b=this.parentGroup,p=(b||m).element||m.box,c,k=this.element,h,d,m=p===m.box;c=this.added;var I;t(a)?(k.setAttribute("data-z-index",a),a=+a,this[f]===a&&(c=!1)):t(this[f])&&k.removeAttribute("data-z-index");this[f]=a;if(c){(a=this.zIndex)&&b&&(b.handleZ=!0);f=p.childNodes;for(I=f.length-1;0<=I&&!h;I--)if(b=f[I],c=b.getAttribute("data-z-index"),d=!t(c),b!==k)if(0>a&&d&&
!m&&!I)p.insertBefore(k,f[I]),h=!0;else if(E(c)<=a||d&&(!t(a)||0<=a))p.insertBefore(k,f[I+1]||null),h=!0;h||(p.insertBefore(k,f[m?3:0]||null),h=!0)}return h},_defaultSetter:function(a,f,m){m.setAttribute(f,a)}});F.prototype.yGetter=F.prototype.xGetter;F.prototype.translateXSetter=F.prototype.translateYSetter=F.prototype.rotationSetter=F.prototype.verticalAlignSetter=F.prototype.rotationOriginXSetter=F.prototype.rotationOriginYSetter=F.prototype.scaleXSetter=F.prototype.scaleYSetter=F.prototype.matrixSetter=
function(a,f){this[f]=a;this.doTransform=!0};G=a.SVGRenderer=function(){this.init.apply(this,arguments)};r(G.prototype,{Element:F,SVG_NS:Q,init:function(a,f,m,b,E,p){var c;b=this.createElement("svg").attr({version:"1.1","class":"highcharts-root"});c=b.element;a.appendChild(c);g(a,"dir","ltr");-1===a.innerHTML.indexOf("xmlns")&&g(c,"xmlns",this.SVG_NS);this.isSVG=!0;this.box=c;this.boxWrapper=b;this.alignedObjects=[];this.url=(q||w)&&A.getElementsByTagName("base").length?P.location.href.replace(/#.*?$/,
"").replace(/<[^>]*>/g,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(A.createTextNode("Created with Highstock 6.1.0-modified"));this.defs=this.createElement("defs").add();this.allowHTML=p;this.forExport=E;this.gradients={};this.cache={};this.cacheKeys=[];this.imgCount=0;this.setSize(f,m,!1);var k;q&&a.getBoundingClientRect&&(f=function(){z(a,{left:0,top:0});k=a.getBoundingClientRect();z(a,{left:Math.ceil(k.left)-k.left+"px",top:Math.ceil(k.top)-
k.top+"px"})},f(),this.unSubPixelFix=H(P,"resize",f))},definition:function(a){function f(a,E){var p;n(m(a),function(a){var m=b.createElement(a.tagName),c={};J(a,function(a,f){"tagName"!==f&&"children"!==f&&"textContent"!==f&&(c[f]=a)});m.attr(c);m.add(E||b.defs);a.textContent&&m.element.appendChild(A.createTextNode(a.textContent));f(a.children||[],m);p=m});return p}var b=this;return f(a)},isHidden:function(){return!this.boxWrapper.getBBox().width},destroy:function(){var a=this.defs;this.box=null;
this.boxWrapper=this.boxWrapper.destroy();c(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.unSubPixelFix&&this.unSubPixelFix();return this.alignedObjects=null},createElement:function(a){var f=new this.Element;f.init(this,a);return f},draw:p,getRadialAttr:function(a,f){return{cx:a[0]-a[2]/2+f.cx*a[2],cy:a[1]-a[2]/2+f.cy*a[2],r:f.r*a[2]}},getSpanWidth:function(a){return a.getBBox(!0).width},applyEllipsis:function(a,f,m,b){var E=a.rotation,p=m,c,k=0,h=m.length,d=function(a){f.removeChild(f.firstChild);
a&&f.appendChild(A.createTextNode(a))},I;a.rotation=0;p=this.getSpanWidth(a,f);if(I=p>b){for(;k<=h;)c=Math.ceil((k+h)/2),p=m.substring(0,c)+"\u2026",d(p),p=this.getSpanWidth(a,f),k===h?k=h+1:p>b?h=c-1:k=c;0===h&&d("")}a.rotation=E;return I},escapes:{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;","'":"\x26#39;",'"':"\x26quot;"},buildText:function(a){var m=a.element,b=this,p=b.forExport,c=f(a.textStr,"").toString(),k=-1!==c.indexOf("\x3c"),h=m.childNodes,d,I=g(m,"x"),w=a.styles,r=a.textWidth,L=
w&&w.lineHeight,q=w&&w.textOutline,M=w&&"ellipsis"===w.textOverflow,y=w&&"nowrap"===w.whiteSpace,D,C=h.length,t=r&&!a.added&&this.box,e=function(a){return L?E(L):b.fontMetrics(void 0,a.getAttribute("style")?a:m).h},v=function(a,f){J(b.escapes,function(m,b){f&&-1!==B(m,f)||(a=a.toString().replace(new RegExp(m,"g"),b))});return a},O=function(a,f){var m;m=a.indexOf("\x3c");a=a.substring(m,a.indexOf("\x3e")-m);m=a.indexOf(f+"\x3d");if(-1!==m&&(m=m+f.length+1,f=a.charAt(m),'"'===f||"'"===f))return a=a.substring(m+
1),a.substring(0,a.indexOf(f))},w=[c,M,y,L,q,w&&w.fontSize,r].join();if(w!==a.textCache){for(a.textCache=w;C--;)m.removeChild(h[C]);k||q||M||r||-1!==c.indexOf(" ")?(t&&t.appendChild(m),c=k?c.replace(/<(b|strong)>/g,'\x3cspan class\x3d"highcharts-strong"\x3e').replace(/<(i|em)>/g,'\x3cspan class\x3d"highcharts-emphasized"\x3e').replace(/<a/g,"\x3cspan").replace(/<\/(b|strong|i|em|a)>/g,"\x3c/span\x3e").split(/<br.*?>/g):[c],c=l(c,function(a){return""!==a}),n(c,function(f,E){var c,k=0;f=f.replace(/^\s+|\s+$/g,
"").replace(/<span/g,"|||\x3cspan").replace(/<\/span>/g,"\x3c/span\x3e|||");c=f.split("|||");n(c,function(f){if(""!==f||1===c.length){var h={},w=A.createElementNS(b.SVG_NS,"tspan"),l,L;(l=O(f,"class"))&&g(w,"class",l);if(l=O(f,"style"))l=l.replace(/(;| |^)color([ :])/,"$1fill$2"),g(w,"style",l);(L=O(f,"href"))&&!p&&(g(w,"onclick",'location.href\x3d"'+L+'"'),g(w,"class","highcharts-anchor"));f=v(f.replace(/<[a-zA-Z\/](.|\n)*?>/g,"")||" ");if(" "!==f){w.appendChild(A.createTextNode(f));k?h.dx=0:E&&
null!==I&&(h.x=I);g(w,h);m.appendChild(w);!k&&D&&(!W&&p&&z(w,{display:"block"}),g(w,"dy",e(w)));if(r){h=f.replace(/([^\^])-/g,"$1- ").split(" ");L=1<c.length||E||1<h.length&&!y;var q=[],B,C=e(w),n=a.rotation;for(M&&(d=b.applyEllipsis(a,w,f,r));!M&&L&&(h.length||q.length);)a.rotation=0,B=b.getSpanWidth(a,w),f=B>r,void 0===d&&(d=f),f&&1!==h.length?(w.removeChild(w.firstChild),q.unshift(h.pop())):(h=q,q=[],h.length&&!y&&(w=A.createElementNS(Q,"tspan"),g(w,{dy:C,x:I}),l&&g(w,"style",l),m.appendChild(w)),
B>r&&(r=B+1)),h.length&&w.appendChild(A.createTextNode(h.join(" ").replace(/- /g,"-")));a.rotation=n}k++}}});D=D||m.childNodes.length}),M&&d&&a.attr("title",v(a.textStr,["\x26lt;","\x26gt;"])),t&&t.removeChild(m),q&&a.applyTextOutline&&a.applyTextOutline(q)):m.appendChild(A.createTextNode(v(c)))}},getContrast:function(a){a=x(a).rgba;return 510<a[0]+a[1]+a[2]?"#000000":"#FFFFFF"},button:function(a,f,m,b,c,E,p,k,h){var w=this.label(a,f,m,h,null,null,null,null,"button"),d=0;w.attr(I({padding:8,r:2},
c));H(w.element,D?"mouseover":"mouseenter",function(){3!==d&&w.setState(1)});H(w.element,D?"mouseout":"mouseleave",function(){3!==d&&w.setState(d)});w.setState=function(a){1!==a&&(w.state=d=a);w.removeClass(/highcharts-button-(normal|hover|pressed|disabled)/).addClass("highcharts-button-"+["normal","hover","pressed","disabled"][a||0])};return w.on("click",function(a){3!==d&&b.call(w,a)})},crispLine:function(a,f){a[1]===a[4]&&(a[1]=a[4]=Math.round(a[1])-f%2/2);a[2]===a[5]&&(a[2]=a[5]=Math.round(a[2])+
f%2/2);return a},path:function(a){var f={};C(a)?f.d=a:y(a)&&r(f,a);return this.createElement("path").attr(f)},circle:function(a,f,m){a=y(a)?a:{x:a,y:f,r:m};f=this.createElement("circle");f.xSetter=f.ySetter=function(a,f,m){m.setAttribute("c"+f,a)};return f.attr(a)},arc:function(a,f,m,b,c,E){y(a)?(b=a,f=b.y,m=b.r,a=b.x):b={innerR:b,start:c,end:E};a=this.symbol("arc",a,f,m,m,b);a.r=m;return a},rect:function(a,f,m,b,c,E){c=y(a)?a.r:c;E=this.createElement("rect");a=y(a)?a:void 0===a?{}:{x:a,y:f,width:Math.max(m,
0),height:Math.max(b,0)};c&&(a.r=c);E.rSetter=function(a,f,m){g(m,{rx:a,ry:a})};return E.attr(a)},setSize:function(a,m,b){var c=this.alignedObjects,E=c.length;this.width=a;this.height=m;for(this.boxWrapper.animate({width:a,height:m},{step:function(){this.attr({viewBox:"0 0 "+this.attr("width")+" "+this.attr("height")})},duration:f(b,!0)?void 0:0});E--;)c[E].align()},g:function(a){var f=this.createElement("g");return a?f.attr({"class":"highcharts-"+a}):f},image:function(a,f,m,b,c,E){var p={preserveAspectRatio:"none"},
k,h=function(a,f){a.setAttributeNS?a.setAttributeNS("http://www.w3.org/1999/xlink","href",f):a.setAttribute("hc-svg-href",f)},w=function(f){h(k.element,a);E.call(k,f)};1<arguments.length&&r(p,{x:f,y:m,width:b,height:c});k=this.createElement("image").attr(p);E?(h(k.element,"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d"),p=new P.Image,H(p,"load",w),p.src=a,p.complete&&w({})):h(k.element,a);return k},symbol:function(a,m,b,c,E,p){var k=this,h,w=/^url\((.*?)\)$/,d=w.test(a),
I=!d&&(this.symbols[a]?a:"circle"),l=I&&this.symbols[I],L=t(m)&&l&&l.call(this.symbols,Math.round(m),Math.round(b),c,E,p),q,B;l?(h=this.path(L),r(h,{symbolName:I,x:m,y:b,width:c,height:E}),p&&r(h,p)):d&&(q=a.match(w)[1],h=this.image(q),h.imgwidth=f(N[q]&&N[q].width,p&&p.width),h.imgheight=f(N[q]&&N[q].height,p&&p.height),B=function(){h.attr({width:h.width,height:h.height})},n(["width","height"],function(a){h[a+"Setter"]=function(a,f){var m={},b=this["img"+f],c="width"===f?"translateX":"translateY";
this[f]=a;t(b)&&(this.element&&this.element.setAttribute(f,b),this.alignByTranslate||(m[c]=((this[f]||0)-b)/2,this.attr(m)))}}),t(m)&&h.attr({x:m,y:b}),h.isImg=!0,t(h.imgwidth)&&t(h.imgheight)?B():(h.attr({width:0,height:0}),v("img",{onload:function(){var a=e[k.chartIndex];0===this.width&&(z(this,{position:"absolute",top:"-999em"}),A.body.appendChild(this));N[q]={width:this.width,height:this.height};h.imgwidth=this.width;h.imgheight=this.height;h.element&&B();this.parentNode&&this.parentNode.removeChild(this);
k.imgCount--;if(!k.imgCount&&a&&a.onload)a.onload()},src:q}),this.imgCount++));return h},symbols:{circle:function(a,f,m,b){return this.arc(a+m/2,f+b/2,m/2,b/2,{start:0,end:2*Math.PI,open:!1})},square:function(a,f,m,b){return["M",a,f,"L",a+m,f,a+m,f+b,a,f+b,"Z"]},triangle:function(a,f,m,b){return["M",a+m/2,f,"L",a+m,f+b,a,f+b,"Z"]},"triangle-down":function(a,f,m,b){return["M",a,f,"L",a+m,f,a+m/2,f+b,"Z"]},diamond:function(a,f,m,b){return["M",a+m/2,f,"L",a+m,f+b/2,a+m/2,f+b,a,f+b/2,"Z"]},arc:function(a,
m,b,c,E){var p=E.start,k=E.r||b,h=E.r||c||b,w=E.end-.001;b=E.innerR;c=f(E.open,.001>Math.abs(E.end-E.start-2*Math.PI));var d=Math.cos(p),I=Math.sin(p),l=Math.cos(w),w=Math.sin(w);E=.001>E.end-p-Math.PI?0:1;k=["M",a+k*d,m+h*I,"A",k,h,0,E,1,a+k*l,m+h*w];t(b)&&k.push(c?"M":"L",a+b*l,m+b*w,"A",b,b,0,E,0,a+b*d,m+b*I);k.push(c?"":"Z");return k},callout:function(a,f,m,b,E){var c=Math.min(E&&E.r||0,m,b),p=c+6,k=E&&E.anchorX;E=E&&E.anchorY;var h;h=["M",a+c,f,"L",a+m-c,f,"C",a+m,f,a+m,f,a+m,f+c,"L",a+m,f+b-
c,"C",a+m,f+b,a+m,f+b,a+m-c,f+b,"L",a+c,f+b,"C",a,f+b,a,f+b,a,f+b-c,"L",a,f+c,"C",a,f,a,f,a+c,f];k&&k>m?E>f+p&&E<f+b-p?h.splice(13,3,"L",a+m,E-6,a+m+6,E,a+m,E+6,a+m,f+b-c):h.splice(13,3,"L",a+m,b/2,k,E,a+m,b/2,a+m,f+b-c):k&&0>k?E>f+p&&E<f+b-p?h.splice(33,3,"L",a,E+6,a-6,E,a,E-6,a,f+c):h.splice(33,3,"L",a,b/2,k,E,a,b/2,a,f+c):E&&E>b&&k>a+p&&k<a+m-p?h.splice(23,3,"L",k+6,f+b,k,f+b+6,k-6,f+b,a+c,f+b):E&&0>E&&k>a+p&&k<a+m-p&&h.splice(3,3,"L",k-6,f,k,f-6,k+6,f,m-c,f);return h}},clipRect:function(f,m,b,
E){var c=a.uniqueKey(),k=this.createElement("clipPath").attr({id:c}).add(this.defs);f=this.rect(f,m,b,E,0).add(k);f.id=c;f.clipPath=k;f.count=0;return f},text:function(a,f,m,b){var E={};if(b&&(this.allowHTML||!this.forExport))return this.html(a,f,m);E.x=Math.round(f||0);m&&(E.y=Math.round(m));if(a||0===a)E.text=a;a=this.createElement("text").attr(E);b||(a.xSetter=function(a,f,m){var b=m.getElementsByTagName("tspan"),E,c=m.getAttribute(f),k;for(k=0;k<b.length;k++)E=b[k],E.getAttribute(f)===c&&E.setAttribute(f,
a);m.setAttribute(f,a)});return a},fontMetrics:function(a,f){a=f&&F.prototype.getStyle.call(f,"font-size");a=/px/.test(a)?E(a):/em/.test(a)?parseFloat(a)*(f?this.fontMetrics(null,f.parentNode).f:16):12;f=24>a?a+3:Math.round(1.2*a);return{h:f,b:Math.round(.8*f),f:a}},rotCorr:function(a,f,m){var b=a;f&&m&&(b=Math.max(b*Math.cos(f*d),4));return{x:-a/3*Math.sin(f*d),y:b}},label:function(f,m,b,E,c,k,p,h,w){var d=this,l=d.g("button"!==w&&"label"),q=l.text=d.text("",0,0,p).attr({zIndex:1}),B,M,y=0,D=3,C=
0,J,A,e,W,g,z={},Q,v=/^url\((.*?)\)$/.test(E),x=v,u,N,P,O;w&&l.addClass("highcharts-"+w);x=!0;u=function(){return B.strokeWidth()%2/2};N=function(){var a=q.element.style,f={};M=(void 0===J||void 0===A||g)&&t(q.textStr)&&q.getBBox();l.width=(J||M.width||0)+2*D+C;l.height=(A||M.height||0)+2*D;Q=D+d.fontMetrics(a&&a.fontSize,q).b;x&&(B||(l.box=B=d.symbols[E]||v?d.symbol(E):d.rect(),B.addClass(("button"===w?"":"highcharts-label-box")+(w?" highcharts-"+w+"-box":"")),B.add(l),a=u(),f.x=a,f.y=(h?-Q:0)+a),
f.width=Math.round(l.width),f.height=Math.round(l.height),B.attr(r(f,z)),z={})};P=function(){var a=C+D,f;f=h?0:Q;t(J)&&M&&("center"===g||"right"===g)&&(a+={center:.5,right:1}[g]*(J-M.width));if(a!==q.x||f!==q.y)q.attr("x",a),q.hasBoxWidthChanged&&(M=q.getBBox(!0),N()),void 0!==f&&q.attr("y",f);q.x=a;q.y=f};O=function(a,f){B?B.attr(a,f):z[a]=f};l.onAdd=function(){q.add(l);l.attr({text:f||0===f?f:"",x:m,y:b});B&&t(c)&&l.attr({anchorX:c,anchorY:k})};l.widthSetter=function(f){J=a.isNumber(f)?f:null};
l.heightSetter=function(a){A=a};l["text-alignSetter"]=function(a){g=a};l.paddingSetter=function(a){t(a)&&a!==D&&(D=l.padding=a,P())};l.paddingLeftSetter=function(a){t(a)&&a!==C&&(C=a,P())};l.alignSetter=function(a){a={left:0,center:.5,right:1}[a];a!==y&&(y=a,M&&l.attr({x:e}))};l.textSetter=function(a){void 0!==a&&q.textSetter(a);N();P()};l["stroke-widthSetter"]=function(a,f){a&&(x=!0);this["stroke-width"]=a;O(f,a)};l.rSetter=function(a,f){O(f,a)};l.anchorXSetter=function(a,f){c=l.anchorX=a;O(f,Math.round(a)-
u()-e)};l.anchorYSetter=function(a,f){k=l.anchorY=a;O(f,a-W)};l.xSetter=function(a){l.x=a;y&&(a-=y*((J||M.width)+2*D),l["forceAnimate:x"]=!0);e=Math.round(a);l.attr("translateX",e)};l.ySetter=function(a){W=l.y=Math.round(a);l.attr("translateY",W)};var R=l.css;return r(l,{css:function(a){if(a){var f={};a=I(a);n(l.textProps,function(m){void 0!==a[m]&&(f[m]=a[m],delete a[m])});q.css(f);"width"in f&&N()}return R.call(l,a)},getBBox:function(){return{width:M.width+2*D,height:M.height+2*D,x:M.x-D,y:M.y-
D}},destroy:function(){L(l.element,"mouseenter");L(l.element,"mouseleave");q&&(q=q.destroy());B&&(B=B.destroy());F.prototype.destroy.call(l);l=d=N=P=O=null}})}});a.Renderer=G})(K);(function(a){var F=a.attr,G=a.createElement,H=a.css,u=a.defined,g=a.each,e=a.extend,x=a.isFirefox,z=a.isMS,v=a.isWebKit,t=a.pick,d=a.pInt,c=a.SVGRenderer,A=a.win,n=a.wrap;e(a.SVGElement.prototype,{htmlCss:function(a){var b=this.element;if(b=a&&"SPAN"===b.tagName&&a.width)delete a.width,this.textWidth=b,this.htmlUpdateTransform();
a&&"ellipsis"===a.textOverflow&&(a.whiteSpace="nowrap",a.overflow="hidden");this.styles=e(this.styles,a);H(this.element,a);return this},htmlGetBBox:function(){var a=this.element;return{x:a.offsetLeft,y:a.offsetTop,width:a.offsetWidth,height:a.offsetHeight}},htmlUpdateTransform:function(){if(this.added){var a=this.renderer,b=this.element,c=this.x||0,h=this.y||0,B=this.textAlign||"left",C={left:0,center:.5,right:1}[B],q=this.styles,D=q&&q.whiteSpace;H(b,{marginLeft:this.translateX||0,marginTop:this.translateY||
0});this.inverted&&g(b.childNodes,function(c){a.invertChild(c,b)});if("SPAN"===b.tagName){var q=this.rotation,y=this.textWidth&&d(this.textWidth),k=[q,B,b.innerHTML,this.textWidth,this.textAlign].join(),w;(w=y!==this.oldTextWidth)&&!(w=y>this.oldTextWidth)&&((w=this.textPxLength)||(H(b,{width:"",whiteSpace:D||"nowrap"}),w=b.offsetWidth),w=w>y);w&&/[ \-]/.test(b.textContent||b.innerText)?(H(b,{width:y+"px",display:"block",whiteSpace:D||"normal"}),this.oldTextWidth=y,this.hasBoxWidthChanged=!0):this.hasBoxWidthChanged=
!1;k!==this.cTT&&(D=a.fontMetrics(b.style.fontSize).b,u(q)&&q!==(this.oldRotation||0)&&this.setSpanRotation(q,C,D),this.getSpanCorrection(!u(q)&&this.textPxLength||b.offsetWidth,D,C,q,B));H(b,{left:c+(this.xCorr||0)+"px",top:h+(this.yCorr||0)+"px"});this.cTT=k;this.oldRotation=q}}else this.alignOnAdd=!0},setSpanRotation:function(a,b,c){var h={},l=this.renderer.getTransformKey();h[l]=h.transform="rotate("+a+"deg)";h[l+(x?"Origin":"-origin")]=h.transformOrigin=100*b+"% "+c+"px";H(this.element,h)},getSpanCorrection:function(a,
b,c){this.xCorr=-a*c;this.yCorr=-b}});e(c.prototype,{getTransformKey:function(){return z&&!/Edge/.test(A.navigator.userAgent)?"-ms-transform":v?"-webkit-transform":x?"MozTransform":A.opera?"-o-transform":""},html:function(a,b,c){var h=this.createElement("span"),l=h.element,d=h.renderer,q=d.isSVG,r=function(a,b){g(["opacity","visibility"],function(c){n(a,c+"Setter",function(a,c,k,f){a.call(this,c,k,f);b[k]=c})});a.addedSetters=!0};h.textSetter=function(a){a!==l.innerHTML&&delete this.bBox;this.textStr=
a;l.innerHTML=t(a,"");h.doTransform=!0};q&&r(h,h.element.style);h.xSetter=h.ySetter=h.alignSetter=h.rotationSetter=function(a,b){"align"===b&&(b="textAlign");h[b]=a;h.doTransform=!0};h.afterSetters=function(){this.doTransform&&(this.htmlUpdateTransform(),this.doTransform=!1)};h.attr({text:a,x:Math.round(b),y:Math.round(c)}).css({position:"absolute"});l.style.whiteSpace="nowrap";h.css=h.htmlCss;q&&(h.add=function(a){var b,c=d.box.parentNode,I=[];if(this.parentGroup=a){if(b=a.div,!b){for(;a;)I.push(a),
a=a.parentGroup;g(I.reverse(),function(a){function k(b,m){a[m]=b;"translateX"===m?f.left=b+"px":f.top=b+"px";a.doTransform=!0}var f,E=F(a.element,"class");E&&(E={className:E});b=a.div=a.div||G("div",E,{position:"absolute",left:(a.translateX||0)+"px",top:(a.translateY||0)+"px",display:a.display,opacity:a.opacity,pointerEvents:a.styles&&a.styles.pointerEvents},b||c);f=b.style;e(a,{classSetter:function(a){return function(f){this.element.setAttribute("class",f);a.className=f}}(b),on:function(){I[0].div&&
h.on.apply({element:I[0].div},arguments);return a},translateXSetter:k,translateYSetter:k});a.addedSetters||r(a,f)})}}else b=c;b.appendChild(l);h.added=!0;h.alignOnAdd&&h.htmlUpdateTransform();return h});return h}})})(K);(function(a){var F=a.defined,G=a.each,H=a.extend,u=a.merge,g=a.pick,e=a.timeUnits,x=a.win;a.Time=function(a){this.update(a,!1)};a.Time.prototype={defaultOptions:{},update:function(e){var v=g(e&&e.useUTC,!0),t=this;this.options=e=u(!0,this.options||{},e);this.Date=e.Date||x.Date;this.timezoneOffset=
(this.useUTC=v)&&e.timezoneOffset;this.getTimezoneOffset=this.timezoneOffsetFunction();(this.variableTimezone=!(v&&!e.getTimezoneOffset&&!e.timezone))||this.timezoneOffset?(this.get=function(a,c){var d=c.getTime(),n=d-t.getTimezoneOffset(c);c.setTime(n);a=c["getUTC"+a]();c.setTime(d);return a},this.set=function(d,c,A){var n;if(-1!==a.inArray(d,["Milliseconds","Seconds","Minutes"]))c["set"+d](A);else n=t.getTimezoneOffset(c),n=c.getTime()-n,c.setTime(n),c["setUTC"+d](A),d=t.getTimezoneOffset(c),n=
c.getTime()+d,c.setTime(n)}):v?(this.get=function(a,c){return c["getUTC"+a]()},this.set=function(a,c,t){return c["setUTC"+a](t)}):(this.get=function(a,c){return c["get"+a]()},this.set=function(a,c,t){return c["set"+a](t)})},makeTime:function(e,v,t,d,c,A){var n,r,b;this.useUTC?(n=this.Date.UTC.apply(0,arguments),r=this.getTimezoneOffset(n),n+=r,b=this.getTimezoneOffset(n),r!==b?n+=b-r:r-36E5!==this.getTimezoneOffset(n-36E5)||a.isSafari||(n-=36E5)):n=(new this.Date(e,v,g(t,1),g(d,0),g(c,0),g(A,0))).getTime();
return n},timezoneOffsetFunction:function(){var e=this,g=this.options,t=x.moment;if(!this.useUTC)return function(a){return 6E4*(new Date(a)).getTimezoneOffset()};if(g.timezone){if(t)return function(a){return 6E4*-t.tz(a,g.timezone).utcOffset()};a.error(25)}return this.useUTC&&g.getTimezoneOffset?function(a){return 6E4*g.getTimezoneOffset(a)}:function(){return 6E4*(e.timezoneOffset||0)}},dateFormat:function(e,g,t){if(!a.defined(g)||isNaN(g))return a.defaultOptions.lang.invalidDate||"";e=a.pick(e,"%Y-%m-%d %H:%M:%S");
var d=this,c=new this.Date(g),A=this.get("Hours",c),n=this.get("Day",c),r=this.get("Date",c),b=this.get("Month",c),l=this.get("FullYear",c),h=a.defaultOptions.lang,B=h.weekdays,C=h.shortWeekdays,q=a.pad,c=a.extend({a:C?C[n]:B[n].substr(0,3),A:B[n],d:q(r),e:q(r,2," "),w:n,b:h.shortMonths[b],B:h.months[b],m:q(b+1),o:b+1,y:l.toString().substr(2,2),Y:l,H:q(A),k:A,I:q(A%12||12),l:A%12||12,M:q(d.get("Minutes",c)),p:12>A?"AM":"PM",P:12>A?"am":"pm",S:q(c.getSeconds()),L:q(Math.round(g%1E3),3)},a.dateFormats);
a.objectEach(c,function(a,b){for(;-1!==e.indexOf("%"+b);)e=e.replace("%"+b,"function"===typeof a?a.call(d,g):a)});return t?e.substr(0,1).toUpperCase()+e.substr(1):e},getTimeTicks:function(a,v,t,d){var c=this,A=[],n={},r,b=new c.Date(v),l=a.unitRange,h=a.count||1,B;if(F(v)){c.set("Milliseconds",b,l>=e.second?0:h*Math.floor(c.get("Milliseconds",b)/h));l>=e.second&&c.set("Seconds",b,l>=e.minute?0:h*Math.floor(c.get("Seconds",b)/h));l>=e.minute&&c.set("Minutes",b,l>=e.hour?0:h*Math.floor(c.get("Minutes",
b)/h));l>=e.hour&&c.set("Hours",b,l>=e.day?0:h*Math.floor(c.get("Hours",b)/h));l>=e.day&&c.set("Date",b,l>=e.month?1:h*Math.floor(c.get("Date",b)/h));l>=e.month&&(c.set("Month",b,l>=e.year?0:h*Math.floor(c.get("Month",b)/h)),r=c.get("FullYear",b));l>=e.year&&c.set("FullYear",b,r-r%h);l===e.week&&c.set("Date",b,c.get("Date",b)-c.get("Day",b)+g(d,1));r=c.get("FullYear",b);d=c.get("Month",b);var C=c.get("Date",b),q=c.get("Hours",b);v=b.getTime();c.variableTimezone&&(B=t-v>4*e.month||c.getTimezoneOffset(v)!==
c.getTimezoneOffset(t));b=b.getTime();for(v=1;b<t;)A.push(b),b=l===e.year?c.makeTime(r+v*h,0):l===e.month?c.makeTime(r,d+v*h):!B||l!==e.day&&l!==e.week?B&&l===e.hour&&1<h?c.makeTime(r,d,C,q+v*h):b+l*h:c.makeTime(r,d,C+v*h*(l===e.day?1:7)),v++;A.push(b);l<=e.hour&&1E4>A.length&&G(A,function(a){0===a%18E5&&"000000000"===c.dateFormat("%H%M%S%L",a)&&(n[a]="day")})}A.info=H(a,{higherRanks:n,totalRange:l*h});return A}}})(K);(function(a){var F=a.merge;a.defaultOptions={symbols:["circle","diamond","square",
"triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:" "},global:{},time:a.Time.prototype.defaultOptions,chart:{borderRadius:0,
colorCount:10,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],resetZoomButton:{theme:{zIndex:6},position:{align:"right",x:-10,y:10}},width:null,height:null},title:{text:"Chart title",align:"center",margin:15,widthAdjust:-44},subtitle:{text:"",align:"center",widthAdjust:-44},plotOptions:{},labels:{style:{position:"absolute",color:"#333333"}},legend:{enabled:!0,align:"center",alignColumns:!0,layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#999999",borderRadius:0,
navigation:{},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},squareSymbol:!0,symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{}},loading:{},tooltip:{enabled:!0,animation:a.svg,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},footerFormat:"",padding:8,snap:a.isTouchDevice?25:10,headerFormat:'\x3cspan class\x3d"highcharts-header"\x3e{point.key}\x3c/span\x3e\x3cbr/\x3e',
pointFormat:'\x3cspan class\x3d"highcharts-color-{point.colorIndex}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cspan class\x3d"highcharts-strong"\x3e{point.y}\x3c/span\x3e\x3cbr/\x3e'},credits:{enabled:!0,href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},text:"Highcharts.com"}};a.setOptions=function(G){a.defaultOptions=F(!0,a.defaultOptions,G);a.time.update(F(a.defaultOptions.global,a.defaultOptions.time),!1);return a.defaultOptions};a.getOptions=function(){return a.defaultOptions};
a.defaultPlotOptions=a.defaultOptions.plotOptions;a.time=new a.Time(F(a.defaultOptions.global,a.defaultOptions.time));a.dateFormat=function(G,F,u){return a.time.dateFormat(G,F,u)}})(K);(function(a){var F=a.correctFloat,G=a.defined,H=a.destroyObjectProperties,u=a.fireEvent,g=a.isNumber,e=a.pick,x=a.deg2rad;a.Tick=function(a,e,t,d){this.axis=a;this.pos=e;this.type=t||"";this.isNewLabel=this.isNew=!0;t||d||this.addLabel()};a.Tick.prototype={addLabel:function(){var a=this.axis,g=a.options,t=a.chart,d=
a.categories,c=a.names,A=this.pos,n=g.labels,r=a.tickPositions,b=A===r[0],l=A===r[r.length-1],c=d?e(d[A],c[A],A):A,d=this.label,r=r.info,h;a.isDatetimeAxis&&r&&(h=g.dateTimeLabelFormats[r.higherRanks[A]||r.unitName]);this.isFirst=b;this.isLast=l;g=a.labelFormatter.call({axis:a,chart:t,isFirst:b,isLast:l,dateTimeLabelFormat:h,value:a.isLog?F(a.lin2log(c)):c,pos:A});if(G(d))d&&d.attr({text:g});else{if(this.label=d=G(g)&&n.enabled?t.renderer.text(g,0,0,n.useHTML).add(a.labelGroup):null)d.textPxLength=
d.getBBox().width;this.rotation=0}},getLabelSize:function(){return this.label?this.label.getBBox()[this.axis.horiz?"height":"width"]:0},handleOverflow:function(a){var g=this.axis,t=g.options.labels,d=a.x,c=g.chart.chartWidth,A=g.chart.spacing,n=e(g.labelLeft,Math.min(g.pos,A[3])),A=e(g.labelRight,Math.max(g.isRadial?0:g.pos+g.len,c-A[1])),r=this.label,b=this.rotation,l={left:0,center:.5,right:1}[g.labelAlign||r.attr("align")],h=r.getBBox().width,B=g.getSlotWidth(this),C=B,q=1,D,y={};if(b||!1===t.overflow)0>
b&&d-l*h<n?D=Math.round(d/Math.cos(b*x)-n):0<b&&d+l*h>A&&(D=Math.round((c-d)/Math.cos(b*x)));else if(c=d+(1-l)*h,d-l*h<n?C=a.x+C*(1-l)-n:c>A&&(C=A-a.x+C*l,q=-1),C=Math.min(B,C),C<B&&"center"===g.labelAlign&&(a.x+=q*(B-C-l*(B-Math.min(h,C)))),h>C||g.autoRotation&&(r.styles||{}).width)D=C;D&&(y.width=D,(t.style||{}).textOverflow||(y.textOverflow="ellipsis"),r.css(y))},getPosition:function(e,g,t,d){var c=this.axis,A=c.chart,n=d&&A.oldChartHeight||A.chartHeight;e={x:e?a.correctFloat(c.translate(g+t,null,
null,d)+c.transB):c.left+c.offset+(c.opposite?(d&&A.oldChartWidth||A.chartWidth)-c.right-c.left:0),y:e?n-c.bottom+c.offset-(c.opposite?c.height:0):a.correctFloat(n-c.translate(g+t,null,null,d)-c.transB)};u(this,"afterGetPosition",{pos:e});return e},getLabelPosition:function(a,e,t,d,c,A,n,r){var b=this.axis,l=b.transA,h=b.reversed,B=b.staggerLines,C=b.tickRotCorr||{x:0,y:0},q=c.y,D=d||b.reserveSpaceDefault?0:-b.labelOffset*("center"===b.labelAlign?.5:1),y={};G(q)||(q=0===b.side?t.rotation?-8:-t.getBBox().height:
2===b.side?C.y+8:Math.cos(t.rotation*x)*(C.y-t.getBBox(!1,0).height/2));a=a+c.x+D+C.x-(A&&d?A*l*(h?-1:1):0);e=e+q-(A&&!d?A*l*(h?1:-1):0);B&&(t=n/(r||1)%B,b.opposite&&(t=B-t-1),e+=b.labelOffset/B*t);y.x=a;y.y=Math.round(e);u(this,"afterGetLabelPosition",{pos:y});return y},getMarkPath:function(a,e,t,d,c,A){return A.crispLine(["M",a,e,"L",a+(c?0:-t),e+(c?t:0)],d)},renderGridLine:function(a,e,t){var d=this.axis,c=this.gridLine,A={},n=this.pos,r=this.type,b=d.tickmarkOffset,l=d.chart.renderer;c||(r||(A.zIndex=
1),a&&(A.opacity=0),this.gridLine=c=l.path().attr(A).addClass("highcharts-"+(r?r+"-":"")+"grid-line").add(d.gridGroup));if(!a&&c&&(a=d.getPlotLinePath(n+b,c.strokeWidth()*t,a,!0)))c[this.isNew?"attr":"animate"]({d:a,opacity:e})},renderMark:function(a,e,t){var d=this.axis,c=d.chart.renderer,A=this.type,n=d.tickSize(A?A+"Tick":"tick"),r=this.mark,b=!r,l=a.x;a=a.y;n&&(d.opposite&&(n[0]=-n[0]),b&&(this.mark=r=c.path().addClass("highcharts-"+(A?A+"-":"")+"tick").add(d.axisGroup)),r[b?"attr":"animate"]({d:this.getMarkPath(l,
a,n[0],r.strokeWidth()*t,d.horiz,c),opacity:e}))},renderLabel:function(a,x,t,d){var c=this.axis,A=c.horiz,n=c.options,r=this.label,b=n.labels,l=b.step,c=c.tickmarkOffset,h=!0,B=a.x;a=a.y;r&&g(B)&&(r.xy=a=this.getLabelPosition(B,a,r,A,b,c,d,l),this.isFirst&&!this.isLast&&!e(n.showFirstLabel,1)||this.isLast&&!this.isFirst&&!e(n.showLastLabel,1)?h=!1:!A||b.step||b.rotation||x||0===t||this.handleOverflow(a),l&&d%l&&(h=!1),h&&g(a.y)?(a.opacity=t,r[this.isNewLabel?"attr":"animate"](a),this.isNewLabel=!1):
(r.attr("y",-9999),this.isNewLabel=!0))},render:function(g,x,t){var d=this.axis,c=d.horiz,A=this.getPosition(c,this.pos,d.tickmarkOffset,x),n=A.x,r=A.y,d=c&&n===d.pos+d.len||!c&&r===d.pos?-1:1;t=e(t,1);this.isActive=!0;this.renderGridLine(x,t,d);this.renderMark(A,t,d);this.renderLabel(A,x,t,g);this.isNew=!1;a.fireEvent(this,"afterRender")},destroy:function(){H(this,this.axis)}}})(K);var ba=function(a){var F=a.addEvent,G=a.animObject,H=a.arrayMax,u=a.arrayMin,g=a.correctFloat,e=a.defaultOptions,x=
a.defined,z=a.deg2rad,v=a.destroyObjectProperties,t=a.each,d=a.extend,c=a.fireEvent,A=a.format,n=a.getMagnitude,r=a.grep,b=a.inArray,l=a.isArray,h=a.isNumber,B=a.isString,C=a.merge,q=a.normalizeTickInterval,D=a.objectEach,y=a.pick,k=a.removeEvent,w=a.splat,I=a.syncTimeout,p=a.Tick,J=function(){this.init.apply(this,arguments)};a.extend(J.prototype,{defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",
year:"%Y"},endOnTick:!1,labels:{enabled:!0,x:0},maxPadding:.01,minorTickLength:2,minorTickPosition:"outside",minPadding:.01,startOfWeek:1,startOnTick:!1,tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",title:{align:"middle"},type:"linear"},defaultYAxisOptions:{endOnTick:!0,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8},maxPadding:.05,minPadding:.05,startOnTick:!0,title:{rotation:270,text:"Values"},stackLabels:{allowOverlap:!1,enabled:!1,formatter:function(){return a.numberFormat(this.total,
-1)}}},defaultLeftAxisOptions:{labels:{x:-15},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15},title:{rotation:90}},defaultBottomAxisOptions:{labels:{autoRotation:[-45],x:0},title:{rotation:0}},defaultTopAxisOptions:{labels:{autoRotation:[-45],x:0},title:{rotation:0}},init:function(a,E){var f=E.isX,m=this;m.chart=a;m.horiz=a.inverted&&!m.isZAxis?!f:f;m.isXAxis=f;m.coll=m.coll||(f?"xAxis":"yAxis");c(this,"init",{userOptions:E});m.opposite=E.opposite;m.side=E.side||(m.horiz?m.opposite?0:
2:m.opposite?1:3);m.setOptions(E);var k=this.options,p=k.type;m.labelFormatter=k.labels.formatter||m.defaultLabelFormatter;m.userOptions=E;m.minPixelPadding=0;m.reversed=k.reversed;m.visible=!1!==k.visible;m.zoomEnabled=!1!==k.zoomEnabled;m.hasNames="category"===p||!0===k.categories;m.categories=k.categories||m.hasNames;m.names||(m.names=[],m.names.keys={});m.plotLinesAndBandsGroups={};m.isLog="logarithmic"===p;m.isDatetimeAxis="datetime"===p;m.positiveValuesOnly=m.isLog&&!m.allowNegativeLog;m.isLinked=
x(k.linkedTo);m.ticks={};m.labelEdge=[];m.minorTicks={};m.plotLinesAndBands=[];m.alternateBands={};m.len=0;m.minRange=m.userMinRange=k.minRange||k.maxZoom;m.range=k.range;m.offset=k.offset||0;m.stacks={};m.oldStacks={};m.stacksTouched=0;m.max=null;m.min=null;m.crosshair=y(k.crosshair,w(a.options.tooltip.crosshairs)[f?0:1],!1);E=m.options.events;-1===b(m,a.axes)&&(f?a.axes.splice(a.xAxis.length,0,m):a.axes.push(m),a[m.coll].push(m));m.series=m.series||[];a.inverted&&!m.isZAxis&&f&&void 0===m.reversed&&
(m.reversed=!0);D(E,function(a,f){F(m,f,a)});m.lin2log=k.linearToLogConverter||m.lin2log;m.isLog&&(m.val2lin=m.log2lin,m.lin2val=m.lin2log);c(this,"afterInit")},setOptions:function(a){this.options=C(this.defaultOptions,"yAxis"===this.coll&&this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],C(e[this.coll],a));c(this,"afterSetOptions",{userOptions:a})},defaultLabelFormatter:function(){var f=this.axis,
b=this.value,c=f.chart.time,m=f.categories,k=this.dateTimeLabelFormat,p=e.lang,h=p.numericSymbols,p=p.numericSymbolMagnitude||1E3,w=h&&h.length,l,d=f.options.labels.format,f=f.isLog?Math.abs(b):f.tickInterval;if(d)l=A(d,this,c);else if(m)l=b;else if(k)l=c.dateFormat(k,b);else if(w&&1E3<=f)for(;w--&&void 0===l;)c=Math.pow(p,w+1),f>=c&&0===10*b%c&&null!==h[w]&&0!==b&&(l=a.numberFormat(b/c,-1)+h[w]);void 0===l&&(l=1E4<=Math.abs(b)?a.numberFormat(b,-1):a.numberFormat(b,-1,void 0,""));return l},getSeriesExtremes:function(){var a=
this,b=a.chart;c(this,"getSeriesExtremes",null,function(){a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.threshold=null;a.softThreshold=!a.isXAxis;a.buildStacks&&a.buildStacks();t(a.series,function(f){if(f.visible||!b.options.chart.ignoreHiddenSeries){var m=f.options,c=m.threshold,E;a.hasVisibleSeries=!0;a.positiveValuesOnly&&0>=c&&(c=null);if(a.isXAxis)m=f.xData,m.length&&(f=u(m),E=H(m),h(f)||f instanceof Date||(m=r(m,h),f=u(m),E=H(m)),m.length&&(a.dataMin=Math.min(y(a.dataMin,m[0],f),f),a.dataMax=
Math.max(y(a.dataMax,m[0],E),E)));else if(f.getExtremes(),E=f.dataMax,f=f.dataMin,x(f)&&x(E)&&(a.dataMin=Math.min(y(a.dataMin,f),f),a.dataMax=Math.max(y(a.dataMax,E),E)),x(c)&&(a.threshold=c),!m.softThreshold||a.positiveValuesOnly)a.softThreshold=!1}})});c(this,"afterGetSeriesExtremes")},translate:function(a,b,c,m,k,p){var f=this.linkedParent||this,E=1,w=0,l=m?f.oldTransA:f.transA;m=m?f.oldMin:f.min;var d=f.minPixelPadding;k=(f.isOrdinal||f.isBroken||f.isLog&&k)&&f.lin2val;l||(l=f.transA);c&&(E*=
-1,w=f.len);f.reversed&&(E*=-1,w-=E*(f.sector||f.len));b?(a=(a*E+w-d)/l+m,k&&(a=f.lin2val(a))):(k&&(a=f.val2lin(a)),a=h(m)?E*(a-m)*l+w+E*d+(h(p)?l*p:0):void 0);return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,m,k){var f=this.chart,E=this.left,p=this.top,w,l,d=c&&f.oldChartHeight||f.chartHeight,I=c&&f.oldChartWidth||f.chartWidth,q;w=this.transB;
var r=function(a,f,b){if(a<f||a>b)m?a=Math.min(Math.max(f,a),b):q=!0;return a};k=y(k,this.translate(a,null,null,c));k=Math.min(Math.max(-1E5,k),1E5);a=c=Math.round(k+w);w=l=Math.round(d-k-w);h(k)?this.horiz?(w=p,l=d-this.bottom,a=c=r(a,E,E+this.width)):(a=E,c=I-this.right,w=l=r(w,p,p+this.height)):(q=!0,m=!1);return q&&!m?null:f.renderer.crispLine(["M",a,w,"L",c,l],b||1)},getLinearTickPositions:function(a,b,c){var f,E=g(Math.floor(b/a)*a);c=g(Math.ceil(c/a)*a);var k=[],p;g(E+a)===E&&(p=20);if(this.single)return[b];
for(b=E;b<=c;){k.push(b);b=g(b+a,p);if(b===f)break;f=b}return k},getMinorTickInterval:function(){var a=this.options;return!0===a.minorTicks?y(a.minorTickInterval,"auto"):!1===a.minorTicks?null:a.minorTickInterval},getMinorTickPositions:function(){var a=this,b=a.options,c=a.tickPositions,m=a.minorTickInterval,k=[],p=a.pointRangePadding||0,h=a.min-p,p=a.max+p,w=p-h;if(w&&w/m<a.len/3)if(a.isLog)t(this.paddedTicks,function(f,b,c){b&&k.push.apply(k,a.getLogTickPositions(m,c[b-1],c[b],!0))});else if(a.isDatetimeAxis&&
"auto"===this.getMinorTickInterval())k=k.concat(a.getTimeTicks(a.normalizeTimeTickInterval(m),h,p,b.startOfWeek));else for(b=h+(c[0]-h)%m;b<=p&&b!==k[0];b+=m)k.push(b);0!==k.length&&a.trimTicks(k);return k},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,m,k,p,h,w,l,d,I;this.isXAxis&&void 0===this.minRange&&!this.isLog&&(x(a.min)||x(a.max)?this.minRange=null:(t(this.series,function(a){l=a.xData;for(h=d=a.xIncrement?1:l.length-1;0<h;h--)if(w=l[h]-l[h-1],void 0===p||w<p)p=w}),
this.minRange=Math.min(5*p,this.dataMax-this.dataMin)));c-b<this.minRange&&(k=this.dataMax-this.dataMin>=this.minRange,I=this.minRange,m=(I-c+b)/2,m=[b-m,y(a.min,b-m)],k&&(m[2]=this.isLog?this.log2lin(this.dataMin):this.dataMin),b=H(m),c=[b+I,y(a.max,b+I)],k&&(c[2]=this.isLog?this.log2lin(this.dataMax):this.dataMax),c=u(c),c-b<I&&(m[0]=c-I,m[1]=y(a.min,c-I),b=H(m)));this.min=b;this.max=c},getClosest:function(){var a;this.categories?a=1:t(this.series,function(f){var b=f.closestPointRange,m=f.visible||
!f.chart.options.chart.ignoreHiddenSeries;!f.noSharedTooltip&&x(b)&&m&&(a=x(a)?Math.min(a,b):b)});return a},nameToX:function(a){var f=l(this.categories),c=f?this.categories:this.names,m=a.options.x,k;a.series.requireSorting=!1;x(m)||(m=!1===this.options.uniqueNames?a.series.autoIncrement():f?b(a.name,c):y(c.keys[a.name],-1));-1===m?f||(k=c.length):k=m;void 0!==k&&(this.names[k]=a.name,this.names.keys[a.name]=k);return k},updateNames:function(){var f=this,b=this.names;0<b.length&&(t(a.keys(b.keys),
function(a){delete b.keys[a]}),b.length=0,this.minRange=this.userMinRange,t(this.series||[],function(a){a.xIncrement=null;if(!a.points||a.isDirtyData)a.processData(),a.generatePoints();t(a.points,function(b,c){var m;b.options&&(m=f.nameToX(b),void 0!==m&&m!==b.x&&(b.x=m,a.xData[c]=m))})}))},setAxisTranslation:function(a){var f=this,b=f.max-f.min,m=f.axisPointRange||0,k,p=0,h=0,w=f.linkedParent,l=!!f.categories,d=f.transA,I=f.isXAxis;if(I||l||m)k=f.getClosest(),w?(p=w.minPointOffset,h=w.pointRangePadding):
t(f.series,function(a){var b=l?1:I?y(a.options.pointRange,k,0):f.axisPointRange||0;a=a.options.pointPlacement;m=Math.max(m,b);f.single||(p=Math.max(p,B(a)?0:b/2),h=Math.max(h,"on"===a?0:b))}),w=f.ordinalSlope&&k?f.ordinalSlope/k:1,f.minPointOffset=p*=w,f.pointRangePadding=h*=w,f.pointRange=Math.min(m,b),I&&(f.closestPointRange=k);a&&(f.oldTransA=d);f.translationSlope=f.transA=d=f.options.staticScale||f.len/(b+h||1);f.transB=f.horiz?f.left:f.bottom;f.minPixelPadding=d*p;c(this,"afterSetAxisTranslation")},
minFromRange:function(){return this.max-this.range},setTickInterval:function(f){var b=this,k=b.chart,m=b.options,p=b.isLog,w=b.isDatetimeAxis,l=b.isXAxis,d=b.isLinked,I=m.maxPadding,r=m.minPadding,B=m.tickInterval,D=m.tickPixelInterval,C=b.categories,e=h(b.threshold)?b.threshold:null,J=b.softThreshold,A,v,u,z;w||C||d||this.getTickAmount();u=y(b.userMin,m.min);z=y(b.userMax,m.max);d?(b.linkedParent=k[b.coll][m.linkedTo],k=b.linkedParent.getExtremes(),b.min=y(k.min,k.dataMin),b.max=y(k.max,k.dataMax),
m.type!==b.linkedParent.options.type&&a.error(11,1)):(!J&&x(e)&&(b.dataMin>=e?(A=e,r=0):b.dataMax<=e&&(v=e,I=0)),b.min=y(u,A,b.dataMin),b.max=y(z,v,b.dataMax));p&&(b.positiveValuesOnly&&!f&&0>=Math.min(b.min,y(b.dataMin,b.min))&&a.error(10,1),b.min=g(b.log2lin(b.min),15),b.max=g(b.log2lin(b.max),15));b.range&&x(b.max)&&(b.userMin=b.min=u=Math.max(b.dataMin,b.minFromRange()),b.userMax=z=b.max,b.range=null);c(b,"foundExtremes");b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(C||b.axisPointRange||
b.usePercentage||d)&&x(b.min)&&x(b.max)&&(k=b.max-b.min)&&(!x(u)&&r&&(b.min-=k*r),!x(z)&&I&&(b.max+=k*I));h(m.softMin)&&!h(b.userMin)&&(b.min=Math.min(b.min,m.softMin));h(m.softMax)&&!h(b.userMax)&&(b.max=Math.max(b.max,m.softMax));h(m.floor)&&(b.min=Math.max(b.min,m.floor));h(m.ceiling)&&(b.max=Math.min(b.max,m.ceiling));J&&x(b.dataMin)&&(e=e||0,!x(u)&&b.min<e&&b.dataMin>=e?b.min=e:!x(z)&&b.max>e&&b.dataMax<=e&&(b.max=e));b.tickInterval=b.min===b.max||void 0===b.min||void 0===b.max?1:d&&!B&&D===
b.linkedParent.options.tickPixelInterval?B=b.linkedParent.tickInterval:y(B,this.tickAmount?(b.max-b.min)/Math.max(this.tickAmount-1,1):void 0,C?1:(b.max-b.min)*D/Math.max(b.len,D));l&&!f&&t(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&!B&&(b.tickInterval=Math.max(b.pointRange,b.tickInterval));f=
y(m.minTickInterval,b.isDatetimeAxis&&b.closestPointRange);!B&&b.tickInterval<f&&(b.tickInterval=f);w||p||B||(b.tickInterval=q(b.tickInterval,null,n(b.tickInterval),y(m.allowDecimals,!(.5<b.tickInterval&&5>b.tickInterval&&1E3<b.max&&9999>b.max)),!!this.tickAmount));this.tickAmount||(b.tickInterval=b.unsquish());this.setTickPositions()},setTickPositions:function(){var a=this.options,b,k=a.tickPositions;b=this.getMinorTickInterval();var m=a.tickPositioner,p=a.startOnTick,h=a.endOnTick;this.tickmarkOffset=
this.categories&&"between"===a.tickmarkPlacement&&1===this.tickInterval?.5:0;this.minorTickInterval="auto"===b&&this.tickInterval?this.tickInterval/5:b;this.single=this.min===this.max&&x(this.min)&&!this.tickAmount&&(parseInt(this.min,10)===this.min||!1!==a.allowDecimals);this.tickPositions=b=k&&k.slice();!b&&(b=this.isDatetimeAxis?this.getTimeTicks(this.normalizeTimeTickInterval(this.tickInterval,a.units),this.min,this.max,a.startOfWeek,this.ordinalPositions,this.closestPointRange,!0):this.is