/*
 Highcharts JS v6.1.0-modified (2018-06-15)

 (c) 2016 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(E){"object"===typeof module&&module.exports?module.exports=E:E(Highcharts)})(function(E){var O=function(){return function(b){var A=this,l=A.graphic,d=b.animate,t=b.attr,m=b.onComplete,H=b.css,D=b.group,k=b.renderer,u=b.shapeArgs;b=b.shapeType;A.shouldDraw()?(l||(A.graphic=l=k[b](u).add(D)),l.css(H).attr(t).animate(d,void 0,m)):l&&l.animate(d,void 0,function(){A.graphic=l=l.destroy();"function"===typeof m&&m()});l&&l.addClass(A.getClassName(),!0)}}(),N=function(b){var A=b.each,l=b.extend,
d=b.isArray,t=b.isObject,m=b.isNumber,H=b.merge,D=b.pick,k=b.reduce;return{getColor:function(u,d){var w=d.index,n=d.mapOptionsToLevel,l=d.parentColor,B=d.parentColorIndex,y=d.series,x=d.colors,m=d.siblings,q=y.points,k,G,t,A;if(u){q=q[u.i];u=n[u.level]||{};if(k=q&&u.colorByPoint)t=q.index%(x?x.length:y.chart.options.chart.colorCount),G=x&&x[t];x=q&&q.options.color;k=u&&u.color;if(n=l)n=(n=u&&u.colorVariation)&&"brightness"===n.key?b.color(l).brighten(w/m*n.to).get():l;k=D(x,k,G,n,y.color);A=D(q&&
q.options.colorIndex,u&&u.colorIndex,t,B,d.colorIndex)}return{color:k,colorIndex:A}},getLevelOptions:function(b){var G=null,w,n,F,B;if(t(b))for(G={},F=m(b.from)?b.from:1,B=b.levels,n={},w=t(b.defaults)?b.defaults:{},d(B)&&(n=k(B,function(b,d){var n,q;t(d)&&m(d.level)&&(q=H({},d),n="boolean"===typeof q.levelIsConstant?q.levelIsConstant:w.levelIsConstant,delete q.levelIsConstant,delete q.level,d=d.level+(n?0:F-1),t(b[d])?l(b[d],q):b[d]=q);return b},{})),B=m(b.to)?b.to:1,b=0;b<=B;b++)G[b]=H({},w,t(n[b])?
n[b]:{});return G},setTreeValues:function G(b,d){var k=d.before,m=d.idRoot,t=d.mapIdToNode[m],x=d.points[b.i],w=x&&x.options||{},q=0,n=[];l(b,{levelDynamic:b.level-(("boolean"===typeof d.levelIsConstant?d.levelIsConstant:1)?0:t.level),name:D(x&&x.name,""),visible:m===b.id||("boolean"===typeof d.visible?d.visible:!1)});"function"===typeof k&&(b=k(b,d));A(b.children,function(k,m){var t=l({},d);l(t,{index:m,siblings:b.children.length,visible:b.visible});k=G(k,t);n.push(k);k.visible&&(q+=k.val)});b.visible=
0<q||b.visible;k=D(w.value,q);l(b,{children:n,childrenTotal:q,isLeaf:b.visible&&!q,val:k});return b},updateRootId:function(b){var d;t(b)&&(d=t(b.options)?b.options:{},d=D(b.rootNode,d.rootId,""),t(b.userOptions)&&(b.userOptions.rootId=d),b.rootNode=d);return d}}}(E);(function(b,A){var l=b.seriesType,d=b.seriesTypes,t=b.map,m=b.merge,H=b.extend,D=b.noop,k=b.each,u=A.getColor,G=A.getLevelOptions,w=b.grep,n=b.isNumber,F=b.isObject,B=b.isString,y=b.pick,x=b.Series,E=b.stableSort,q=b.Color,M=function(a,
e,c){c=c||this;b.objectEach(a,function(p,f){e.call(c,p,f,a)})},K=b.reduce,J=function(a,e,c){c=c||this;a=e.call(c,a);!1!==a&&J(a,e,c)},L=A.updateRootId;l("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",
alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:d&&d.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],axisTypes:d&&d.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:D,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",translateColors:d&&d.heatmap&&d.heatmap.prototype.translateColors,
colorAttribs:d&&d.heatmap&&d.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,e){a=K(a||[],function(c,a,e){a=y(a.parent,"");void 0===c[a]&&(c[a]=[]);c[a].push(e);return c},{});M(a,function(a,p,f){""!==p&&-1===b.inArray(p,e)&&(k(a,function(a){f[""].push(a)}),delete f[p])});return a},getTree:function(){var a=t(this.data,function(a){return a.id}),a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},init:function(a,
e){x.prototype.init.call(this,a,e);this.options.allowDrillToNode&&b.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(a,e,c,p,b){var f=this,d=[],g=f.points[e],r=0,z;k(p[a]||[],function(e){z=f.buildNode(f.points[e].id,e,c+1,p,a);r=Math.max(z.height+1,r);d.push(z)});e={id:a,i:e,children:d,height:r,level:c,parent:b,visible:!1};f.nodeMap[e.id]=e;g&&(g.node=e);return e},setTreeValues:function(a){var e=this,c=e.options,b=e.nodeMap[e.rootNode],c="boolean"===typeof c.levelIsConstant?c.levelIsConstant:
!0,f=0,I=[],d,g=e.points[a.i];k(a.children,function(a){a=e.setTreeValues(a);I.push(a);a.ignore||(f+=a.val)});E(I,function(a,c){return a.sortIndex-c.sortIndex});d=y(g&&g.options.value,f);g&&(g.value=d);H(a,{children:I,childrenTotal:f,ignore:!(y(g&&g.visible,!0)&&0<d),isLeaf:a.visible&&!f,levelDynamic:a.level-(c?0:b.level),name:y(g&&g.name,""),sortIndex:y(g&&g.sortIndex,-d),val:d});return a},calculateChildrenAreas:function(a,e){var c=this,b=c.options,f=c.mapOptionsToLevel[a.level+1],I=y(c[f&&f.layoutAlgorithm]&&
f.layoutAlgorithm,b.layoutAlgorithm),d=b.alternateStartingDirection,g=[];a=w(a.children,function(a){return!a.ignore});f&&f.layoutStartingDirection&&(e.direction="vertical"===f.layoutStartingDirection?0:1);g=c[I](e,a);k(a,function(a,b){b=g[b];a.values=m(b,{val:a.childrenTotal,direction:d?1-e.direction:e.direction});a.pointValues=m(b,{x:b.x/c.axisRatio,width:b.width/c.axisRatio});a.children.length&&c.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,b=a.xAxis,c=a.yAxis;k(a.points,
function(e){var f=e.node,p=f.pointValues,d,g,r;r=(a.pointAttribs(e)["stroke-width"]||0)%2/2;p&&f.visible?(f=Math.round(b.translate(p.x,0,0,0,1))-r,d=Math.round(b.translate(p.x+p.width,0,0,0,1))-r,g=Math.round(c.translate(p.y,0,0,0,1))-r,p=Math.round(c.translate(p.y+p.height,0,0,0,1))-r,e.shapeType="rect",e.shapeArgs={x:Math.min(f,d),y:Math.min(g,p),width:Math.abs(d-f),height:Math.abs(p-g)},e.plotX=e.shapeArgs.x+e.shapeArgs.width/2,e.plotY=e.shapeArgs.y+e.shapeArgs.height/2):(delete e.plotX,delete e.plotY)})},
setColorRecursive:function(a,e,c,b,f){var p=this,d=p&&p.chart,d=d&&d.options&&d.options.colors,g;if(a){g=u(a,{colors:d,index:b,mapOptionsToLevel:p.mapOptionsToLevel,parentColor:e,parentColorIndex:c,series:p,siblings:f});if(e=p.points[a.i])e.color=g.color,e.colorIndex=g.colorIndex;k(a.children||[],function(c,e){p.setColorRecursive(c,g.color,g.colorIndex,e,a.children.length)})}},algorithmGroup:function(a,e,c,b){this.height=a;this.width=e;this.plot=b;this.startDirection=this.direction=c;this.lH=this.nH=
this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/
this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,e,c,b){var f,p,d,g,r=c.lW,z=c.lH,h=c.plot,q,v=0,l=c.elArr.length-1;e?(r=c.nW,z=c.nH):q=c.elArr[c.elArr.length-1];k(c.elArr,function(a){if(e||v<l)0===c.direction?(f=h.x,p=h.y,d=r,g=a/d):(f=h.x,p=h.y,g=z,d=a/g),
b.push({x:f,y:p,width:d,height:g}),0===c.direction?h.y+=g:h.x+=d;v+=1});c.reset();0===c.direction?c.width-=r:c.height-=z;h.y=h.parent.y+(h.parent.height-c.height);h.x=h.parent.x+(h.parent.width-c.width);a&&(c.direction=1-c.direction);e||c.addElement(q)},algorithmLowAspectRatio:function(a,e,c){var b=[],f=this,d,C={x:e.x,y:e.y,parent:e},g=0,r=c.length-1,z=new this.algorithmGroup(e.height,e.width,e.direction,C);k(c,function(c){d=c.val/e.val*e.height*e.width;z.addElement(d);z.lP.nR>z.lP.lR&&f.algorithmCalcPoints(a,
!1,z,b,C);g===r&&f.algorithmCalcPoints(a,!0,z,b,C);g+=1});return b},algorithmFill:function(a,b,c){var e=[],f,d=b.direction,C=b.x,g=b.y,r=b.width,z=b.height,h,q,v,l;k(c,function(c){f=c.val/b.val*b.height*b.width;h=C;q=g;0===d?(l=z,v=f/l,r-=v,C+=v):(v=r,l=f/v,z-=l,g+=l);e.push({x:h,y:q,width:v,height:l});a&&(d=1-d)});return e},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,
a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,c=L(a),d,f;x.prototype.translate.call(a);f=a.tree=a.getTree();d=a.nodeMap[c];a.mapOptionsToLevel=G({from:d.level+1,levels:b.levels,to:f.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===c||d&&d.children.length||(a.drillToNode("",!1),c=a.rootNode,d=a.nodeMap[c]);J(a.nodeMap[a.rootNode],function(c){var b=!1,d=c.parent;c.visible=!0;if(d||""===d)b=a.nodeMap[d];
return b});J(a.nodeMap[a.rootNode].children,function(a){var c=!1;k(a,function(a){a.visible=!0;a.children.length&&(c=(c||[]).concat(a.children))});return c});a.setTreeValues(f);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=c={x:0,y:0,width:100,height:100};a.nodeMap[""].values=c=m(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:f.val});a.calculateChildrenAreas(f,c);a.colorAxis?a.translateColors():b.colorByPoint||a.setColorRecursive(a.tree);b.allowDrillToNode&&
(b=d.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,c=w(a.points,function(a){return a.node.visible}),d,f;k(c,function(c){f=b[c.node.level];d={style:{}};c.node.isLeaf||(d.enabled=!1);f&&f.dataLabels&&(d=m(d,f.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(d.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+
"px"}));c.dlOptions=m(d,c.options.dataLabels)});x.prototype.drawDataLabels.call(this)},alignDataLabel:function(a){d&&d.column&&d.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=F(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{},c=this.options,f=b&&c.states[b]||{},e=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||f.borderColor||c.borderColor,"stroke-width":y(a&&
a.borderWidth,d.borderWidth,f.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||f.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==e.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==e.indexOf("highcharts-internal-node-interactive")?(b=y(f.opacity,c.opacity),a.fill=q(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==e.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=q(a.fill).brighten(f.brightness).get());return a},
drawPoints:function(){var a=this,b=w(a.points,function(a){return a.node.visible});k(b,function(c){var b="level-group-"+c.node.levelDynamic;a[b]||(a[b]=a.chart.renderer.g(b).attr({zIndex:1E3-c.node.levelDynamic}).add(a.group));c.group=a[b]});d&&d.column&&d.column.prototype.drawPoints.call(this);a.options.allowDrillToNode&&k(b,function(c){c.graphic&&(c.drillId=a.options.interactByLeaf?a.drillToByLeaf(c):a.drillToByGroup(c))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;B(b)&&(a.setState(""),
this.drillToNode(b))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&B(a.parent)&&this.drillToNode(a.parent)},drillToNode:function(a,b){var c=this.nodeMap[a];this.idPreviousRoot=this.rootNode;this.rootNode=
a;""===a?this.drillUpButton=this.drillUpButton.destroy():this.showDrillUpButton(c&&c.name||a);this.isDirty=!0;y(b,!0)&&this.chart.redraw()},showDrillUpButton:function(a){var b=this;a=a||"\x3c Back";var c=b.options.drillUpButton,d,f;c.text&&(a=c.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:a}).align()):(f=(d=c.theme)&&d.states,this.drillUpButton=this.chart.renderer.button(a,null,null,function(){b.drillUp()},d,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:c.position.align,
zIndex:7}).add().align(c.position,!1,c.relativeTo||"plotBox"))},buildKDTree:D,drawLegendSymbol:b.LegendSymbolMixin?b.LegendSymbolMixin.drawRectangle:void 0,getExtremes:function(){x.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;x.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,
tickPositions:[]};x.prototype.bindAxes.call(this);b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,a)},utils:{recursive:J,reduce:K}},{getClassName:function(){var a=b.Point.prototype.getClassName.call(this),d=this.series,c=d.options;this.node.level<=d.nodeMap[d.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||y(c.interactByLeaf,!c.allowDrillToNode)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||
n(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:d?d.pie.prototype.pointClass.prototype.setVisible:void 0})})(E,N);(function(b,A,l){var d=b.CenteredSeriesMixin,t=b.Series,m=b.each,H=b.extend,D=d.getCenter,k=l.getColor,u=l.getLevelOptions,G=d.getStartAndEndRadians,w=b.grep,n=b.inArray,F=b.isNumber,B=b.isObject,y=b.isString,x=b.keys,E=b.merge,q=180/Math.PI,d=b.seriesType,M=l.setTreeValues,K=b.reduce,J=l.updateRootId,
L=function(a,b){var c=[];if(F(a)&&F(b)&&a<=b)for(;a<=b;a++)c.push(a);return c},a=function(a,b){var c;b=B(b)?b:{};var d=0,e,g,r,p;B(a)&&(c=E({},a),a=F(b.from)?b.from:0,p=F(b.to)?b.to:0,g=L(a,p),a=w(x(c),function(a){return-1===n(+a,g)}),e=r=F(b.diffRadius)?b.diffRadius:0,m(g,function(a){a=c[a];var b=a.levelSize.unit,f=a.levelSize.value;"weight"===b?d+=f:"percentage"===b?(a.levelSize={unit:"pixels",value:f/100*e},r-=a.levelSize.value):"pixels"===b&&(r-=f)}),m(g,function(a){var b=c[a];"weight"===b.levelSize.unit&&
(b=b.levelSize.value,c[a].levelSize={unit:"pixels",value:b/d*r})}),m(a,function(a){c[a].levelSize={value:0,unit:"pixels"}}));return c},e=function(a,b){var c=b.mapIdToNode[a.parent],d=b.series,e=d.chart,g=d.points[a.i],c=k(a,{colors:e&&e.options&&e.options.colors,colorIndex:d.colorIndex,index:b.index,mapOptionsToLevel:b.mapOptionsToLevel,parentColor:c&&c.color,parentColorIndex:c&&c.colorIndex,series:b.series,siblings:b.siblings});a.color=c.color;a.colorIndex=c.colorIndex;g&&(g.color=a.color,g.colorIndex=
a.colorIndex,a.sliced=a.id!==b.idRoot?g.sliced:!1);return a};d("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,dataLabels:{defer:!0,style:{textOverflow:"ellipsis"},rotationMode:"perpendicular"},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},{drawDataLabels:b.noop,drawPoints:function(){var a=this,b=a.mapOptionsToLevel,d=a.shapeRoot,e=a.group,k=a.hasRendered,g=a.rootNode,r=a.idPreviousRoot,z=a.nodeMap,h=z[r],l=h&&h.shapeArgs,h=a.points,v=a.startAndEndRadians,
n=a.chart,n=n&&n.options&&n.options.chart||{},x="boolean"===typeof n.animation?n.animation:!0,u=a.center[3]/2,A=a.chart.renderer,y,w=!1,D=!1;if(n=!!(x&&k&&g!==r&&a.dataLabelsGroup))a.dataLabelsGroup.attr({opacity:0}),y=function(){w=!0;a.dataLabelsGroup&&a.dataLabelsGroup.animate({opacity:1,visibility:"visible"})};m(h,function(c){var f,p,h=c.node,n=b[h.level];f=c.shapeExisting||{};var m=h.shapeArgs||{},t,I=!(!h.visible||!h.shapeArgs);if(k&&x){var w={};p={end:m.end,start:m.start,innerR:m.innerR,r:m.r,
x:m.x,y:m.y};I?!c.graphic&&l&&(w=g===c.id?{start:v.start,end:v.end}:l.end<=m.start?{start:v.end,end:v.end}:{start:v.start,end:v.start},w.innerR=w.r=u):c.graphic&&(r===c.id?p={innerR:u,r:u}:d&&(p=d.end<=f.start?{innerR:u,r:u,start:v.end,end:v.end}:{innerR:u,r:u,start:v.start,end:v.start}));f=w}else p=m,f={};var w=[m.plotX,m.plotY],C;c.node.isLeaf||(g===c.id?(C=z[g],C=C.parent):C=c.id);H(c,{shapeExisting:m,tooltipPos:w,drillId:C,name:""+(c.name||c.id||c.index),plotX:m.plotX,plotY:m.plotY,value:h.val,
isNull:!I});C=c.options;h=B(m)?m:{};C=B(C)?C.dataLabels:{};n=B(n)?n.dataLabels:{};n=E({rotationMode:"perpendicular",style:{width:h.radius}},n,C);F(n.rotation)||(h=h.end-(h.end-h.start)/2,h=h*q%180,"parallel"===n.rotationMode&&(h-=90),90<h&&(h-=180),n.rotation=h);0===n.rotation&&(n.rotation=.001);c.dlOptions=n;!D&&I&&(D=!0,t=y);c.draw({animate:p,attr:H(f,a.pointAttribs&&a.pointAttribs(c,c.selected&&"select")),onComplete:t,group:e,renderer:A,shapeType:"arc",shapeArgs:m})});n&&D?(a.hasRendered=!1,a.options.dataLabels.defer=
!0,t.prototype.drawDataLabels.call(a),a.hasRendered=!0,w&&y()):t.prototype.drawDataLabels.call(a)},pointAttribs:b.seriesTypes.column.prototype.pointAttribs,layoutAlgorithm:function(a,b,d){var c=a.start,e=a.end-c,f=a.val,r=a.x,p=a.y,h=d&&B(d.levelSize)&&F(d.levelSize.value)?d.levelSize.value:0,m=a.r,n=m+h,k=d&&F(d.slicedOffset)?d.slicedOffset:0;return K(b||[],function(a,b){var d=1/f*b.val*e,g=c+d/2,l=r+Math.cos(g)*k,g=p+Math.sin(g)*k;b={x:b.sliced?l:r,y:b.sliced?g:p,innerR:m,r:n,radius:h,start:c,end:c+
d};a.push(b);c=b.end;return a},[])},setShapeArgs:function(a,b,d){var c=[],e=d[a.level+1];a=w(a.children,function(a){return a.visible});c=this.layoutAlgorithm(b,a,e);m(a,function(a,b){b=c[b];var e=b.start+(b.end-b.start)/2,f=b.innerR+(b.r-b.innerR)/2,g=b.end-b.start,e=0===b.innerR&&6.28<g?{x:b.x,y:b.y}:{x:b.x+Math.cos(e)*f,y:b.y+Math.sin(e)*f},f=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=g*b.innerR,this.points[a.i].outerArcLength=
g*b.r);a.shapeArgs=E(b,{plotX:e.x,plotY:e.y});a.values=E(b,{val:f});a.children.length&&this.setShapeArgs(a,a.values,d)},this)},translate:function(){var b=this.options,d=this.center=D.call(this),f=this.startAndEndRadians=G(b.startAngle,b.endAngle),m=d[3]/2,n=d[2]/2-m,g=J(this),k=this.nodeMap,l,h=k&&k[g],q,v;this.shapeRoot=h&&h.shapeArgs;t.prototype.translate.call(this);v=this.tree=this.getTree();k=this.nodeMap;h=k[g];l=y(h.parent)?h.parent:"";q=k[l];l=u({from:0<h.level?h.level:1,levels:this.options.levels,
to:v.height,defaults:{colorByPoint:b.colorByPoint,dataLabels:b.dataLabels,levelIsConstant:b.levelIsConstant,levelSize:b.levelSize,slicedOffset:b.slicedOffset}});l=a(l,{diffRadius:n,from:0<h.level?h.level:1,to:v.height});M(v,{before:e,idRoot:g,levelIsConstant:b.levelIsConstant,mapOptionsToLevel:l,mapIdToNode:k,points:this.points,series:this});b=k[""].shapeArgs={end:f.end,r:m,start:f.start,val:h.val,x:d[0],y:d[1]};this.setShapeArgs(q,b,l);this.mapOptionsToLevel=l},animate:function(a){var b=this.chart,
c=[b.plotWidth/2,b.plotHeight/2],d=b.plotLeft,e=b.plotTop,b=this.group;a?(a={translateX:c[0]+d,translateY:c[1]+e,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},b.attr(a)):(a={translateX:d,translateY:e,scaleX:1,scaleY:1,rotation:0,opacity:1},b.animate(a,this.options.animation),this.animate=null)},utils:{calculateLevelSizes:a,range:L}},{draw:A,shouldDraw:function(){return!this.isNull}})})(E,O,N)});
