/*
 Highcharts JS v6.1.0-modified (2018-06-15)

 (c) 2016 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(D){"object"===typeof module&&module.exports?module.exports=D:D(Highcharts)})(function(D){var O=function(){return function(b){var A=this,k=A.graphic,f=b.animate,w=b.attr,t=b.onComplete,G=b.css,B=b.group,l=b.renderer,y=b.shapeArgs;b=b.shapeType;A.shouldDraw()?(k||(A.graphic=k=l[b](y).add(B)),k.css(G).attr(w).animate(f,void 0,t)):k&&k.animate(f,void 0,function(){A.graphic=k=k.destroy();"function"===typeof t&&t()});k&&k.addClass(A.getClassName(),!0)}}(),N=function(b){var A=b.each,k=b.extend,
f=b.isArray,w=b.isObject,t=b.isNumber,G=b.merge,B=b.pick,l=b.reduce;return{getColor:function(y,z){var v=z.index,m=z.mapOptionsToLevel,f=z.parentColor,k=z.parentColorIndex,u=z.series,p=z.colors,t=z.siblings,F=u.points,l,w,A,I;if(y){F=F[y.i];y=m[y.level]||{};if(l=F&&y.colorByPoint)A=F.index%(p?p.length:u.chart.options.chart.colorCount),w=p&&p[A];p=F&&F.options.color;l=y&&y.color;if(m=f)m=(m=y&&y.colorVariation)&&"brightness"===m.key?b.color(f).brighten(v/t*m.to).get():f;l=B(p,l,w,m,u.color);I=B(F&&
F.options.colorIndex,y&&y.colorIndex,A,k,z.colorIndex)}return{color:l,colorIndex:I}},getLevelOptions:function(b){var z=null,v,m,E,C;if(w(b))for(z={},E=t(b.from)?b.from:1,C=b.levels,m={},v=w(b.defaults)?b.defaults:{},f(C)&&(m=l(C,function(b,p){var f,m;w(p)&&t(p.level)&&(m=G({},p),f="boolean"===typeof m.levelIsConstant?m.levelIsConstant:v.levelIsConstant,delete m.levelIsConstant,delete m.level,p=p.level+(f?0:E-1),w(b[p])?k(b[p],m):b[p]=m);return b},{})),C=t(b.to)?b.to:1,b=0;b<=C;b++)z[b]=G({},v,w(m[b])?
m[b]:{});return z},setTreeValues:function z(b,m){var f=m.before,l=m.idRoot,t=m.mapIdToNode[l],p=m.points[b.i],w=p&&p.options||{},v=0,G=[];k(b,{levelDynamic:b.level-(("boolean"===typeof m.levelIsConstant?m.levelIsConstant:1)?0:t.level),name:B(p&&p.name,""),visible:l===b.id||("boolean"===typeof m.visible?m.visible:!1)});"function"===typeof f&&(b=f(b,m));A(b.children,function(f,p){var l=k({},m);k(l,{index:p,siblings:b.children.length,visible:b.visible});f=z(f,l);G.push(f);f.visible&&(v+=f.val)});b.visible=
0<v||b.visible;f=B(w.value,v);k(b,{children:G,childrenTotal:v,isLeaf:b.visible&&!v,val:f});return b},updateRootId:function(b){var f;w(b)&&(f=w(b.options)?b.options:{},f=B(b.rootNode,f.rootId,""),w(b.userOptions)&&(b.userOptions.rootId=f),b.rootNode=f);return f}}}(D);(function(b,A){var k=b.seriesType,f=b.seriesTypes,w=b.map,t=b.merge,G=b.extend,B=b.noop,l=b.each,y=A.getColor,z=A.getLevelOptions,v=b.grep,m=b.isNumber,E=b.isObject,C=b.isString,u=b.pick,p=b.Series,D=b.stableSort,F=b.Color,M=function(a,
d,c){c=c||this;b.objectEach(a,function(e,g){d.call(c,e,g,a)})},L=b.reduce,J=function(a,d,c){c=c||this;a=d.call(c,a);!1!==a&&J(a,d,c)},I=A.updateRootId;k("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",
alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:f&&f.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],axisTypes:f&&f.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:B,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",translateColors:f&&f.heatmap&&f.heatmap.prototype.translateColors,
colorAttribs:f&&f.heatmap&&f.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,d){a=L(a||[],function(c,a,d){a=u(a.parent,"");void 0===c[a]&&(c[a]=[]);c[a].push(d);return c},{});M(a,function(a,e,g){""!==e&&-1===b.inArray(e,d)&&(l(a,function(a){g[""].push(a)}),delete g[e])});return a},getTree:function(){var a=w(this.data,function(a){return a.id}),a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},init:function(a,
d){p.prototype.init.call(this,a,d);this.options.allowDrillToNode&&b.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(a,d,c,e,g){var b=this,q=[],h=b.points[d],x=0,H;l(e[a]||[],function(d){H=b.buildNode(b.points[d].id,d,c+1,e,a);x=Math.max(H.height+1,x);q.push(H)});d={id:a,i:d,children:q,height:x,level:c,parent:g,visible:!1};b.nodeMap[d.id]=d;h&&(h.node=d);return d},setTreeValues:function(a){var d=this,c=d.options,b=d.nodeMap[d.rootNode],c="boolean"===typeof c.levelIsConstant?c.levelIsConstant:
!0,g=0,r=[],q,h=d.points[a.i];l(a.children,function(a){a=d.setTreeValues(a);r.push(a);a.ignore||(g+=a.val)});D(r,function(a,c){return a.sortIndex-c.sortIndex});q=u(h&&h.options.value,g);h&&(h.value=q);G(a,{children:r,childrenTotal:g,ignore:!(u(h&&h.visible,!0)&&0<q),isLeaf:a.visible&&!g,levelDynamic:a.level-(c?0:b.level),name:u(h&&h.name,""),sortIndex:u(h&&h.sortIndex,-q),val:q});return a},calculateChildrenAreas:function(a,d){var c=this,b=c.options,g=c.mapOptionsToLevel[a.level+1],r=u(c[g&&g.layoutAlgorithm]&&
g.layoutAlgorithm,b.layoutAlgorithm),q=b.alternateStartingDirection,h=[];a=v(a.children,function(a){return!a.ignore});g&&g.layoutStartingDirection&&(d.direction="vertical"===g.layoutStartingDirection?0:1);h=c[r](d,a);l(a,function(a,b){b=h[b];a.values=t(b,{val:a.childrenTotal,direction:q?1-d.direction:d.direction});a.pointValues=t(b,{x:b.x/c.axisRatio,width:b.width/c.axisRatio});a.children.length&&c.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,b=a.xAxis,c=a.yAxis;l(a.points,
function(d){var g=d.node,e=g.pointValues,q,h,x;x=(a.pointAttribs(d)["stroke-width"]||0)%2/2;e&&g.visible?(g=Math.round(b.translate(e.x,0,0,0,1))-x,q=Math.round(b.translate(e.x+e.width,0,0,0,1))-x,h=Math.round(c.translate(e.y,0,0,0,1))-x,e=Math.round(c.translate(e.y+e.height,0,0,0,1))-x,d.shapeType="rect",d.shapeArgs={x:Math.min(g,q),y:Math.min(h,e),width:Math.abs(q-g),height:Math.abs(e-h)},d.plotX=d.shapeArgs.x+d.shapeArgs.width/2,d.plotY=d.shapeArgs.y+d.shapeArgs.height/2):(delete d.plotX,delete d.plotY)})},
setColorRecursive:function(a,d,c,b,g){var e=this,q=e&&e.chart,q=q&&q.options&&q.options.colors,h;if(a){h=y(a,{colors:q,index:b,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:d,parentColorIndex:c,series:e,siblings:g});if(d=e.points[a.i])d.color=h.color,d.colorIndex=h.colorIndex;l(a.children||[],function(c,d){e.setColorRecursive(c,h.color,h.colorIndex,d,a.children.length)})}},algorithmGroup:function(a,d,c,b){this.height=a;this.width=d;this.plot=b;this.startDirection=this.direction=c;this.lH=this.nH=
this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/
this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,d,c,b){var e,r,q,h,x=c.lW,f=c.lH,n=c.plot,m,p=0,k=c.elArr.length-1;d?(x=c.nW,f=c.nH):m=c.elArr[c.elArr.length-1];l(c.elArr,function(a){if(d||p<k)0===c.direction?(e=n.x,r=n.y,q=x,h=a/q):(e=n.x,r=n.y,h=f,q=a/h),
b.push({x:e,y:r,width:q,height:h}),0===c.direction?n.y+=h:n.x+=q;p+=1});c.reset();0===c.direction?c.width-=x:c.height-=f;n.y=n.parent.y+(n.parent.height-c.height);n.x=n.parent.x+(n.parent.width-c.width);a&&(c.direction=1-c.direction);d||c.addElement(m)},algorithmLowAspectRatio:function(a,b,c){var d=[],g=this,r,q={x:b.x,y:b.y,parent:b},h=0,x=c.length-1,f=new this.algorithmGroup(b.height,b.width,b.direction,q);l(c,function(c){r=c.val/b.val*b.height*b.width;f.addElement(r);f.lP.nR>f.lP.lR&&g.algorithmCalcPoints(a,
!1,f,d,q);h===x&&g.algorithmCalcPoints(a,!0,f,d,q);h+=1});return d},algorithmFill:function(a,b,c){var d=[],g,r=b.direction,q=b.x,h=b.y,f=b.width,m=b.height,n,p,K,k;l(c,function(c){g=c.val/b.val*b.height*b.width;n=q;p=h;0===r?(k=m,K=g/k,f-=K,q+=K):(K=f,k=g/K,m-=k,h+=k);d.push({x:n,y:p,width:K,height:k});a&&(r=1-r)});return d},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,
a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,c=I(a),e,g;p.prototype.translate.call(a);g=a.tree=a.getTree();e=a.nodeMap[c];a.mapOptionsToLevel=z({from:e.level+1,levels:b.levels,to:g.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===c||e&&e.children.length||(a.drillToNode("",!1),c=a.rootNode,e=a.nodeMap[c]);J(a.nodeMap[a.rootNode],function(c){var b=!1,e=c.parent;c.visible=!0;if(e||""===e)b=a.nodeMap[e];
return b});J(a.nodeMap[a.rootNode].children,function(a){var c=!1;l(a,function(a){a.visible=!0;a.children.length&&(c=(c||[]).concat(a.children))});return c});a.setTreeValues(g);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=c={x:0,y:0,width:100,height:100};a.nodeMap[""].values=c=t(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:g.val});a.calculateChildrenAreas(g,c);a.colorAxis?a.translateColors():b.colorByPoint||a.setColorRecursive(a.tree);b.allowDrillToNode&&
(b=e.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,c=v(a.points,function(a){return a.node.visible}),e,g;l(c,function(c){g=b[c.node.level];e={style:{}};c.node.isLeaf||(e.enabled=!1);g&&g.dataLabels&&(e=t(e,g.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(e.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+
"px"}));c.dlOptions=t(e,c.options.dataLabels)});p.prototype.drawDataLabels.call(this)},alignDataLabel:function(a){f.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=E(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=a&&c[a.node.level]||{},c=this.options,g=b&&c.states[b]||{},d=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||e.borderColor||g.borderColor||c.borderColor,"stroke-width":u(a&&a.borderWidth,
e.borderWidth,g.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||e.borderDashStyle||g.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==d.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==d.indexOf("highcharts-internal-node-interactive")?(b=u(g.opacity,c.opacity),a.fill=F(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==d.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=F(a.fill).brighten(g.brightness).get());return a},drawPoints:function(){var a=
this,b=v(a.points,function(a){return a.node.visible});l(b,function(c){var b="level-group-"+c.node.levelDynamic;a[b]||(a[b]=a.chart.renderer.g(b).attr({zIndex:1E3-c.node.levelDynamic}).add(a.group));c.group=a[b]});f.column.prototype.drawPoints.call(this);a.options.allowDrillToNode&&l(b,function(c){c.graphic&&(c.drillId=a.options.interactByLeaf?a.drillToByLeaf(c):a.drillToByGroup(c))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;C(b)&&(a.setState(""),this.drillToNode(b))},drillToByGroup:function(a){var b=
!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&C(a.parent)&&this.drillToNode(a.parent)},drillToNode:function(a,b){var c=this.nodeMap[a];this.idPreviousRoot=this.rootNode;this.rootNode=a;""===a?this.drillUpButton=this.drillUpButton.destroy():
this.showDrillUpButton(c&&c.name||a);this.isDirty=!0;u(b,!0)&&this.chart.redraw()},showDrillUpButton:function(a){var b=this;a=a||"\x3c Back";var c=b.options.drillUpButton,e,g;c.text&&(a=c.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:a}).align()):(g=(e=c.theme)&&e.states,this.drillUpButton=this.chart.renderer.button(a,null,null,function(){b.drillUp()},e,g&&g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:c.position.align,zIndex:7}).add().align(c.position,
!1,c.relativeTo||"plotBox"))},buildKDTree:B,drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,getExtremes:function(){p.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;p.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};p.prototype.bindAxes.call(this);b.extend(this.yAxis.options,
a);b.extend(this.xAxis.options,a)},utils:{recursive:J,reduce:L}},{getClassName:function(){var a=b.Point.prototype.getClassName.call(this),d=this.series,c=d.options;this.node.level<=d.nodeMap[d.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||u(c.interactByLeaf,!c.allowDrillToNode)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||m(this.value)},setState:function(a){b.Point.prototype.setState.call(this,
a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:f.pie.prototype.pointClass.prototype.setVisible})})(D,N);(function(b,A,k){var f=b.CenteredSeriesMixin,w=b.Series,t=b.each,G=b.extend,B=f.getCenter,l=k.getColor,y=k.getLevelOptions,z=f.getStartAndEndRadians,v=b.grep,m=b.inArray,E=b.isNumber,C=b.isObject,u=b.isString,p=b.keys,D=b.merge,F=180/Math.PI,f=b.seriesType,M=k.setTreeValues,L=b.reduce,J=k.updateRootId,I=function(a,b){var c=[];if(E(a)&&E(b)&&a<=b)for(;a<=b;a++)c.push(a);
return c},a=function(a,b){var c;b=C(b)?b:{};var e=0,d,h,f,k;C(a)&&(c=D({},a),a=E(b.from)?b.from:0,k=E(b.to)?b.to:0,h=I(a,k),a=v(p(c),function(a){return-1===m(+a,h)}),d=f=E(b.diffRadius)?b.diffRadius:0,t(h,function(a){a=c[a];var b=a.levelSize.unit,g=a.levelSize.value;"weight"===b?e+=g:"percentage"===b?(a.levelSize={unit:"pixels",value:g/100*d},f-=a.levelSize.value):"pixels"===b&&(f-=g)}),t(h,function(a){var b=c[a];"weight"===b.levelSize.unit&&(b=b.levelSize.value,c[a].levelSize={unit:"pixels",value:b/
e*f})}),t(a,function(a){c[a].levelSize={value:0,unit:"pixels"}}));return c},d=function(a,b){var c=b.mapIdToNode[a.parent],d=b.series,e=d.chart,h=d.points[a.i],c=l(a,{colors:e&&e.options&&e.options.colors,colorIndex:d.colorIndex,index:b.index,mapOptionsToLevel:b.mapOptionsToLevel,parentColor:c&&c.color,parentColorIndex:c&&c.colorIndex,series:b.series,siblings:b.siblings});a.color=c.color;a.colorIndex=c.colorIndex;h&&(h.color=a.color,h.colorIndex=a.colorIndex,a.sliced=a.id!==b.idRoot?h.sliced:!1);return a};
f("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,dataLabels:{defer:!0,style:{textOverflow:"ellipsis"},rotationMode:"perpendicular"},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},{drawDataLabels:b.noop,drawPoints:function(){var a=this,b=a.mapOptionsToLevel,d=a.shapeRoot,f=a.group,q=a.hasRendered,h=a.rootNode,x=a.idPreviousRoot,m=a.nodeMap,n=m[x],p=n&&n.shapeArgs,n=a.points,k=a.startAndEndRadians,l=a.chart,l=l&&l.options&&l.options.chart||{},z="boolean"===
typeof l.animation?l.animation:!0,v=a.center[3]/2,A=a.chart.renderer,y,u=!1,B=!1;if(l=!!(z&&q&&h!==x&&a.dataLabelsGroup))a.dataLabelsGroup.attr({opacity:0}),y=function(){u=!0;a.dataLabelsGroup&&a.dataLabelsGroup.animate({opacity:1,visibility:"visible"})};t(n,function(c){var e,g,n=c.node,l=b[n.level];e=c.shapeExisting||{};var r=n.shapeArgs||{},t,w=!(!n.visible||!n.shapeArgs);if(q&&z){var H={};g={end:r.end,start:r.start,innerR:r.innerR,r:r.r,x:r.x,y:r.y};w?!c.graphic&&p&&(H=h===c.id?{start:k.start,
end:k.end}:p.end<=r.start?{start:k.end,end:k.end}:{start:k.start,end:k.start},H.innerR=H.r=v):c.graphic&&(x===c.id?g={innerR:v,r:v}:d&&(g=d.end<=e.start?{innerR:v,r:v,start:k.end,end:k.end}:{innerR:v,r:v,start:k.start,end:k.start}));e=H}else g=r,e={};var H=[r.plotX,r.plotY],u;c.node.isLeaf||(h===c.id?(u=m[h],u=u.parent):u=c.id);G(c,{shapeExisting:r,tooltipPos:H,drillId:u,name:""+(c.name||c.id||c.index),plotX:r.plotX,plotY:r.plotY,value:n.val,isNull:!w});u=c.options;n=C(r)?r:{};u=C(u)?u.dataLabels:
{};l=C(l)?l.dataLabels:{};l=D({rotationMode:"perpendicular",style:{width:n.radius}},l,u);E(l.rotation)||(n=n.end-(n.end-n.start)/2,n=n*F%180,"parallel"===l.rotationMode&&(n-=90),90<n&&(n-=180),l.rotation=n);0===l.rotation&&(l.rotation=.001);c.dlOptions=l;!B&&w&&(B=!0,t=y);c.draw({animate:g,attr:G(e,a.pointAttribs&&a.pointAttribs(c,c.selected&&"select")),onComplete:t,group:f,renderer:A,shapeType:"arc",shapeArgs:r})});l&&B?(a.hasRendered=!1,a.options.dataLabels.defer=!0,w.prototype.drawDataLabels.call(a),
a.hasRendered=!0,u&&y()):w.prototype.drawDataLabels.call(a)},pointAttribs:b.seriesTypes.column.prototype.pointAttribs,layoutAlgorithm:function(a,b,d){var c=a.start,e=a.end-c,h=a.val,g=a.x,f=a.y,n=d&&C(d.levelSize)&&E(d.levelSize.value)?d.levelSize.value:0,l=a.r,k=l+n,m=d&&E(d.slicedOffset)?d.slicedOffset:0;return L(b||[],function(a,b){var d=1/h*b.val*e,x=c+d/2,q=g+Math.cos(x)*m,x=f+Math.sin(x)*m;b={x:b.sliced?q:g,y:b.sliced?x:f,innerR:l,r:k,radius:n,start:c,end:c+d};a.push(b);c=b.end;return a},[])},
setShapeArgs:function(a,b,d){var c=[],e=d[a.level+1];a=v(a.children,function(a){return a.visible});c=this.layoutAlgorithm(b,a,e);t(a,function(a,b){b=c[b];var e=b.start+(b.end-b.start)/2,g=b.innerR+(b.r-b.innerR)/2,f=b.end-b.start,e=0===b.innerR&&6.28<f?{x:b.x,y:b.y}:{x:b.x+Math.cos(e)*g,y:b.y+Math.sin(e)*g},g=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=f*b.innerR,this.points[a.i].outerArcLength=f*b.r);a.shapeArgs=D(b,{plotX:e.x,
plotY:e.y});a.values=D(b,{val:g});a.children.length&&this.setShapeArgs(a,a.values,d)},this)},translate:function(){var b=this.options,e=this.center=B.call(this),g=this.startAndEndRadians=z(b.startAngle,b.endAngle),f=e[3]/2,l=e[2]/2-f,h=J(this),k=this.nodeMap,m,n=k&&k[h],p,t;this.shapeRoot=n&&n.shapeArgs;w.prototype.translate.call(this);t=this.tree=this.getTree();k=this.nodeMap;n=k[h];m=u(n.parent)?n.parent:"";p=k[m];m=y({from:0<n.level?n.level:1,levels:this.options.levels,to:t.height,defaults:{colorByPoint:b.colorByPoint,
dataLabels:b.dataLabels,levelIsConstant:b.levelIsConstant,levelSize:b.levelSize,slicedOffset:b.slicedOffset}});m=a(m,{diffRadius:l,from:0<n.level?n.level:1,to:t.height});M(t,{before:d,idRoot:h,levelIsConstant:b.levelIsConstant,mapOptionsToLevel:m,mapIdToNode:k,points:this.points,series:this});b=k[""].shapeArgs={end:g.end,r:f,start:g.start,val:n.val,x:e[0],y:e[1]};this.setShapeArgs(p,b,m);this.mapOptionsToLevel=m},animate:function(a){var b=this.chart,c=[b.plotWidth/2,b.plotHeight/2],d=b.plotLeft,f=
b.plotTop,b=this.group;a?(a={translateX:c[0]+d,translateY:c[1]+f,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},b.attr(a)):(a={translateX:d,translateY:f,scaleX:1,scaleY:1,rotation:0,opacity:1},b.animate(a,this.options.animation),this.animate=null)},utils:{calculateLevelSizes:a,range:I}},{draw:A,shouldDraw:function(){return!this.isNull}})})(D,O,N)});
