/*
 Highcharts JS v6.1.0-modified (2018-06-15)

 (c) 2016 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(C){"object"===typeof module&&module.exports?module.exports=C:C(Highcharts)})(function(C){var O=function(){return function(b){var z=this,n=z.graphic,e=b.animate,v=b.attr,p=b.onComplete,F=b.css,A=b.group,k=b.renderer,x=b.shapeArgs;b=b.shapeType;z.shouldDraw()?(n||(z.graphic=n=k[b](x).add(A)),n.css(F).attr(v).animate(e,void 0,p)):n&&n.animate(e,void 0,function(){z.graphic=n=n.destroy();"function"===typeof p&&p()});n&&n.addClass(z.getClassName(),!0)}}(),N=function(b){var z=b.each,n=b.extend,
e=b.isArray,v=b.isObject,p=b.isNumber,F=b.merge,A=b.pick,k=b.reduce;return{getColor:function(x,y){var t=y.index,l=y.mapOptionsToLevel,e=y.parentColor,n=y.parentColorIndex,u=y.series,q=y.colors,p=y.siblings,E=u.points,k,v,z,I;if(x){E=E[x.i];x=l[x.level]||{};if(k=E&&x.colorByPoint)z=E.index%(q?q.length:u.chart.options.chart.colorCount),v=q&&q[z];q=E&&E.options.color;k=x&&x.color;if(l=e)l=(l=x&&x.colorVariation)&&"brightness"===l.key?b.color(e).brighten(t/p*l.to).get():e;k=A(q,k,v,l,u.color);I=A(E&&
E.options.colorIndex,x&&x.colorIndex,z,n,y.colorIndex)}return{color:k,colorIndex:I}},getLevelOptions:function(b){var y=null,t,l,D,B;if(v(b))for(y={},D=p(b.from)?b.from:1,B=b.levels,l={},t=v(b.defaults)?b.defaults:{},e(B)&&(l=k(B,function(b,q){var e,l;v(q)&&p(q.level)&&(l=F({},q),e="boolean"===typeof l.levelIsConstant?l.levelIsConstant:t.levelIsConstant,delete l.levelIsConstant,delete l.level,q=q.level+(e?0:D-1),v(b[q])?n(b[q],l):b[q]=l);return b},{})),B=p(b.to)?b.to:1,b=0;b<=B;b++)y[b]=F({},t,v(l[b])?
l[b]:{});return y},setTreeValues:function y(b,l){var e=l.before,k=l.idRoot,p=l.mapIdToNode[k],q=l.points[b.i],v=q&&q.options||{},t=0,F=[];n(b,{levelDynamic:b.level-(("boolean"===typeof l.levelIsConstant?l.levelIsConstant:1)?0:p.level),name:A(q&&q.name,""),visible:k===b.id||("boolean"===typeof l.visible?l.visible:!1)});"function"===typeof e&&(b=e(b,l));z(b.children,function(e,q){var k=n({},l);n(k,{index:q,siblings:b.children.length,visible:b.visible});e=y(e,k);F.push(e);e.visible&&(t+=e.val)});b.visible=
0<t||b.visible;e=A(v.value,t);n(b,{children:F,childrenTotal:t,isLeaf:b.visible&&!t,val:e});return b},updateRootId:function(b){var e;v(b)&&(e=v(b.options)?b.options:{},e=A(b.rootNode,e.rootId,""),v(b.userOptions)&&(b.userOptions.rootId=e),b.rootNode=e);return e}}}(C);(function(b,z){var n=b.seriesType,e=b.seriesTypes,v=b.map,p=b.merge,F=b.extend,A=b.noop,k=b.each,x=z.getColor,y=z.getLevelOptions,t=b.grep,l=b.isNumber,D=b.isObject,B=b.isString,u=b.pick,q=b.Series,C=b.stableSort,E=b.Color,M=function(a,
d,c){c=c||this;b.objectEach(a,function(g,f){d.call(c,g,f,a)})},L=b.reduce,J=function(a,d,c){c=c||this;a=d.call(c,a);!1!==a&&J(a,d,c)},I=z.updateRootId;n("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",
alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:e&&e.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],axisTypes:e&&e.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:A,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",translateColors:e&&e.heatmap&&e.heatmap.prototype.translateColors,
colorAttribs:e&&e.heatmap&&e.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,d){a=L(a||[],function(c,a,d){a=u(a.parent,"");void 0===c[a]&&(c[a]=[]);c[a].push(d);return c},{});M(a,function(a,g,f){""!==g&&-1===b.inArray(g,d)&&(k(a,function(a){f[""].push(a)}),delete f[g])});return a},getTree:function(){var a=v(this.data,function(a){return a.id}),a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},init:function(a,
d){q.prototype.init.call(this,a,d);this.options.allowDrillToNode&&b.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(a,d,c,g,b){var f=this,r=[],h=f.points[d],w=0,H;k(g[a]||[],function(d){H=f.buildNode(f.points[d].id,d,c+1,g,a);w=Math.max(H.height+1,w);r.push(H)});d={id:a,i:d,children:r,height:w,level:c,parent:b,visible:!1};f.nodeMap[d.id]=d;h&&(h.node=d);return d},setTreeValues:function(a){var d=this,c=d.options,b=d.nodeMap[d.rootNode],c="boolean"===typeof c.levelIsConstant?c.levelIsConstant:
!0,f=0,G=[],r,h=d.points[a.i];k(a.children,function(a){a=d.setTreeValues(a);G.push(a);a.ignore||(f+=a.val)});C(G,function(a,c){return a.sortIndex-c.sortIndex});r=u(h&&h.options.value,f);h&&(h.value=r);F(a,{children:G,childrenTotal:f,ignore:!(u(h&&h.visible,!0)&&0<r),isLeaf:a.visible&&!f,levelDynamic:a.level-(c?0:b.level),name:u(h&&h.name,""),sortIndex:u(h&&h.sortIndex,-r),val:r});return a},calculateChildrenAreas:function(a,d){var c=this,b=c.options,f=c.mapOptionsToLevel[a.level+1],G=u(c[f&&f.layoutAlgorithm]&&
f.layoutAlgorithm,b.layoutAlgorithm),r=b.alternateStartingDirection,h=[];a=t(a.children,function(a){return!a.ignore});f&&f.layoutStartingDirection&&(d.direction="vertical"===f.layoutStartingDirection?0:1);h=c[G](d,a);k(a,function(a,b){b=h[b];a.values=p(b,{val:a.childrenTotal,direction:r?1-d.direction:d.direction});a.pointValues=p(b,{x:b.x/c.axisRatio,width:b.width/c.axisRatio});a.children.length&&c.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,b=a.xAxis,c=a.yAxis;k(a.points,
function(d){var f=d.node,g=f.pointValues,r,h,w;w=(a.pointAttribs(d)["stroke-width"]||0)%2/2;g&&f.visible?(f=Math.round(b.translate(g.x,0,0,0,1))-w,r=Math.round(b.translate(g.x+g.width,0,0,0,1))-w,h=Math.round(c.translate(g.y,0,0,0,1))-w,g=Math.round(c.translate(g.y+g.height,0,0,0,1))-w,d.shapeType="rect",d.shapeArgs={x:Math.min(f,r),y:Math.min(h,g),width:Math.abs(r-f),height:Math.abs(g-h)},d.plotX=d.shapeArgs.x+d.shapeArgs.width/2,d.plotY=d.shapeArgs.y+d.shapeArgs.height/2):(delete d.plotX,delete d.plotY)})},
setColorRecursive:function(a,d,c,b,f){var g=this,r=g&&g.chart,r=r&&r.options&&r.options.colors,h;if(a){h=x(a,{colors:r,index:b,mapOptionsToLevel:g.mapOptionsToLevel,parentColor:d,parentColorIndex:c,series:g,siblings:f});if(d=g.points[a.i])d.color=h.color,d.colorIndex=h.colorIndex;k(a.children||[],function(c,d){g.setColorRecursive(c,h.color,h.colorIndex,d,a.children.length)})}},algorithmGroup:function(a,d,c,b){this.height=a;this.width=d;this.plot=b;this.startDirection=this.direction=c;this.lH=this.nH=
this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/
this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,d,c,b){var f,g,r,h,w=c.lW,e=c.lH,m=c.plot,l,q=0,n=c.elArr.length-1;d?(w=c.nW,e=c.nH):l=c.elArr[c.elArr.length-1];k(c.elArr,function(a){if(d||q<n)0===c.direction?(f=m.x,g=m.y,r=w,h=a/r):(f=m.x,g=m.y,h=e,r=a/h),
b.push({x:f,y:g,width:r,height:h}),0===c.direction?m.y+=h:m.x+=r;q+=1});c.reset();0===c.direction?c.width-=w:c.height-=e;m.y=m.parent.y+(m.parent.height-c.height);m.x=m.parent.x+(m.parent.width-c.width);a&&(c.direction=1-c.direction);d||c.addElement(l)},algorithmLowAspectRatio:function(a,d,c){var b=[],f=this,G,r={x:d.x,y:d.y,parent:d},h=0,w=c.length-1,e=new this.algorithmGroup(d.height,d.width,d.direction,r);k(c,function(c){G=c.val/d.val*d.height*d.width;e.addElement(G);e.lP.nR>e.lP.lR&&f.algorithmCalcPoints(a,
!1,e,b,r);h===w&&f.algorithmCalcPoints(a,!0,e,b,r);h+=1});return b},algorithmFill:function(a,b,c){var d=[],f,e=b.direction,r=b.x,h=b.y,w=b.width,l=b.height,m,q,K,n;k(c,function(c){f=c.val/b.val*b.height*b.width;m=r;q=h;0===e?(n=l,K=f/n,w-=K,r+=K):(K=w,n=f/K,l-=n,h+=n);d.push({x:m,y:q,width:K,height:n});a&&(e=1-e)});return d},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,
a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,c=I(a),g,f;q.prototype.translate.call(a);f=a.tree=a.getTree();g=a.nodeMap[c];a.mapOptionsToLevel=y({from:g.level+1,levels:b.levels,to:f.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===c||g&&g.children.length||(a.drillToNode("",!1),c=a.rootNode,g=a.nodeMap[c]);J(a.nodeMap[a.rootNode],function(c){var b=!1,d=c.parent;c.visible=!0;if(d||""===d)b=a.nodeMap[d];
return b});J(a.nodeMap[a.rootNode].children,function(a){var c=!1;k(a,function(a){a.visible=!0;a.children.length&&(c=(c||[]).concat(a.children))});return c});a.setTreeValues(f);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=c={x:0,y:0,width:100,height:100};a.nodeMap[""].values=c=p(c,{width:c.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:f.val});a.calculateChildrenAreas(f,c);a.colorAxis?a.translateColors():b.colorByPoint||a.setColorRecursive(a.tree);b.allowDrillToNode&&
(b=g.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,c=t(a.points,function(a){return a.node.visible}),g,f;k(c,function(c){f=b[c.node.level];g={style:{}};c.node.isLeaf||(g.enabled=!1);f&&f.dataLabels&&(g=p(g,f.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(g.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+
"px"}));c.dlOptions=p(g,c.options.dataLabels)});q.prototype.drawDataLabels.call(this)},alignDataLabel:function(a){e.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=D(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{},c=this.options,f=b&&c.states[b]||{},e=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||f.borderColor||c.borderColor,"stroke-width":u(a&&a.borderWidth,
d.borderWidth,f.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||f.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==e.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==e.indexOf("highcharts-internal-node-interactive")?(b=u(f.opacity,c.opacity),a.fill=E(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==e.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=E(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=
this,b=t(a.points,function(a){return a.node.visible});k(b,function(c){var b="level-group-"+c.node.levelDynamic;a[b]||(a[b]=a.chart.renderer.g(b).attr({zIndex:1E3-c.node.levelDynamic}).add(a.group));c.group=a[b]});e.column.prototype.drawPoints.call(this);a.options.allowDrillToNode&&k(b,function(c){c.graphic&&(c.drillId=a.options.interactByLeaf?a.drillToByLeaf(c):a.drillToByGroup(c))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;B(b)&&(a.setState(""),this.drillToNode(b))},drillToByGroup:function(a){var b=
!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&B(a.parent)&&this.drillToNode(a.parent)},drillToNode:function(a,b){var c=this.nodeMap[a];this.idPreviousRoot=this.rootNode;this.rootNode=a;""===a?this.drillUpButton=this.drillUpButton.destroy():
this.showDrillUpButton(c&&c.name||a);this.isDirty=!0;u(b,!0)&&this.chart.redraw()},showDrillUpButton:function(a){var b=this;a=a||"\x3c Back";var c=b.options.drillUpButton,g,f;c.text&&(a=c.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:a}).align()):(f=(g=c.theme)&&g.states,this.drillUpButton=this.chart.renderer.button(a,null,null,function(){b.drillUp()},g,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:c.position.align,zIndex:7}).add().align(c.position,
!1,c.relativeTo||"plotBox"))},buildKDTree:A,drawLegendSymbol:b.LegendSymbolMixin?b.LegendSymbolMixin.drawRectangle:void 0,getExtremes:function(){q.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;q.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};q.prototype.bindAxes.call(this);
b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,a)},utils:{recursive:J,reduce:L}},{getClassName:function(){var a=b.Point.prototype.getClassName.call(this),d=this.series,c=d.options;this.node.level<=d.nodeMap[d.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||u(c.interactByLeaf,!c.allowDrillToNode)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||l(this.value)},setState:function(a){b.Point.prototype.setState.call(this,
a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:e.pie.prototype.pointClass.prototype.setVisible})})(C,N);(function(b,z,n){var e=b.CenteredSeriesMixin,v=b.Series,p=b.each,F=b.extend,A=e.getCenter,k=n.getColor,x=n.getLevelOptions,y=e.getStartAndEndRadians,t=b.grep,l=b.inArray,D=b.isNumber,B=b.isObject,u=b.isString,q=b.keys,C=b.merge,E=180/Math.PI,e=b.seriesType,M=n.setTreeValues,L=b.reduce,J=n.updateRootId,I=function(a,b){var c=[];if(D(a)&&D(b)&&a<=b)for(;a<=b;a++)c.push(a);
return c},a=function(a,b){var c;b=B(b)?b:{};var d=0,g,h,e,n;B(a)&&(c=C({},a),a=D(b.from)?b.from:0,n=D(b.to)?b.to:0,h=I(a,n),a=t(q(c),function(a){return-1===l(+a,h)}),g=e=D(b.diffRadius)?b.diffRadius:0,p(h,function(a){a=c[a];var b=a.levelSize.unit,f=a.levelSize.value;"weight"===b?d+=f:"percentage"===b?(a.levelSize={unit:"pixels",value:f/100*g},e-=a.levelSize.value):"pixels"===b&&(e-=f)}),p(h,function(a){var b=c[a];"weight"===b.levelSize.unit&&(b=b.levelSize.value,c[a].levelSize={unit:"pixels",value:b/
d*e})}),p(a,function(a){c[a].levelSize={value:0,unit:"pixels"}}));return c},d=function(a,b){var c=b.mapIdToNode[a.parent],d=b.series,e=d.chart,h=d.points[a.i],c=k(a,{colors:e&&e.options&&e.options.colors,colorIndex:d.colorIndex,index:b.index,mapOptionsToLevel:b.mapOptionsToLevel,parentColor:c&&c.color,parentColorIndex:c&&c.colorIndex,series:b.series,siblings:b.siblings});a.color=c.color;a.colorIndex=c.colorIndex;h&&(h.color=a.color,h.colorIndex=a.colorIndex,a.sliced=a.id!==b.idRoot?h.sliced:!1);return a};
e("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,dataLabels:{defer:!0,style:{textOverflow:"ellipsis"},rotationMode:"perpendicular"},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},{drawDataLabels:b.noop,drawPoints:function(){var a=this,b=a.mapOptionsToLevel,d=a.shapeRoot,e=a.group,r=a.hasRendered,h=a.rootNode,w=a.idPreviousRoot,l=a.nodeMap,m=l[w],q=m&&m.shapeArgs,m=a.points,n=a.startAndEndRadians,k=a.chart,k=k&&k.options&&k.options.chart||{},y="boolean"===
typeof k.animation?k.animation:!0,t=a.center[3]/2,z=a.chart.renderer,x,u=!1,A=!1;if(k=!!(y&&r&&h!==w&&a.dataLabelsGroup))a.dataLabelsGroup.attr({opacity:0}),x=function(){u=!0;a.dataLabelsGroup&&a.dataLabelsGroup.animate({opacity:1,visibility:"visible"})};p(m,function(c){var f,g,m=c.node,k=b[m.level];f=c.shapeExisting||{};var p=m.shapeArgs||{},G,v=!(!m.visible||!m.shapeArgs);if(r&&y){var H={};g={end:p.end,start:p.start,innerR:p.innerR,r:p.r,x:p.x,y:p.y};v?!c.graphic&&q&&(H=h===c.id?{start:n.start,
end:n.end}:q.end<=p.start?{start:n.end,end:n.end}:{start:n.start,end:n.start},H.innerR=H.r=t):c.graphic&&(w===c.id?g={innerR:t,r:t}:d&&(g=d.end<=f.start?{innerR:t,r:t,start:n.end,end:n.end}:{innerR:t,r:t,start:n.start,end:n.start}));f=H}else g=p,f={};var H=[p.plotX,p.plotY],u;c.node.isLeaf||(h===c.id?(u=l[h],u=u.parent):u=c.id);F(c,{shapeExisting:p,tooltipPos:H,drillId:u,name:""+(c.name||c.id||c.index),plotX:p.plotX,plotY:p.plotY,value:m.val,isNull:!v});u=c.options;m=B(p)?p:{};u=B(u)?u.dataLabels:
{};k=B(k)?k.dataLabels:{};k=C({rotationMode:"perpendicular",style:{width:m.radius}},k,u);D(k.rotation)||(m=m.end-(m.end-m.start)/2,m=m*E%180,"parallel"===k.rotationMode&&(m-=90),90<m&&(m-=180),k.rotation=m);0===k.rotation&&(k.rotation=.001);c.dlOptions=k;!A&&v&&(A=!0,G=x);c.draw({animate:g,attr:F(f,a.pointAttribs&&a.pointAttribs(c,c.selected&&"select")),onComplete:G,group:e,renderer:z,shapeType:"arc",shapeArgs:p})});k&&A?(a.hasRendered=!1,a.options.dataLabels.defer=!0,v.prototype.drawDataLabels.call(a),
a.hasRendered=!0,u&&x()):v.prototype.drawDataLabels.call(a)},pointAttribs:b.seriesTypes.column.prototype.pointAttribs,layoutAlgorithm:function(a,b,d){var c=a.start,f=a.end-c,e=a.val,g=a.x,k=a.y,m=d&&B(d.levelSize)&&D(d.levelSize.value)?d.levelSize.value:0,n=a.r,l=n+m,p=d&&D(d.slicedOffset)?d.slicedOffset:0;return L(b||[],function(a,b){var d=1/e*b.val*f,h=c+d/2,w=g+Math.cos(h)*p,h=k+Math.sin(h)*p;b={x:b.sliced?w:g,y:b.sliced?h:k,innerR:n,r:l,radius:m,start:c,end:c+d};a.push(b);c=b.end;return a},[])},
setShapeArgs:function(a,b,d){var c=[],f=d[a.level+1];a=t(a.children,function(a){return a.visible});c=this.layoutAlgorithm(b,a,f);p(a,function(a,b){b=c[b];var f=b.start+(b.end-b.start)/2,e=b.innerR+(b.r-b.innerR)/2,g=b.end-b.start,f=0===b.innerR&&6.28<g?{x:b.x,y:b.y}:{x:b.x+Math.cos(f)*e,y:b.y+Math.sin(f)*e},e=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=g*b.innerR,this.points[a.i].outerArcLength=g*b.r);a.shapeArgs=C(b,{plotX:f.x,
plotY:f.y});a.values=C(b,{val:e});a.children.length&&this.setShapeArgs(a,a.values,d)},this)},translate:function(){var b=this.options,e=this.center=A.call(this),f=this.startAndEndRadians=y(b.startAngle,b.endAngle),k=e[3]/2,n=e[2]/2-k,h=J(this),l=this.nodeMap,p,m=l&&l[h],q,t;this.shapeRoot=m&&m.shapeArgs;v.prototype.translate.call(this);t=this.tree=this.getTree();l=this.nodeMap;m=l[h];p=u(m.parent)?m.parent:"";q=l[p];p=x({from:0<m.level?m.level:1,levels:this.options.levels,to:t.height,defaults:{colorByPoint:b.colorByPoint,
dataLabels:b.dataLabels,levelIsConstant:b.levelIsConstant,levelSize:b.levelSize,slicedOffset:b.slicedOffset}});p=a(p,{diffRadius:n,from:0<m.level?m.level:1,to:t.height});M(t,{before:d,idRoot:h,levelIsConstant:b.levelIsConstant,mapOptionsToLevel:p,mapIdToNode:l,points:this.points,series:this});b=l[""].shapeArgs={end:f.end,r:k,start:f.start,val:m.val,x:e[0],y:e[1]};this.setShapeArgs(q,b,p);this.mapOptionsToLevel=p},animate:function(a){var b=this.chart,c=[b.plotWidth/2,b.plotHeight/2],d=b.plotLeft,e=
b.plotTop,b=this.group;a?(a={translateX:c[0]+d,translateY:c[1]+e,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},b.attr(a)):(a={translateX:d,translateY:e,scaleX:1,scaleY:1,rotation:0,opacity:1},b.animate(a,this.options.animation),this.animate=null)},utils:{calculateLevelSizes:a,range:I}},{draw:z,shouldDraw:function(){return!this.isNull}})})(C,O,N)});
