/*
 Highcharts JS v6.1.0-modified (2018-06-15)

 (c) 2014 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(w){"object"===typeof module&&module.exports?module.exports=w:w(Highcharts)})(function(w){var F=function(b){var w=b.each,B=b.extend,c=b.isArray,t=b.isObject,v=b.isNumber,E=b.merge,y=b.pick,n=b.reduce;return{getColor:function(p,q){var x=q.index,g=q.mapOptionsToLevel,c=q.parentColor,n=q.parentColorIndex,u=q.series,f=q.colors,t=q.siblings,h=u.points,C,D,A,v;if(p){h=h[p.i];p=g[p.level]||{};if(C=h&&p.colorByPoint)A=h.index%(f?f.length:u.chart.options.chart.colorCount),D=f&&f[A];f=h&&h.options.color;
C=p&&p.color;if(g=c)g=(g=p&&p.colorVariation)&&"brightness"===g.key?b.color(c).brighten(x/t*g.to).get():c;C=y(f,C,D,g,u.color);v=y(h&&h.options.colorIndex,p&&p.colorIndex,A,n,q.colorIndex)}return{color:C,colorIndex:v}},getLevelOptions:function(b){var q=null,x,g,p,z;if(t(b))for(q={},p=v(b.from)?b.from:1,z=b.levels,g={},x=t(b.defaults)?b.defaults:{},c(z)&&(g=n(z,function(b,f){var g,h;t(f)&&v(f.level)&&(h=E({},f),g="boolean"===typeof h.levelIsConstant?h.levelIsConstant:x.levelIsConstant,delete h.levelIsConstant,
delete h.level,f=f.level+(g?0:p-1),t(b[f])?B(b[f],h):b[f]=h);return b},{})),z=v(b.to)?b.to:1,b=0;b<=z;b++)q[b]=E({},x,t(g[b])?g[b]:{});return q},setTreeValues:function q(b,g){var c=g.before,n=g.idRoot,x=g.mapIdToNode[n],f=g.points[b.i],t=f&&f.options||{},h=0,v=[];B(b,{levelDynamic:b.level-(("boolean"===typeof g.levelIsConstant?g.levelIsConstant:1)?0:x.level),name:y(f&&f.name,""),visible:n===b.id||("boolean"===typeof g.visible?g.visible:!1)});"function"===typeof c&&(b=c(b,g));w(b.children,function(c,
f){var n=B({},g);B(n,{index:f,siblings:b.children.length,visible:b.visible});c=q(c,n);v.push(c);c.visible&&(h+=c.val)});b.visible=0<h||b.visible;c=y(t.value,h);B(b,{children:v,childrenTotal:h,isLeaf:b.visible&&!h,val:c});return b},updateRootId:function(b){var c;t(b)&&(c=t(b.options)?b.options:{},c=y(b.rootNode,c.rootId,""),t(b.userOptions)&&(b.userOptions.rootId=c),b.rootNode=c);return c}}}(w);(function(b,w){var B=b.seriesType,c=b.seriesTypes,t=b.map,v=b.merge,E=b.extend,y=b.noop,n=b.each,p=w.getColor,
q=w.getLevelOptions,x=b.grep,g=b.isNumber,F=b.isObject,z=b.isString,u=b.pick,f=b.Series,G=b.stableSort,h=b.Color,C=function(a,d,e){e=e||this;b.objectEach(a,function(b,k){d.call(e,b,k,a)})},D=b.reduce,A=function(a,d,e){e=e||this;a=d.call(e,a);!1!==a&&A(a,d,e)},H=w.updateRootId;B("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},
ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:c&&c.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],axisTypes:c&&c.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:y,parallelArrays:["x",
"y","value","colorValue"],colorKey:"colorValue",translateColors:c&&c.heatmap&&c.heatmap.prototype.translateColors,colorAttribs:c&&c.heatmap&&c.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,d){a=D(a||[],function(a,d,b){d=u(d.parent,"");void 0===a[d]&&(a[d]=[]);a[d].push(b);return a},{});C(a,function(a,r,k){""!==r&&-1===b.inArray(r,d)&&(n(a,function(a){k[""].push(a)}),delete k[r])});return a},getTree:function(){var a=t(this.data,function(a){return a.id}),
a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},init:function(a,d){f.prototype.init.call(this,a,d);this.options.allowDrillToNode&&b.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(a,d,e,b,k){var l=this,r=[],m=l.points[d],c=0,f;n(b[a]||[],function(d){f=l.buildNode(l.points[d].id,d,e+1,b,a);c=Math.max(f.height+1,c);r.push(f)});d={id:a,i:d,children:r,height:c,level:e,parent:k,visible:!1};l.nodeMap[d.id]=d;m&&(m.node=d);return d},setTreeValues:function(a){var d=
this,e=d.options,b=d.nodeMap[d.rootNode],e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0,k=0,l=[],c,m=d.points[a.i];n(a.children,function(a){a=d.setTreeValues(a);l.push(a);a.ignore||(k+=a.val)});G(l,function(a,d){return a.sortIndex-d.sortIndex});c=u(m&&m.options.value,k);m&&(m.value=c);E(a,{children:l,childrenTotal:k,ignore:!(u(m&&m.visible,!0)&&0<c),isLeaf:a.visible&&!k,levelDynamic:a.level-(e?0:b.level),name:u(m&&m.name,""),sortIndex:u(m&&m.sortIndex,-c),val:c});return a},calculateChildrenAreas:function(a,
d){var e=this,b=e.options,k=e.mapOptionsToLevel[a.level+1],l=u(e[k&&k.layoutAlgorithm]&&k.layoutAlgorithm,b.layoutAlgorithm),c=b.alternateStartingDirection,m=[];a=x(a.children,function(a){return!a.ignore});k&&k.layoutStartingDirection&&(d.direction="vertical"===k.layoutStartingDirection?0:1);m=e[l](d,a);n(a,function(a,b){b=m[b];a.values=v(b,{val:a.childrenTotal,direction:c?1-d.direction:d.direction});a.pointValues=v(b,{x:b.x/e.axisRatio,width:b.width/e.axisRatio});a.children.length&&e.calculateChildrenAreas(a,
a.values)})},setPointValues:function(){var a=this,d=a.xAxis,e=a.yAxis;n(a.points,function(b){var k=b.node,l=k.pointValues,c,r,f;f=(a.pointAttribs(b)["stroke-width"]||0)%2/2;l&&k.visible?(k=Math.round(d.translate(l.x,0,0,0,1))-f,c=Math.round(d.translate(l.x+l.width,0,0,0,1))-f,r=Math.round(e.translate(l.y,0,0,0,1))-f,l=Math.round(e.translate(l.y+l.height,0,0,0,1))-f,b.shapeType="rect",b.shapeArgs={x:Math.min(k,c),y:Math.min(r,l),width:Math.abs(c-k),height:Math.abs(l-r)},b.plotX=b.shapeArgs.x+b.shapeArgs.width/
2,b.plotY=b.shapeArgs.y+b.shapeArgs.height/2):(delete b.plotX,delete b.plotY)})},setColorRecursive:function(a,d,b,c,k){var e=this,r=e&&e.chart,r=r&&r.options&&r.options.colors,m;if(a){m=p(a,{colors:r,index:c,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:d,parentColorIndex:b,series:e,siblings:k});if(d=e.points[a.i])d.color=m.color,d.colorIndex=m.colorIndex;n(a.children||[],function(d,b){e.setColorRecursive(d,m.color,m.colorIndex,b,a.children.length)})}},algorithmGroup:function(a,d,b,c){this.height=
a;this.width=d;this.plot=c;this.startDirection=this.direction=b;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,d){return Math.max(a/d,d/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=
this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,d,b,c){var e,l,r,m,f=b.lW,g=b.lH,h=b.plot,p,q=0,v=b.elArr.length-1;d?(f=b.nW,g=b.nH):p=b.elArr[b.elArr.length-1];n(b.elArr,function(a){if(d||
q<v)0===b.direction?(e=h.x,l=h.y,r=f,m=a/r):(e=h.x,l=h.y,m=g,r=a/m),c.push({x:e,y:l,width:r,height:m}),0===b.direction?h.y+=m:h.x+=r;q+=1});b.reset();0===b.direction?b.width-=f:b.height-=g;h.y=h.parent.y+(h.parent.height-b.height);h.x=h.parent.x+(h.parent.width-b.width);a&&(b.direction=1-b.direction);d||b.addElement(p)},algorithmLowAspectRatio:function(a,b,e){var d=[],c=this,l,f={x:b.x,y:b.y,parent:b},m=0,h=e.length-1,g=new this.algorithmGroup(b.height,b.width,b.direction,f);n(e,function(e){l=e.val/
b.val*b.height*b.width;g.addElement(l);g.lP.nR>g.lP.lR&&c.algorithmCalcPoints(a,!1,g,d,f);m===h&&c.algorithmCalcPoints(a,!0,g,d,f);m+=1});return d},algorithmFill:function(a,b,e){var d=[],c,l=b.direction,f=b.x,h=b.y,g=b.width,p=b.height,q,v,t,u;n(e,function(e){c=e.val/b.val*b.height*b.width;q=f;v=h;0===l?(u=p,t=c/u,g-=t,f+=t):(t=g,u=c/t,p-=u,h+=u);d.push({x:q,y:v,width:t,height:u});a&&(l=1-l)});return d},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,
a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,e=H(a),c,k;f.prototype.translate.call(a);k=a.tree=a.getTree();c=a.nodeMap[e];a.mapOptionsToLevel=q({from:c.level+1,levels:b.levels,to:k.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===e||c&&c.children.length||(a.drillToNode("",!1),e=a.rootNode,c=a.nodeMap[e]);A(a.nodeMap[a.rootNode],function(b){var d=
!1,e=b.parent;b.visible=!0;if(e||""===e)d=a.nodeMap[e];return d});A(a.nodeMap[a.rootNode].children,function(a){var b=!1;n(a,function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(k);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=e={x:0,y:0,width:100,height:100};a.nodeMap[""].values=e=v(e,{width:e.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:k.val});a.calculateChildrenAreas(k,e);a.colorAxis?a.translateColors():
b.colorByPoint||a.setColorRecursive(a.tree);b.allowDrillToNode&&(b=c.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,e=x(a.points,function(a){return a.node.visible}),c,k;n(e,function(d){k=b[d.node.level];c={style:{}};d.node.isLeaf||(c.enabled=!1);k&&k.dataLabels&&(c=v(c,k.dataLabels),a._hasPointLabels=!0);d.shapeArgs&&(c.style.width=d.shapeArgs.width,
d.dataLabel&&d.dataLabel.css({width:d.shapeArgs.width+"px"}));d.dlOptions=v(c,d.options.dataLabels)});f.prototype.drawDataLabels.call(this)},alignDataLabel:function(a){c&&c.column&&c.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var d=F(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},c=a&&d[a.node.level]||{},d=this.options,f=b&&d.states[b]||{},g=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||c.borderColor||
f.borderColor||d.borderColor,"stroke-width":u(a&&a.borderWidth,c.borderWidth,f.borderWidth,d.borderWidth),dashstyle:a&&a.borderDashStyle||c.borderDashStyle||f.borderDashStyle||d.borderDashStyle,fill:a&&a.color||this.color};-1!==g.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==g.indexOf("highcharts-internal-node-interactive")?(b=u(f.opacity,d.opacity),a.fill=h(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==g.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=
h(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=this,b=x(a.points,function(a){return a.node.visible});n(b,function(b){var d="level-group-"+b.node.levelDynamic;a[d]||(a[d]=a.chart.renderer.g(d).attr({zIndex:1E3-b.node.levelDynamic}).add(a.group));b.group=a[d]});c&&c.column&&c.column.prototype.drawPoints.call(this);a.options.allowDrillToNode&&n(b,function(b){b.graphic&&(b.drillId=a.options.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=
(a=a.point)&&a.drillId;z(b)&&(a.setState(""),this.drillToNode(b))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&z(a.parent)&&this.drillToNode(a.parent)},drillToNode:function(a,b){var d=this.nodeMap[a];
this.idPreviousRoot=this.rootNode;this.rootNode=a;""===a?this.drillUpButton=this.drillUpButton.destroy():this.showDrillUpButton(d&&d.name||a);this.isDirty=!0;u(b,!0)&&this.chart.redraw()},showDrillUpButton:function(a){var b=this;a=a||"\x3c Back";var c=b.options.drillUpButton,f,g;c.text&&(a=c.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:a}).align()):(g=(f=c.theme)&&f.states,this.drillUpButton=this.chart.renderer.button(a,null,null,function(){b.drillUp()},f,g&&
g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:c.position.align,zIndex:7}).add().align(c.position,!1,c.relativeTo||"plotBox"))},buildKDTree:y,drawLegendSymbol:b.LegendSymbolMixin?b.LegendSymbolMixin.drawRectangle:void 0,getExtremes:function(){f.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;f.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,
min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};f.prototype.bindAxes.call(this);b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,a)},utils:{recursive:A,reduce:D}},{getClassName:function(){var a=b.Point.prototype.getClassName.call(this),d=this.series,c=d.options;this.node.level<=d.nodeMap[d.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||u(c.interactByLeaf,!c.allowDrillToNode)?this.node.isLeaf||(a+=" highcharts-internal-node"):
a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||g(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:c?c.pie.prototype.pointClass.prototype.setVisible:void 0})})(w,F)});
