/*
 Highcharts JS v6.1.0-modified (2018-06-15)

 (c) 2014 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(x){"object"===typeof module&&module.exports?module.exports=x:x(Highcharts)})(function(x){var G=function(b){var x=b.each,C=b.extend,d=b.isArray,t=b.isObject,n=b.isNumber,F=b.merge,z=b.pick,p=b.reduce;return{getColor:function(q,r){var y=r.index,l=r.mapOptionsToLevel,d=r.parentColor,p=r.parentColorIndex,v=r.series,f=r.colors,t=r.siblings,h=v.points,D,E,B,n;if(q){h=h[q.i];q=l[q.level]||{};if(D=h&&q.colorByPoint)B=h.index%(f?f.length:v.chart.options.chart.colorCount),E=f&&f[B];f=h&&h.options.color;
D=q&&q.color;if(l=d)l=(l=q&&q.colorVariation)&&"brightness"===l.key?b.color(d).brighten(y/t*l.to).get():d;D=z(f,D,E,l,v.color);n=z(h&&h.options.colorIndex,q&&q.colorIndex,B,p,r.colorIndex)}return{color:D,colorIndex:n}},getLevelOptions:function(b){var r=null,y,l,q,A;if(t(b))for(r={},q=n(b.from)?b.from:1,A=b.levels,l={},y=t(b.defaults)?b.defaults:{},d(A)&&(l=p(A,function(b,f){var l,h;t(f)&&n(f.level)&&(h=F({},f),l="boolean"===typeof h.levelIsConstant?h.levelIsConstant:y.levelIsConstant,delete h.levelIsConstant,
delete h.level,f=f.level+(l?0:q-1),t(b[f])?C(b[f],h):b[f]=h);return b},{})),A=n(b.to)?b.to:1,b=0;b<=A;b++)r[b]=F({},y,t(l[b])?l[b]:{});return r},setTreeValues:function r(b,l){var d=l.before,p=l.idRoot,y=l.mapIdToNode[p],f=l.points[b.i],t=f&&f.options||{},h=0,n=[];C(b,{levelDynamic:b.level-(("boolean"===typeof l.levelIsConstant?l.levelIsConstant:1)?0:y.level),name:z(f&&f.name,""),visible:p===b.id||("boolean"===typeof l.visible?l.visible:!1)});"function"===typeof d&&(b=d(b,l));x(b.children,function(f,
d){var p=C({},l);C(p,{index:d,siblings:b.children.length,visible:b.visible});f=r(f,p);n.push(f);f.visible&&(h+=f.val)});b.visible=0<h||b.visible;d=z(t.value,h);C(b,{children:n,childrenTotal:h,isLeaf:b.visible&&!h,val:d});return b},updateRootId:function(b){var d;t(b)&&(d=t(b.options)?b.options:{},d=z(b.rootNode,d.rootId,""),t(b.userOptions)&&(b.userOptions.rootId=d),b.rootNode=d);return d}}}(x);(function(b,x){var C=b.seriesType,d=b.seriesTypes,t=b.map,n=b.merge,F=b.extend,z=b.noop,p=b.each,q=x.getColor,
r=x.getLevelOptions,y=b.grep,l=b.isNumber,G=b.isObject,A=b.isString,v=b.pick,f=b.Series,I=b.stableSort,h=b.Color,D=function(a,c,e){e=e||this;b.objectEach(a,function(b,g){c.call(e,b,g,a)})},E=b.reduce,B=function(a,c,e){e=e||this;a=c.call(e,a);!1!==a&&B(a,c,e)},J=x.updateRootId;C("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},
ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:d&&d.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],axisTypes:d&&d.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:z,parallelArrays:["x",
"y","value","colorValue"],colorKey:"colorValue",translateColors:d&&d.heatmap&&d.heatmap.prototype.translateColors,colorAttribs:d&&d.heatmap&&d.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=E(a||[],function(a,c,b){c=v(c.parent,"");void 0===a[c]&&(a[c]=[]);a[c].push(b);return a},{});D(a,function(a,u,g){""!==u&&-1===b.inArray(u,c)&&(p(a,function(a){g[""].push(a)}),delete g[u])});return a},getTree:function(){var a=t(this.data,function(a){return a.id}),
a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},init:function(a,c){f.prototype.init.call(this,a,c);this.options.allowDrillToNode&&b.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(a,c,e,b,g){var m=this,u=[],k=m.points[c],H=0,d;p(b[a]||[],function(c){d=m.buildNode(m.points[c].id,c,e+1,b,a);H=Math.max(d.height+1,H);u.push(d)});c={id:a,i:c,children:u,height:H,level:e,parent:g,visible:!1};m.nodeMap[c.id]=c;k&&(k.node=c);return c},setTreeValues:function(a){var c=
this,e=c.options,b=c.nodeMap[c.rootNode],e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0,g=0,m=[],d,k=c.points[a.i];p(a.children,function(a){a=c.setTreeValues(a);m.push(a);a.ignore||(g+=a.val)});I(m,function(a,c){return a.sortIndex-c.sortIndex});d=v(k&&k.options.value,g);k&&(k.value=d);F(a,{children:m,childrenTotal:g,ignore:!(v(k&&k.visible,!0)&&0<d),isLeaf:a.visible&&!g,levelDynamic:a.level-(e?0:b.level),name:v(k&&k.name,""),sortIndex:v(k&&k.sortIndex,-d),val:d});return a},calculateChildrenAreas:function(a,
c){var e=this,b=e.options,g=e.mapOptionsToLevel[a.level+1],m=v(e[g&&g.layoutAlgorithm]&&g.layoutAlgorithm,b.layoutAlgorithm),d=b.alternateStartingDirection,k=[];a=y(a.children,function(a){return!a.ignore});g&&g.layoutStartingDirection&&(c.direction="vertical"===g.layoutStartingDirection?0:1);k=e[m](c,a);p(a,function(a,b){b=k[b];a.values=n(b,{val:a.childrenTotal,direction:d?1-c.direction:c.direction});a.pointValues=n(b,{x:b.x/e.axisRatio,width:b.width/e.axisRatio});a.children.length&&e.calculateChildrenAreas(a,
a.values)})},setPointValues:function(){var a=this,c=a.xAxis,e=a.yAxis;p(a.points,function(b){var g=b.node,m=g.pointValues,u,k,d;d=(a.pointAttribs(b)["stroke-width"]||0)%2/2;m&&g.visible?(g=Math.round(c.translate(m.x,0,0,0,1))-d,u=Math.round(c.translate(m.x+m.width,0,0,0,1))-d,k=Math.round(e.translate(m.y,0,0,0,1))-d,m=Math.round(e.translate(m.y+m.height,0,0,0,1))-d,b.shapeType="rect",b.shapeArgs={x:Math.min(g,u),y:Math.min(k,m),width:Math.abs(u-g),height:Math.abs(m-k)},b.plotX=b.shapeArgs.x+b.shapeArgs.width/
2,b.plotY=b.shapeArgs.y+b.shapeArgs.height/2):(delete b.plotX,delete b.plotY)})},setColorRecursive:function(a,c,b,d,g){var e=this,u=e&&e.chart,u=u&&u.options&&u.options.colors,k;if(a){k=q(a,{colors:u,index:d,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:c,parentColorIndex:b,series:e,siblings:g});if(c=e.points[a.i])c.color=k.color,c.colorIndex=k.colorIndex;p(a.children||[],function(c,b){e.setColorRecursive(c,k.color,k.colorIndex,b,a.children.length)})}},algorithmGroup:function(a,c,b,u){this.height=
a;this.width=c;this.plot=u;this.startDirection=this.direction=b;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=
this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,c,b,u){var e,d,f,k,l=b.lW,h=b.lH,w=b.plot,q,r=0,n=b.elArr.length-1;c?(l=b.nW,h=b.nH):q=b.elArr[b.elArr.length-1];p(b.elArr,function(a){if(c||
r<n)0===b.direction?(e=w.x,d=w.y,f=l,k=a/f):(e=w.x,d=w.y,k=h,f=a/k),u.push({x:e,y:d,width:f,height:k}),0===b.direction?w.y+=k:w.x+=f;r+=1});b.reset();0===b.direction?b.width-=l:b.height-=h;w.y=w.parent.y+(w.parent.height-b.height);w.x=w.parent.x+(w.parent.width-b.width);a&&(b.direction=1-b.direction);c||b.addElement(q)},algorithmLowAspectRatio:function(a,b,e){var c=[],d=this,m,f={x:b.x,y:b.y,parent:b},k=0,l=e.length-1,h=new this.algorithmGroup(b.height,b.width,b.direction,f);p(e,function(e){m=e.val/
b.val*b.height*b.width;h.addElement(m);h.lP.nR>h.lP.lR&&d.algorithmCalcPoints(a,!1,h,c,f);k===l&&d.algorithmCalcPoints(a,!0,h,c,f);k+=1});return c},algorithmFill:function(a,b,e){var c=[],d,m=b.direction,f=b.x,k=b.y,h=b.width,l=b.height,q,r,n,t;p(e,function(e){d=e.val/b.val*b.height*b.width;q=f;r=k;0===m?(t=l,n=d/t,h-=n,f+=n):(n=h,t=d/n,l-=t,k+=t);c.push({x:q,y:r,width:n,height:t});a&&(m=1-m)});return c},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,
a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,e=J(a),d,g;f.prototype.translate.call(a);g=a.tree=a.getTree();d=a.nodeMap[e];a.mapOptionsToLevel=r({from:d.level+1,levels:b.levels,to:g.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===e||d&&d.children.length||(a.drillToNode("",!1),e=a.rootNode,d=a.nodeMap[e]);B(a.nodeMap[a.rootNode],function(b){var c=
!1,e=b.parent;b.visible=!0;if(e||""===e)c=a.nodeMap[e];return c});B(a.nodeMap[a.rootNode].children,function(a){var b=!1;p(a,function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(g);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=e={x:0,y:0,width:100,height:100};a.nodeMap[""].values=e=n(e,{width:e.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:g.val});a.calculateChildrenAreas(g,e);a.colorAxis?a.translateColors():
b.colorByPoint||a.setColorRecursive(a.tree);b.allowDrillToNode&&(b=d.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,e=y(a.points,function(a){return a.node.visible}),d,g;p(e,function(c){g=b[c.node.level];d={style:{}};c.node.isLeaf||(d.enabled=!1);g&&g.dataLabels&&(d=n(d,g.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(d.style.width=c.shapeArgs.width,
c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=n(d,c.options.dataLabels)});f.prototype.drawDataLabels.call(this)},alignDataLabel:function(a){d.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=G(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{},c=this.options,g=b&&c.states[b]||{},f=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||
g.borderColor||c.borderColor,"stroke-width":v(a&&a.borderWidth,d.borderWidth,g.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||g.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==f.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==f.indexOf("highcharts-internal-node-interactive")?(b=v(g.opacity,c.opacity),a.fill=h(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==f.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=
h(a.fill).brighten(g.brightness).get());return a},drawPoints:function(){var a=this,b=y(a.points,function(a){return a.node.visible});p(b,function(b){var c="level-group-"+b.node.levelDynamic;a[c]||(a[c]=a.chart.renderer.g(c).attr({zIndex:1E3-b.node.levelDynamic}).add(a.group));b.group=a[c]});d.column.prototype.drawPoints.call(this);a.options.allowDrillToNode&&p(b,function(b){b.graphic&&(b.drillId=a.options.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=
(a=a.point)&&a.drillId;A(b)&&(a.setState(""),this.drillToNode(b))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&A(a.parent)&&this.drillToNode(a.parent)},drillToNode:function(a,b){var c=this.nodeMap[a];
this.idPreviousRoot=this.rootNode;this.rootNode=a;""===a?this.drillUpButton=this.drillUpButton.destroy():this.showDrillUpButton(c&&c.name||a);this.isDirty=!0;v(b,!0)&&this.chart.redraw()},showDrillUpButton:function(a){var b=this;a=a||"\x3c Back";var d=b.options.drillUpButton,f,g;d.text&&(a=d.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:a}).align()):(g=(f=d.theme)&&f.states,this.drillUpButton=this.chart.renderer.button(a,null,null,function(){b.drillUp()},f,g&&
g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:d.position.align,zIndex:7}).add().align(d.position,!1,d.relativeTo||"plotBox"))},buildKDTree:z,drawLegendSymbol:b.LegendSymbolMixin?b.LegendSymbolMixin.drawRectangle:void 0,getExtremes:function(){f.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;f.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,
min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};f.prototype.bindAxes.call(this);b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,a)},utils:{recursive:B,reduce:E}},{getClassName:function(){var a=b.Point.prototype.getClassName.call(this),c=this.series,d=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||v(d.interactByLeaf,!d.allowDrillToNode)?this.node.isLeaf||(a+=" highcharts-internal-node"):
a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||l(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:d.pie.prototype.pointClass.prototype.setVisible})})(x,G)});
