/*
  Highcharts JS v6.1.0-modified (2018-06-14)

 Indicator series type for Highstock

 (c) 2010-2017 Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(m){"object"===typeof module&&module.exports?module.exports=m:m(Highcharts)})(function(m){(function(b){function m(e,b,g,h,a,d,c,n){e=0>c?g[h-1]:g[h-1][c];return[b[h-1],void 0===d?n:e*a+d*(1-a)]}var q=b.isArray;b=b.seriesType;b("ema","sma",{params:{index:0,period:14}},{getValues:function(e,b){var g=b.period,h=e.xData,a=(e=e.yData)?e.length:0,d=2/(g+1),c=0,n=0,u=[],r=[],k=[],f=-1,t=[],l;if(h.length<g)return!1;for(q(e[0])&&(f=b.index?b.index:0);c<g;)t.push([h[c],0>f?e[c]:e[c][f]]),n+=0>f?e[c]:
e[c][f],c++;b=n/g;for(g=c;g<a;g++)l=m(t,h,e,g,d,l,f,b),u.push(l),r.push(l[0]),k.push(l[1]),l=l[1],t.push([h[g],0>f?e[g]:e[g][f]]);l=m(t,h,e,g,d,l,f);u.push(l);r.push(l[0]);k.push(l[1]);return{values:u,xData:r,yData:k}}})})(m);(function(b){var m=b.seriesType,q=b.each,e=b.merge,p=b.defined,g=b.seriesTypes.sma,h=b.seriesTypes.ema;m("macd","sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,
lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eValue: {point.MACD}\x3cbr/\x3eSignal: {point.signal}\x3cbr/\x3eHistogram: {point.y}\x3cbr/\x3e'},dataGrouping:{approximation:"averages"},minPointLength:0},{nameComponents:["longPeriod","shortPeriod","signalPeriod"],pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal",
"MACD"],pointValKey:"y",markerAttribs:b.noop,getColumnMetrics:b.seriesTypes.column.prototype.getColumnMetrics,crispCol:b.seriesTypes.column.prototype.crispCol,init:function(){g.prototype.init.apply(this,arguments);this.options=e({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options);this.macdZones={zones:this.options.macdLine.zones,startIndex:0};this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length};
this.resetZones=!0},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,d=["plotSignal","plotMACD"];b.seriesTypes.column.prototype.translate.apply(a);q(a.points,function(c){q([c.signal,c.MACD],function(n,b){null!==n&&(c[d[b]]=a.yAxis.toPixels(n,!0))})})},destroy:function(){this.graph=null;this.graphmacd=this.graphmacd.destroy();this.graphsignal=this.graphsignal.destroy();g.prototype.destroy.apply(this,arguments)},drawPoints:b.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var a=
this,d=a.points,c=d.length,b=a.options,h=a.zones,r={options:{gapSize:b.gapSize}},k=[[],[]],f;c--;)f=d[c],p(f.plotMACD)&&k[0].push({plotX:f.plotX,plotY:f.plotMACD,isNull:!p(f.plotMACD)}),p(f.plotSignal)&&k[1].push({plotX:f.plotX,plotY:f.plotSignal,isNull:!p(f.plotMACD)});q(["macd","signal"],function(c,d){a.points=k[d];a.options=e(b[c+"Line"].styles,r);a.graph=a["graph"+c];a.currentLineZone=c+"Zones";a.zones=a[a.currentLineZone].zones;g.prototype.drawGraph.call(a);a["graph"+c]=a.graph});a.points=d;
a.options=b;a.zones=h;a.currentLineZone=null},getZonesGraphs:function(a){var d=g.prototype.getZonesGraphs.call(this,a),c=d;this.currentLineZone&&(c=d.splice(this[this.currentLineZone].startIndex+1),c.length?c.splice(0,0,a[0]):c=[a[0]]);return c},applyZones:function(){var a=this.zones;this.zones=this.signalZones.zones;g.prototype.applyZones.call(this);this.options.macdLine.zones.length&&this.graphmacd.hide();this.zones=a},getValues:function(a,d){var c=0,b=[],g=[],e=[],k,f;if(a.xData.length<d.longPeriod)return!1;
k=h.prototype.getValues(a,{period:d.shortPeriod});f=h.prototype.getValues(a,{period:d.longPeriod});k=k.values;f=f.values;for(a=1;a<=k.length;a++)p(f[a-1])&&p(f[a-1][1])&&b.push([k[a+d.shortPeriod+1][0],0,null,k[a+d.shortPeriod+1][1]-f[a-1][1]]);for(a=0;a<b.length;a++)g.push(b[a][0]),e.push([0,null,b[a][3]]);d=h.prototype.getValues({xData:g,yData:e},{period:d.signalPeriod,index:2});d=d.values;for(a=0;a<b.length;a++)b[a][0]>=d[0][0]&&(b[a][2]=d[c][1],e[a]=[0,d[c][1],b[a][3]],null===b[a][3]?(b[a][1]=
0,e[a][0]=0):(b[a][1]=b[a][3]-d[c][1],e[a][0]=b[a][3]-d[c][1]),c++);return{values:b,xData:g,yData:e}}})})(m)});
