/*
 Highcharts JS v6.1.0-modified (2018-06-16)
 Exporting module

 (c) 2010-2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(n){"object"===typeof module&&module.exports?module.exports=n:n(Highcharts)})(function(n){(function(f){var n=f.defaultOptions,w=f.doc,x=f.Chart,u=f.addEvent,J=f.removeEvent,D=f.fireEvent,q=f.createElement,E=f.discardElement,F=f.css,y=f.merge,B=f.pick,v=f.each,G=f.objectEach,A=f.extend,z=f.win,I=z.navigator.userAgent,H=f.SVGRenderer,K=f.Renderer.prototype.symbols,L=/Edge\/|Trident\/|MSIE /.test(I),M=/firefox/i.test(I);A(n.lang,{printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",
downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});n.navigation={buttonOptions:{theme:{},symbolSize:14,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,verticalAlign:"top",width:24}};n.exporting={type:"image/png",url:"https://export.highcharts.com/",printMaxWidth:780,scale:2,buttons:{contextButton:{className:"highcharts-contextbutton",menuClassName:"highcharts-contextmenu",symbol:"menu",_titleKey:"contextButtonTitle",
menuItems:"printChart separator downloadPNG downloadJPEG downloadPDF downloadSVG".split(" ")}},menuItemDefinitions:{printChart:{textKey:"printChart",onclick:function(){this.print()}},separator:{separator:!0},downloadPNG:{textKey:"downloadPNG",onclick:function(){this.exportChart()}},downloadJPEG:{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},downloadPDF:{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},downloadSVG:{textKey:"downloadSVG",
onclick:function(){this.exportChart({type:"image/svg+xml"})}}}};f.post=function(a,b,c){var d=q("form",y({method:"post",action:a,enctype:"multipart/form-data"},c),{display:"none"},w.body);G(b,function(a,b){q("input",{type:"hidden",name:b,value:a},null,d)});d.submit();E(d)};A(x.prototype,{sanitizeSVG:function(a,b){if(b&&b.exporting&&b.exporting.allowHTML){var c=a.match(/<\/svg>(.*?$)/);c&&c[1]&&(c='\x3cforeignObject x\x3d"0" y\x3d"0" width\x3d"'+b.chart.width+'" height\x3d"'+b.chart.height+'"\x3e\x3cbody xmlns\x3d"http://www.w3.org/1999/xhtml"\x3e'+
c[1]+"\x3c/body\x3e\x3c/foreignObject\x3e",a=a.replace("\x3c/svg\x3e",c+"\x3c/svg\x3e"))}return a=a.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\(("|&quot;)(\S+)("|&quot;)\)/g,"url($2)").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'\x3csvg xmlns:xlink\x3d"http://www.w3.org/1999/xlink" ').replace(/ (|NS[0-9]+\:)href=/g," xlink:href\x3d").replace(/\n/," ").replace(/<\/svg>.*?$/,"\x3c/svg\x3e").replace(/(fill|stroke)="rgba\(([ 0-9]+,[ 0-9]+,[ 0-9]+),([ 0-9\.]+)\)"/g,
'$1\x3d"rgb($2)" $1-opacity\x3d"$3"').replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad")},getChartHTML:function(){this.inlineStyles();return this.container.innerHTML},getSVG:function(a){var b,c,d,r,h,g=y(this.options,a);c=q("div",null,{position:"absolute",top:"-9999em",width:this.chartWidth+"px",height:this.chartHeight+"px"},w.body);d=this.renderTo.style.width;h=this.renderTo.style.height;d=g.exporting.sourceWidth||g.chart.width||/px$/.test(d)&&parseInt(d,10)||600;h=g.exporting.sourceHeight||
g.chart.height||/px$/.test(h)&&parseInt(h,10)||400;A(g.chart,{animation:!1,renderTo:c,forExport:!0,renderer:"SVGRenderer",width:d,height:h});g.exporting.enabled=!1;delete g.data;g.series=[];v(this.series,function(a){r=y(a.userOptions,{animation:!1,enableMouseTracking:!1,showCheckbox:!1,visible:a.visible});r.isInternal||g.series.push(r)});v(this.axes,function(a){a.userOptions.internalKey||(a.userOptions.internalKey=f.uniqueKey())});b=new f.Chart(g,this.callback);a&&v(["xAxis","yAxis","series"],function(d){var c=
{};a[d]&&(c[d]=a[d],b.update(c))});v(this.axes,function(a){var d=f.find(b.axes,function(b){return b.options.internalKey===a.userOptions.internalKey}),c=a.getExtremes(),e=c.userMin,c=c.userMax;!d||void 0===e&&void 0===c||d.setExtremes(e,c,!0,!1)});d=b.getChartHTML();D(this,"getSVG",{chartCopy:b});d=this.sanitizeSVG(d,g);g=null;b.destroy();E(c);return d},getSVGForExport:function(a,b){var c=this.options.exporting;return this.getSVG(y({chart:{borderRadius:0}},c.chartOptions,b,{exporting:{sourceWidth:a&&
a.sourceWidth||c.sourceWidth,sourceHeight:a&&a.sourceHeight||c.sourceHeight}}))},exportChart:function(a,b){b=this.getSVGForExport(a,b);a=y(this.options.exporting,a);f.post(a.url,{filename:a.filename||"chart",type:a.type,width:a.width||0,scale:a.scale,svg:b},a.formAttributes)},print:function(){var a=this,b=a.container,c=[],d=b.parentNode,f=w.body,h=f.childNodes,g=a.options.exporting.printMaxWidth,e,k;if(!a.isPrinting){a.isPrinting=!0;a.pointer.reset(null,0);D(a,"beforePrint");if(k=g&&a.chartWidth>
g)e=[a.options.chart.width,void 0,!1],a.setSize(g,void 0,!1);v(h,function(a,b){1===a.nodeType&&(c[b]=a.style.display,a.style.display="none")});f.appendChild(b);z.focus();z.print();setTimeout(function(){d.appendChild(b);v(h,function(a,b){1===a.nodeType&&(a.style.display=c[b])});a.isPrinting=!1;k&&a.setSize.apply(a,e);D(a,"afterPrint")},1E3)}},contextMenu:function(a,b,c,d,r,h,g){var e=this,k=e.chartWidth,p=e.chartHeight,t="cache-"+a,l=e[t],m=Math.max(r,h),C,n;l||(e[t]=l=q("div",{className:a},{position:"absolute",
zIndex:1E3,padding:m+"px",pointerEvents:"auto"},e.fixedDiv||e.container),C=q("div",{className:"highcharts-menu"},null,l),n=function(){F(l,{display:"none"});g&&g.setState(0);e.openMenu=!1},e.exportEvents.push(u(l,"mouseleave",function(){l.hideTimer=setTimeout(n,500)}),u(l,"mouseenter",function(){f.clearTimeout(l.hideTimer)}),u(w,"mouseup",function(b){e.pointer.inClass(b.target,a)||n()})),v(b,function(a){"string"===typeof a&&(a=e.options.exporting.menuItemDefinitions[a]);if(f.isObject(a,!0)){var b;
b=a.separator?q("hr",null,null,C):q("div",{className:"highcharts-menu-item",onclick:function(b){b&&b.stopPropagation();n();a.onclick&&a.onclick.apply(e,arguments)},innerHTML:a.text||e.options.lang[a.textKey]},null,C);e.exportDivElements.push(b)}}),e.exportDivElements.push(C,l),e.exportMenuWidth=l.offsetWidth,e.exportMenuHeight=l.offsetHeight);b={display:"block"};c+e.exportMenuWidth>k?b.right=k-c-r-m+"px":b.left=c-m+"px";d+h+e.exportMenuHeight>p&&"top"!==g.alignOptions.verticalAlign?b.bottom=p-d-m+
"px":b.top=d+h-m+"px";F(l,b);e.openMenu=!0},addButton:function(a){var b=this,c=b.renderer,d=y(b.options.navigation.buttonOptions,a),f=d.onclick,h=d.menuItems,g,e,k=d.symbolSize||12;b.btnCount||(b.btnCount=0);b.exportDivElements||(b.exportDivElements=[],b.exportSVGElements=[]);if(!1!==d.enabled){var p=d.theme,t=p.states,l=t&&t.hover,t=t&&t.select,m;delete p.states;f?m=function(a){a.stopPropagation();f.call(b,a)}:h&&(m=function(){b.contextMenu(e.menuClassName,h,e.translateX,e.translateY,e.width,e.height,
e);e.setState(2)});d.text&&d.symbol?p.paddingLeft=B(p.paddingLeft,25):d.text||A(p,{width:d.width,height:d.height,padding:0});e=c.button(d.text,0,0,m,p,l,t).addClass(a.className).attr({title:B(b.options.lang[d._titleKey],"")});e.menuClassName=a.menuClassName||"highcharts-menu-"+b.btnCount++;d.symbol&&(g=c.symbol(d.symbol,d.symbolX-k/2,d.symbolY-k/2,k,k,{width:k,height:k}).addClass("highcharts-button-symbol").attr({zIndex:1}).add(e));e.add(b.exportingGroup).align(A(d,{width:e.width,x:B(d.x,b.buttonOffset)}),
!0,"spacingBox");b.buttonOffset+=(e.width+d.buttonSpacing)*("right"===d.align?-1:1);b.exportSVGElements.push(e,g)}},destroyExport:function(a){var b=a?a.target:this;a=b.exportSVGElements;var c=b.exportDivElements,d=b.exportEvents,r;a&&(v(a,function(a,d){a&&(a.onclick=a.ontouchstart=null,r="cache-"+a.menuClassName,b[r]&&delete b[r],b.exportSVGElements[d]=a.destroy())}),a.length=0);b.exportingGroup&&(b.exportingGroup.destroy(),delete b.exportingGroup);c&&(v(c,function(a,d){f.clearTimeout(a.hideTimer);
J(a,"mouseleave");b.exportDivElements[d]=a.onmouseout=a.onmouseover=a.ontouchstart=a.onclick=null;E(a)}),c.length=0);d&&(v(d,function(a){a()}),d.length=0)}});H.prototype.inlineToAttributes="fill stroke strokeLinecap strokeLinejoin strokeWidth textAnchor x y".split(" ");H.prototype.inlineBlacklist=[/-/,/^(clipPath|cssText|d|height|width)$/,/^font$/,/[lL]ogical(Width|Height)$/,/perspective/,/TapHighlightColor/,/^transition/,/^length$/];H.prototype.unstyledElements=["clipPath","defs","desc"];x.prototype.inlineStyles=
function(){function a(a){return a.replace(/([A-Z])/g,function(a,b){return"-"+b.toLowerCase()})}function b(c){function l(b,g){q=w=!1;if(h){for(u=h.length;u--&&!w;)w=h[u].test(g);q=!w}"transform"===g&&"none"===b&&(q=!0);for(u=f.length;u--&&!q;)q=f[u].test(g)||"function"===typeof b;q||n[g]===b&&"svg"!==c.nodeName||e[c.nodeName][g]===b||(-1!==d.indexOf(g)?c.setAttribute(a(g),b):r+=a(g)+":"+b+";")}var m,n,r="",t,q,w,u;if(1===c.nodeType&&-1===g.indexOf(c.nodeName)){m=z.getComputedStyle(c,null);n="svg"===
c.nodeName?{}:z.getComputedStyle(c.parentNode,null);e[c.nodeName]||(k=p.getElementsByTagName("svg")[0],t=p.createElementNS(c.namespaceURI,c.nodeName),k.appendChild(t),e[c.nodeName]=y(z.getComputedStyle(t,null)),"text"===c.nodeName&&delete e.text.fill,k.removeChild(t));if(M||L)for(var x in m)l(m[x],x);else G(m,l);r&&(m=c.getAttribute("style"),c.setAttribute("style",(m?m+";":"")+r));"svg"===c.nodeName&&c.setAttribute("stroke-width","1px");"text"!==c.nodeName&&v(c.children||c.childNodes,b)}}var c=this.renderer,
d=c.inlineToAttributes,f=c.inlineBlacklist,h=c.inlineWhitelist,g=c.unstyledElements,e={},k,p,c=w.createElement("iframe");F(c,{width:"1px",height:"1px",visibility:"hidden"});w.body.appendChild(c);p=c.contentWindow.document;p.open();p.write('\x3csvg xmlns\x3d"http://www.w3.org/2000/svg"\x3e\x3c/svg\x3e');p.close();b(this.container.querySelector("svg"));k.parentNode.removeChild(k)};K.menu=function(a,b,c,d){return["M",a,b+2.5,"L",a+c,b+2.5,"M",a,b+d/2+.5,"L",a+c,b+d/2+.5,"M",a,b+d-1.5,"L",a+c,b+d-1.5]};
x.prototype.renderExporting=function(){var a=this,b=a.options.exporting,c=b.buttons,d=a.isDirtyExporting||!a.exportSVGElements;a.buttonOffset=0;a.isDirtyExporting&&a.destroyExport();d&&!1!==b.enabled&&(a.exportEvents=[],a.exportingGroup=a.exportingGroup||a.renderer.g("exporting-group").attr({zIndex:3}).add(),G(c,function(b){a.addButton(b)}),a.isDirtyExporting=!1);u(a,"destroy",a.destroyExport)};u(x,"init",function(){var a=this;v(["exporting","navigation"],function(b){a[b]={update:function(c,d){a.isDirtyExporting=
!0;y(!0,a.options[b],c);B(d,!0)&&a.redraw()}}})});x.prototype.callbacks.push(function(a){a.renderExporting();u(a,"redraw",a.renderExporting)})})(n)});
