/*
 Highcharts JS v6.1.0-modified (2018-06-16)

 (c) 2014 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(q){"object"===typeof module&&module.exports?module.exports=q:q(Highcharts)})(function(q){var D=function(a){var q=a.each,x=a.extend,c=a.isArray,k=a.isObject,r=a.isNumber,B=a.merge,y=a.pick,n=a.reduce;return{getColor:function(a,l){var h=l.mapOptionsToLevel,p=l.parentColorIndex,c=l.series,e=l.colors,t=c.points,C,n;a&&(t=t[a.i],h=h[a.level]||{},(a=t&&h.colorByPoint)&&(C=t.index%(e?e.length:c.chart.options.chart.colorCount)),n=y(t&&t.options.colorIndex,h&&h.colorIndex,C,p,l.colorIndex));return{color:void 0,
colorIndex:n}},getLevelOptions:function(a){var l=null,h,p,A,e;if(k(a))for(l={},A=r(a.from)?a.from:1,e=a.levels,p={},h=k(a.defaults)?a.defaults:{},c(e)&&(p=n(e,function(a,c){var l,e;k(c)&&r(c.level)&&(e=B({},c),l="boolean"===typeof e.levelIsConstant?e.levelIsConstant:h.levelIsConstant,delete e.levelIsConstant,delete e.level,c=c.level+(l?0:A-1),k(a[c])?x(a[c],e):a[c]=e);return a},{})),e=r(a.to)?a.to:1,a=0;a<=e;a++)l[a]=B({},h,k(p[a])?p[a]:{});return l},setTreeValues:function l(a,c){var h=c.before,e=
c.idRoot,n=c.mapIdToNode[e],k=c.points[a.i],r=k&&k.options||{},p=0,z=[];x(a,{levelDynamic:a.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:n.level),name:y(k&&k.name,""),visible:e===a.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof h&&(a=h(a,c));q(a.children,function(e,b){var f=x({},c);x(f,{index:b,siblings:a.children.length,visible:a.visible});e=l(e,f);z.push(e);e.visible&&(p+=e.val)});a.visible=0<p||a.visible;h=y(r.value,p);x(a,{children:z,childrenTotal:p,
isLeaf:a.visible&&!p,val:h});return a},updateRootId:function(a){var c;k(a)&&(c=k(a.options)?a.options:{},c=y(a.rootNode,c.rootId,""),k(a.userOptions)&&(a.userOptions.rootId=c),a.rootNode=c);return c}}}(q);(function(a,q){console.log(a);var x=a.seriesType,c=a.seriesTypes,k=a.map,r=a.merge,B=a.extend,y=a.noop,n=a.each,D=q.getColor,l=q.getLevelOptions,h=a.grep,p=a.isNumber,A=a.isString,e=a.pick,t=a.Series,C=a.stableSort,G=function(b,f,d){d=d||this;a.objectEach(b,function(a,g){f.call(d,a,g,b)})},F=a.reduce,
z=function(b,f,d){d=d||this;b=f.call(d,b);!1!==b&&z(b,f,d)},H=q.updateRootId;x("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,
drillUpButton:{position:{align:"right",x:-10,y:10}}},{pointArrayMap:["value"],axisTypes:c&&c.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:y,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",translateColors:c&&c.heatmap&&c.heatmap.prototype.translateColors,colorAttribs:c&&c.heatmap&&c.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(b,f){b=F(b||[],function(b,f,a){f=e(f.parent,
"");void 0===b[f]&&(b[f]=[]);b[f].push(a);return b},{});G(b,function(b,u,g){""!==u&&-1===a.inArray(u,f)&&(n(b,function(b){g[""].push(b)}),delete g[u])});return b},getTree:function(){var b=k(this.data,function(b){return b.id}),b=this.getListOfParents(this.data,b);this.nodeMap=[];return this.buildNode("",-1,0,b,null)},init:function(b,f){t.prototype.init.call(this,b,f);this.options.allowDrillToNode&&a.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(b,f,d,a,g){var w=this,u=[],c=w.points[f],
e=0,E;n(a[b]||[],function(f){E=w.buildNode(w.points[f].id,f,d+1,a,b);e=Math.max(E.height+1,e);u.push(E)});f={id:b,i:f,children:u,height:e,level:d,parent:g,visible:!1};w.nodeMap[f.id]=f;c&&(c.node=f);return f},setTreeValues:function(b){var f=this,d=f.options,a=f.nodeMap[f.rootNode],d="boolean"===typeof d.levelIsConstant?d.levelIsConstant:!0,g=0,w=[],c,m=f.points[b.i];n(b.children,function(b){b=f.setTreeValues(b);w.push(b);b.ignore||(g+=b.val)});C(w,function(b,f){return b.sortIndex-f.sortIndex});c=
e(m&&m.options.value,g);m&&(m.value=c);B(b,{children:w,childrenTotal:g,ignore:!(e(m&&m.visible,!0)&&0<c),isLeaf:b.visible&&!g,levelDynamic:b.level-(d?0:a.level),name:e(m&&m.name,""),sortIndex:e(m&&m.sortIndex,-c),val:c});return b},calculateChildrenAreas:function(b,f){var d=this,a=d.options,g=d.mapOptionsToLevel[b.level+1],c=e(d[g&&g.layoutAlgorithm]&&g.layoutAlgorithm,a.layoutAlgorithm),I=a.alternateStartingDirection,m=[];b=h(b.children,function(b){return!b.ignore});g&&g.layoutStartingDirection&&
(f.direction="vertical"===g.layoutStartingDirection?0:1);m=d[c](f,b);n(b,function(b,a){a=m[a];b.values=r(a,{val:b.childrenTotal,direction:I?1-f.direction:f.direction});b.pointValues=r(a,{x:a.x/d.axisRatio,width:a.width/d.axisRatio});b.children.length&&d.calculateChildrenAreas(b,b.values)})},setPointValues:function(){var b=this.xAxis,f=this.yAxis;n(this.points,function(d){var a=d.node,g=a.pointValues,c,e;g&&a.visible?(a=Math.round(b.translate(g.x,0,0,0,1))-0,c=Math.round(b.translate(g.x+g.width,0,
0,0,1))-0,e=Math.round(f.translate(g.y,0,0,0,1))-0,g=Math.round(f.translate(g.y+g.height,0,0,0,1))-0,d.shapeType="rect",d.shapeArgs={x:Math.min(a,c),y:Math.min(e,g),width:Math.abs(c-a),height:Math.abs(g-e)},d.plotX=d.shapeArgs.x+d.shapeArgs.width/2,d.plotY=d.shapeArgs.y+d.shapeArgs.height/2):(delete d.plotX,delete d.plotY)})},setColorRecursive:function(b,f,d,a,g){var c=this,e=c&&c.chart,e=e&&e.options&&e.options.colors,u;if(b){u=D(b,{colors:e,index:a,mapOptionsToLevel:c.mapOptionsToLevel,parentColor:f,
parentColorIndex:d,series:c,siblings:g});if(f=c.points[b.i])f.color=u.color,f.colorIndex=u.colorIndex;n(b.children||[],function(f,a){c.setColorRecursive(f,u.color,u.colorIndex,a,b.children.length)})}},algorithmGroup:function(b,f,a,c){this.height=b;this.width=f;this.plot=c;this.startDirection=this.direction=a;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(b,f){return Math.max(b/f,f/b)}};this.addElement=function(b){this.lP.total=
this.elArr[this.elArr.length-1];this.total+=b;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(b)};
this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(b,f,a,c){var d,e,u,m,h=a.lW,l=a.lH,v=a.plot,k,p=0,t=a.elArr.length-1;f?(h=a.nW,l=a.nH):k=a.elArr[a.elArr.length-1];n(a.elArr,function(b){if(f||p<t)0===a.direction?(d=v.x,e=v.y,u=h,m=b/u):(d=v.x,e=v.y,m=l,u=b/m),c.push({x:d,y:e,width:u,height:m}),0===a.direction?v.y+=m:v.x+=u;p+=1});a.reset();0===a.direction?a.width-=h:a.height-=l;v.y=v.parent.y+(v.parent.height-a.height);v.x=v.parent.x+(v.parent.width-
a.width);b&&(a.direction=1-a.direction);f||a.addElement(k)},algorithmLowAspectRatio:function(b,a,d){var f=[],c=this,e,h={x:a.x,y:a.y,parent:a},m=0,l=d.length-1,k=new this.algorithmGroup(a.height,a.width,a.direction,h);n(d,function(d){e=d.val/a.val*a.height*a.width;k.addElement(e);k.lP.nR>k.lP.lR&&c.algorithmCalcPoints(b,!1,k,f,h);m===l&&c.algorithmCalcPoints(b,!0,k,f,h);m+=1});return f},algorithmFill:function(b,a,d){var f=[],c,e=a.direction,h=a.x,m=a.y,k=a.width,l=a.height,p,t,q,r;n(d,function(d){c=
d.val/a.val*a.height*a.width;p=h;t=m;0===e?(r=l,q=c/r,k-=q,h+=q):(q=k,r=c/q,l-=r,m+=r);f.push({x:p,y:t,width:q,height:r});b&&(e=1-e)});return f},strip:function(b,a){return this.algorithmLowAspectRatio(!1,b,a)},squarified:function(b,a){return this.algorithmLowAspectRatio(!0,b,a)},sliceAndDice:function(b,a){return this.algorithmFill(!0,b,a)},stripes:function(b,a){return this.algorithmFill(!1,b,a)},translate:function(){var b=this,a=b.options,d=H(b),c,e;t.prototype.translate.call(b);e=b.tree=b.getTree();
c=b.nodeMap[d];b.mapOptionsToLevel=l({from:c.level+1,levels:a.levels,to:e.height,defaults:{levelIsConstant:b.options.levelIsConstant,colorByPoint:a.colorByPoint}});""===d||c&&c.children.length||(b.drillToNode("",!1),d=b.rootNode,c=b.nodeMap[d]);z(b.nodeMap[b.rootNode],function(a){var f=!1,d=a.parent;a.visible=!0;if(d||""===d)f=b.nodeMap[d];return f});z(b.nodeMap[b.rootNode].children,function(b){var a=!1;n(b,function(b){b.visible=!0;b.children.length&&(a=(a||[]).concat(b.children))});return a});b.setTreeValues(e);
b.axisRatio=b.xAxis.len/b.yAxis.len;b.nodeMap[""].pointValues=d={x:0,y:0,width:100,height:100};b.nodeMap[""].values=d=r(d,{width:d.width*b.axisRatio,direction:"vertical"===a.layoutStartingDirection?0:1,val:e.val});b.calculateChildrenAreas(e,d);b.colorAxis?b.translateColors():a.colorByPoint||b.setColorRecursive(b.tree);a.allowDrillToNode&&(a=c.pointValues,b.xAxis.setExtremes(a.x,a.x+a.width,!1),b.yAxis.setExtremes(a.y,a.y+a.height,!1),b.xAxis.setScale(),b.yAxis.setScale());b.setPointValues()},drawDataLabels:function(){var b=
this,a=b.mapOptionsToLevel,d=h(b.points,function(b){return b.node.visible}),c,e;n(d,function(d){e=a[d.node.level];c={style:{}};d.node.isLeaf||(c.enabled=!1);e&&e.dataLabels&&(c=r(c,e.dataLabels),b._hasPointLabels=!0);d.shapeArgs&&(c.style.width=d.shapeArgs.width,d.dataLabel&&d.dataLabel.css({width:d.shapeArgs.width+"px"}));d.dlOptions=r(c,d.options.dataLabels)});t.prototype.drawDataLabels.call(this)},alignDataLabel:function(b){c&&c.column&&c.column.prototype.alignDataLabel.apply(this,arguments);b.dataLabel&&
b.dataLabel.attr({zIndex:(b.node.zIndex||0)+1})},drawPoints:function(){var b=this,a=h(b.points,function(b){return b.node.visible});n(a,function(a){var d="level-group-"+a.node.levelDynamic;b[d]||(b[d]=b.chart.renderer.g(d).attr({zIndex:1E3-a.node.levelDynamic}).add(b.group));a.group=b[d]});c&&c.column&&c.column.prototype.drawPoints.call(this);this.colorAttribs&&n(this.points,function(b){b.graphic&&b.graphic.css(this.colorAttribs(b))},this);b.options.allowDrillToNode&&n(a,function(a){a.graphic&&(a.drillId=
b.options.interactByLeaf?b.drillToByLeaf(a):b.drillToByGroup(a))})},onClickDrillToNode:function(b){var a=(b=b.point)&&b.drillId;A(a)&&(b.setState(""),this.drillToNode(a))},drillToByGroup:function(b){var a=!1;1!==b.node.level-this.nodeMap[this.rootNode].level||b.node.isLeaf||(a=b.id);return a},drillToByLeaf:function(b){var a=!1;if(b.node.parent!==this.rootNode&&b.node.isLeaf)for(b=b.node;!a;)b=this.nodeMap[b.parent],b.parent===this.rootNode&&(a=b.id);return a},drillUp:function(){var b=this.nodeMap[this.rootNode];
b&&A(b.parent)&&this.drillToNode(b.parent)},drillToNode:function(b,a){var c=this.nodeMap[b];this.idPreviousRoot=this.rootNode;this.rootNode=b;""===b?this.drillUpButton=this.drillUpButton.destroy():this.showDrillUpButton(c&&c.name||b);this.isDirty=!0;e(a,!0)&&this.chart.redraw()},showDrillUpButton:function(b){var a=this;b=b||"\x3c Back";var c=a.options.drillUpButton,e,g;c.text&&(b=c.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:b}).align()):(g=(e=c.theme)&&e.states,
this.drillUpButton=this.chart.renderer.button(b,null,null,function(){a.drillUp()},e,g&&g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:c.position.align,zIndex:7}).add().align(c.position,!1,c.relativeTo||"plotBox"))},buildKDTree:y,drawLegendSymbol:a.LegendSymbolMixin?a.LegendSymbolMixin.drawRectangle:void 0,getExtremes:function(){t.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;t.prototype.getExtremes.call(this)},getExtremesFromAll:!0,
bindAxes:function(){var b={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};t.prototype.bindAxes.call(this);a.extend(this.yAxis.options,b);a.extend(this.xAxis.options,b)},utils:{recursive:z,reduce:F}},{getClassName:function(){var b=a.Point.prototype.getClassName.call(this),c=this.series,d=c.options;this.node.level<=c.nodeMap[c.rootNode].level?b+=" highcharts-above-level":this.node.isLeaf||e(d.interactByLeaf,
!d.allowDrillToNode)?this.node.isLeaf||(b+=" highcharts-internal-node"):b+=" highcharts-internal-node-interactive";return b},isValid:function(){return this.id||p(this.value)},setState:function(b){a.Point.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})},setVisible:c?c.pie.prototype.pointClass.prototype.setVisible:void 0})})(q,D)});
