/*
 Highcharts JS v6.1.0-modified (2018-06-15)

 (c) 2014 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(q){"object"===typeof module&&module.exports?module.exports=q:q(Highcharts)})(function(q){var D=function(b){var q=b.each,x=b.extend,d=b.isArray,k=b.isObject,r=b.isNumber,B=b.merge,y=b.pick,n=b.reduce;return{getColor:function(b,l){var h=l.mapOptionsToLevel,p=l.parentColorIndex,d=l.series,f=l.colors,t=d.points,C,n;b&&(t=t[b.i],h=h[b.level]||{},(b=t&&h.colorByPoint)&&(C=t.index%(f?f.length:d.chart.options.chart.colorCount)),n=y(t&&t.options.colorIndex,h&&h.colorIndex,C,p,l.colorIndex));return{color:void 0,
colorIndex:n}},getLevelOptions:function(b){var l=null,h,p,A,f;if(k(b))for(l={},A=r(b.from)?b.from:1,f=b.levels,p={},h=k(b.defaults)?b.defaults:{},d(f)&&(p=n(f,function(b,d){var l,f;k(d)&&r(d.level)&&(f=B({},d),l="boolean"===typeof f.levelIsConstant?f.levelIsConstant:h.levelIsConstant,delete f.levelIsConstant,delete f.level,d=d.level+(l?0:A-1),k(b[d])?x(b[d],f):b[d]=f);return b},{})),f=r(b.to)?b.to:1,b=0;b<=f;b++)l[b]=B({},h,k(p[b])?p[b]:{});return l},setTreeValues:function l(b,d){var h=d.before,f=
d.idRoot,n=d.mapIdToNode[f],k=d.points[b.i],r=k&&k.options||{},p=0,z=[];x(b,{levelDynamic:b.level-(("boolean"===typeof d.levelIsConstant?d.levelIsConstant:1)?0:n.level),name:y(k&&k.name,""),visible:f===b.id||("boolean"===typeof d.visible?d.visible:!1)});"function"===typeof h&&(b=h(b,d));q(b.children,function(f,a){var c=x({},d);x(c,{index:a,siblings:b.children.length,visible:b.visible});f=l(f,c);z.push(f);f.visible&&(p+=f.val)});b.visible=0<p||b.visible;h=y(r.value,p);x(b,{children:z,childrenTotal:p,
isLeaf:b.visible&&!p,val:h});return b},updateRootId:function(b){var d;k(b)&&(d=k(b.options)?b.options:{},d=y(b.rootNode,d.rootId,""),k(b.userOptions)&&(b.userOptions.rootId=d),b.rootNode=d);return d}}}(q);(function(b,q){var x=b.seriesType,d=b.seriesTypes,k=b.map,r=b.merge,B=b.extend,y=b.noop,n=b.each,D=q.getColor,l=q.getLevelOptions,h=b.grep,p=b.isNumber,A=b.isString,f=b.pick,t=b.Series,C=b.stableSort,G=function(a,c,e){e=e||this;b.objectEach(a,function(b,g){c.call(e,b,g,a)})},F=b.reduce,z=function(a,
c,e){e=e||this;a=c.call(e,a);!1!==a&&z(a,c,e)},H=q.updateRootId;x("treemap","scatter",{showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{enabled:!0,defer:!1,verticalAlign:"middle",formatter:function(){return this.point.name||this.point.id},inside:!0},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",
x:-10,y:10}}},{pointArrayMap:["value"],axisTypes:d&&d.heatmap?["xAxis","yAxis","colorAxis"]:["xAxis","yAxis"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:y,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",translateColors:d&&d.heatmap&&d.heatmap.prototype.translateColors,colorAttribs:d&&d.heatmap&&d.heatmap.prototype.colorAttribs,trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=F(a||[],function(a,c,b){c=f(c.parent,"");void 0===a[c]&&(a[c]=[]);a[c].push(b);
return a},{});G(a,function(a,u,g){""!==u&&-1===b.inArray(u,c)&&(n(a,function(a){g[""].push(a)}),delete g[u])});return a},getTree:function(){var a=k(this.data,function(a){return a.id}),a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},init:function(a,c){t.prototype.init.call(this,a,c);this.options.allowDrillToNode&&b.addEvent(this,"click",this.onClickDrillToNode)},buildNode:function(a,c,e,b,g){var w=this,u=[],d=w.points[c],f=0,E;n(b[a]||[],function(c){E=w.buildNode(w.points[c].id,
c,e+1,b,a);f=Math.max(E.height+1,f);u.push(E)});c={id:a,i:c,children:u,height:f,level:e,parent:g,visible:!1};w.nodeMap[c.id]=c;d&&(d.node=c);return c},setTreeValues:function(a){var c=this,e=c.options,b=c.nodeMap[c.rootNode],e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0,g=0,w=[],d,m=c.points[a.i];n(a.children,function(a){a=c.setTreeValues(a);w.push(a);a.ignore||(g+=a.val)});C(w,function(a,c){return a.sortIndex-c.sortIndex});d=f(m&&m.options.value,g);m&&(m.value=d);B(a,{children:w,childrenTotal:g,
ignore:!(f(m&&m.visible,!0)&&0<d),isLeaf:a.visible&&!g,levelDynamic:a.level-(e?0:b.level),name:f(m&&m.name,""),sortIndex:f(m&&m.sortIndex,-d),val:d});return a},calculateChildrenAreas:function(a,c){var e=this,b=e.options,g=e.mapOptionsToLevel[a.level+1],d=f(e[g&&g.layoutAlgorithm]&&g.layoutAlgorithm,b.layoutAlgorithm),I=b.alternateStartingDirection,m=[];a=h(a.children,function(a){return!a.ignore});g&&g.layoutStartingDirection&&(c.direction="vertical"===g.layoutStartingDirection?0:1);m=e[d](c,a);n(a,
function(a,b){b=m[b];a.values=r(b,{val:a.childrenTotal,direction:I?1-c.direction:c.direction});a.pointValues=r(b,{x:b.x/e.axisRatio,width:b.width/e.axisRatio});a.children.length&&e.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this.xAxis,c=this.yAxis;n(this.points,function(e){var b=e.node,g=b.pointValues,d,f;g&&b.visible?(b=Math.round(a.translate(g.x,0,0,0,1))-0,d=Math.round(a.translate(g.x+g.width,0,0,0,1))-0,f=Math.round(c.translate(g.y,0,0,0,1))-0,g=Math.round(c.translate(g.y+
g.height,0,0,0,1))-0,e.shapeType="rect",e.shapeArgs={x:Math.min(b,d),y:Math.min(f,g),width:Math.abs(d-b),height:Math.abs(g-f)},e.plotX=e.shapeArgs.x+e.shapeArgs.width/2,e.plotY=e.shapeArgs.y+e.shapeArgs.height/2):(delete e.plotX,delete e.plotY)})},setColorRecursive:function(a,c,e,b,g){var d=this,f=d&&d.chart,f=f&&f.options&&f.options.colors,u;if(a){u=D(a,{colors:f,index:b,mapOptionsToLevel:d.mapOptionsToLevel,parentColor:c,parentColorIndex:e,series:d,siblings:g});if(c=d.points[a.i])c.color=u.color,
c.colorIndex=u.colorIndex;n(a.children||[],function(c,e){d.setColorRecursive(c,u.color,u.colorIndex,e,a.children.length)})}},algorithmGroup:function(a,c,e,b){this.height=a;this.width=c;this.plot=b;this.startDirection=this.direction=e;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=
this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=
0}},algorithmCalcPoints:function(a,c,e,b){var d,f,u,m,h=e.lW,l=e.lH,v=e.plot,k,p=0,t=e.elArr.length-1;c?(h=e.nW,l=e.nH):k=e.elArr[e.elArr.length-1];n(e.elArr,function(a){if(c||p<t)0===e.direction?(d=v.x,f=v.y,u=h,m=a/u):(d=v.x,f=v.y,m=l,u=a/m),b.push({x:d,y:f,width:u,height:m}),0===e.direction?v.y+=m:v.x+=u;p+=1});e.reset();0===e.direction?e.width-=h:e.height-=l;v.y=v.parent.y+(v.parent.height-e.height);v.x=v.parent.x+(v.parent.width-e.width);a&&(e.direction=1-e.direction);c||e.addElement(k)},algorithmLowAspectRatio:function(a,
c,b){var e=[],d=this,f,h={x:c.x,y:c.y,parent:c},m=0,l=b.length-1,k=new this.algorithmGroup(c.height,c.width,c.direction,h);n(b,function(b){f=b.val/c.val*c.height*c.width;k.addElement(f);k.lP.nR>k.lP.lR&&d.algorithmCalcPoints(a,!1,k,e,h);m===l&&d.algorithmCalcPoints(a,!0,k,e,h);m+=1});return e},algorithmFill:function(a,c,b){var e=[],d,f=c.direction,h=c.x,m=c.y,k=c.width,l=c.height,p,t,q,r;n(b,function(b){d=b.val/c.val*c.height*c.width;p=h;t=m;0===f?(r=l,q=d/r,k-=q,h+=q):(q=k,r=d/q,l-=r,m+=r);e.push({x:p,
y:t,width:q,height:r});a&&(f=1-f)});return e},strip:function(a,c){return this.algorithmLowAspectRatio(!1,a,c)},squarified:function(a,c){return this.algorithmLowAspectRatio(!0,a,c)},sliceAndDice:function(a,c){return this.algorithmFill(!0,a,c)},stripes:function(a,c){return this.algorithmFill(!1,a,c)},translate:function(){var a=this,c=a.options,b=H(a),d,f;t.prototype.translate.call(a);f=a.tree=a.getTree();d=a.nodeMap[b];a.mapOptionsToLevel=l({from:d.level+1,levels:c.levels,to:f.height,defaults:{levelIsConstant:a.options.levelIsConstant,
colorByPoint:c.colorByPoint}});""===b||d&&d.children.length||(a.drillToNode("",!1),b=a.rootNode,d=a.nodeMap[b]);z(a.nodeMap[a.rootNode],function(b){var c=!1,e=b.parent;b.visible=!0;if(e||""===e)c=a.nodeMap[e];return c});z(a.nodeMap[a.rootNode].children,function(a){var b=!1;n(a,function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(f);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=b={x:0,y:0,width:100,height:100};a.nodeMap[""].values=
b=r(b,{width:b.width*a.axisRatio,direction:"vertical"===c.layoutStartingDirection?0:1,val:f.val});a.calculateChildrenAreas(f,b);a.colorAxis?a.translateColors():c.colorByPoint||a.setColorRecursive(a.tree);c.allowDrillToNode&&(c=d.pointValues,a.xAxis.setExtremes(c.x,c.x+c.width,!1),a.yAxis.setExtremes(c.y,c.y+c.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,e=h(a.points,function(a){return a.node.visible}),d,f;n(e,function(c){f=
b[c.node.level];d={style:{}};c.node.isLeaf||(d.enabled=!1);f&&f.dataLabels&&(d=r(d,f.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(d.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=r(d,c.options.dataLabels)});t.prototype.drawDataLabels.call(this)},alignDataLabel:function(a){d&&d.column&&d.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},drawPoints:function(){var a=this,b=h(a.points,
function(a){return a.node.visible});n(b,function(b){var c="level-group-"+b.node.levelDynamic;a[c]||(a[c]=a.chart.renderer.g(c).attr({zIndex:1E3-b.node.levelDynamic}).add(a.group));b.group=a[c]});d&&d.column&&d.column.prototype.drawPoints.call(this);this.colorAttribs&&n(this.points,function(a){a.graphic&&a.graphic.css(this.colorAttribs(a))},this);a.options.allowDrillToNode&&n(b,function(b){b.graphic&&(b.drillId=a.options.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=
(a=a.point)&&a.drillId;A(b)&&(a.setState(""),this.drillToNode(b))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&A(a.parent)&&this.drillToNode(a.parent)},drillToNode:function(a,b){var c=this.nodeMap[a];
this.idPreviousRoot=this.rootNode;this.rootNode=a;""===a?this.drillUpButton=this.drillUpButton.destroy():this.showDrillUpButton(c&&c.name||a);this.isDirty=!0;f(b,!0)&&this.chart.redraw()},showDrillUpButton:function(a){var b=this;a=a||"\x3c Back";var d=b.options.drillUpButton,f,g;d.text&&(a=d.text);this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:a}).align()):(g=(f=d.theme)&&f.states,this.drillUpButton=this.chart.renderer.button(a,null,null,function(){b.drillUp()},f,g&&
g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:d.position.align,zIndex:7}).add().align(d.position,!1,d.relativeTo||"plotBox"))},buildKDTree:y,drawLegendSymbol:b.LegendSymbolMixin?b.LegendSymbolMixin.drawRectangle:void 0,getExtremes:function(){t.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;t.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,
min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};t.prototype.bindAxes.call(this);b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,a)},utils:{recursive:z,reduce:F}},{getClassName:function(){var a=b.Point.prototype.getClassName.call(this),c=this.series,d=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||f(d.interactByLeaf,!d.allowDrillToNode)?this.node.isLeaf||(a+=" highcharts-internal-node"):
a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||p(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:d?d.pie.prototype.pointClass.prototype.setVisible:void 0})})(q,D)});
